### ISSUE TITLE
windows & proxy

### ISSUE THREAD

**Issue by ami44** [laurentj/slimerjs#131]
Bonjour

je n'arrive pas à configurer slimerjs derrière un proxy (et la doc n'indique pas clairement où placer les options de slimerjs)

Préalable :
- je suis sous windows
- mes params de proxy fonctionnent avec firefox ou casperjs + phantomjs 
- je travaille avec slimerjs-master qui a les options --proxy et --proxy-auth activé dans slimerjs.bat
- slimerjs fonctionne bien avec un site en local

j'ai testé la commande avec les options de proxy avant le fichier .js : 

```SET SLIMERJSLAUNCHER="D:\Utilisateurs\ami44\xulrunner\xulrunner.exe" && "D:\Utilisateurs\ami44\slimerjs\src\slimerjs.bat" --proxy=URL.fr:PORT --proxy-auth=ami44:SECRET "D:\Utilisateurs\ami44\hello.js"```

```unknown option --proxy=URL.fr:PORT```

j'ai testé la commande avec les options de proxy après le fichier .js

```SET SLIMERJSLAUNCHER="D:\Utilisateurs\ami44\xulrunner\xulrunner.exe" && "D:\Utilisateurs\ami44\slimerjs\src\slimerjs.bat" "D:\Utilisateurs\ami44\hello.js" --proxy=URL.fr:PORT --proxy-auth=ami44:SECRET``` qui retourne alors 

```Sorry, the page is not loaded```

Donc il semble que les options sont à placer après le fichier *.js mais les params de proxy ne semblent pas pris en compte. 

J'ai essayé de passer par l'usage d'un profile mais l'option ```"network.proxy.type"``` dans le fichier ```pref.js``` est toujours ramené à ```0``` ( 0 = Direct connection, **no proxy**, http://kb.mozillazine.org/Network.proxy.type)

Je ne sais pas si j'ai loupé une étape ou si c'est un bug
Cdlt, AMi44

**Comment by Klestofer** [comment]
I'm using SlimerJS 0.9.6 on Windows. I've found out that proxy parameters must be used like this:
`slimerjs.bat script.js -proxy ip:port -proxy-auth user:pasw`

No need for '=' sign. And '-proxy-auth' parameter is supported.

Parameters passed to script may also present, and they can be in any order, even between '-proxy' and '-proxy-auth' parameters.
For example, if we want to pass param1, param2 and param3 to script.js we can use any order, like this:
`slimerjs.bat script.js -proxy ip:port -proxy-auth user:pasw param1 param2 param3`
`slimerjs.bat script.js param1 param2 param3 -proxy ip:port -proxy-auth user:pasw`
`slimerjs.bat script.js param1 -proxy ip:port -proxy-auth user:pasw param2 param3`
`slimerjs.bat script.js param1 -proxy ip:port param2 -proxy-auth user:pasw param3`
