### ISSUE TITLE
Doesn't work with webgl on remote desktop connection

### ISSUE THREAD

**Issue by zhilongjiang** [laurentj/slimerjs#136]
When I use remote desktop connection to EC2(GPU instance), slimerjs can start, but webgl is unavailable while webgl is available for the other browsers. I did more tests and found slimerjs doesn't work any remote desktop connection machines.

I can use teamviewer to replace remote desktop connection as workaround. But it would be better if this issue can be fixed.

**Comment by chriddyp** [comment]
Has anyone had luck getting this going on an EC2 GPU? I have some webgl code that I'd love to run and test on a GPU server
