### ISSUE TITLE
minor - awkward error message when no file is supplied to the slimerjs command

### ISSUE THREAD

**Issue by matanox** [laurentj/slimerjs#139]
Not sure if this is only in my configuration, but running slimerjs as follows results in the following error messages. Supplying a javascript file name to the command works just fine, so it (basically) seems my configuration is just fine.

```
$ slimerjs-0.9.0/slimerjs
script is missing
WORKER ERROR DURING SETUP Error: Failed to load script: resource://gre/modules/workers/require.js (nsresult = 0x8000ffff)
WORKER ERROR DETAIL @resource://gre/modules/osfile.jsm:23
@resource://gre/modules/osfile/osfile_async_worker.js:16
@resource://gre/modules/osfile/osfile_async_worker.js:395
```

This can help future newbs.

**Comment by metallica666** [comment]
It's fix in the version 50 of firefox
