### ISSUE TITLE
Unable to run coffee version of mocha-phantomjs

### ISSUE THREAD

**Issue by Swatinem** [laurentj/slimerjs#164]
Yesterday when I claimed I could use slimer as dropin replacement with mocha-phantomjs, I kind of lied.
It works fine now with a precompiled js version. But mocha-phantomjs is actually written in coffee for some reasons that I will never understand.

Anyway, I get the following error:
```
Script Error: In /home/swatinem/Coding/component-test/node_modules/mocha-phantomjs/lib/mocha-phantomjs.coffee, child.traverseChildren is not a function
       Stack:
         -> resource://slimerjs/coffee-script/lib/coffee-script/nodes.js: 169
         -> resource://slimerjs/coffee-script/lib/coffee-script/nodes.js: 169 (in function Base.prototype.traverseChildren/Base<)
[…]
```

I tried to update the in-tree version coffeescript to the latest one, but without success. It still fails:
```
Script Error: child.updateLocationDataIfMissing is not a function
       Stack:
         -> resource://slimerjs/coffee-script/lib/coffee-script/nodes.js: 249
         -> resource://slimerjs/coffee-script/lib/coffee-script/nodes.js: 249 (in function Base.prototype.updateLocationDataIfMissing/Base<)
[…]
```

I have absolutely no idea what is going on. But if you like, I can provide a PR to at least bump the coffee version.

**Comment by laurentj** [comment]
It seems mocha-phantomjs is not written anymore with Coffee-script. And I have no time to learn mocha-phantomjs. So I won't fix.
