### ISSUE TITLE
pdf saving hangs

### ISSUE THREAD

**Issue by ChrisJefferson** [laurentj/slimerjs#175]
Hi,

On Mac OS X  with no printers installed, the current git head has two problems:

1) If I call 'page.render("title.pdf")' with page.paperSize set to: page.paperSize = { format: 'A4', orientation: 'landscape', border: '1cm' } then it hangs.

2) The pages do not get saved to a file, they come out of my printer!

I'm happy to debug this if someone can point me towards some things I could try.

**Comment by laurentj** [comment]
I documented workarounds and tips. I don't think I could do something in SlimerJS. I close this issue. If you still have a similar issue, feel free to open a new issue.

**Comment by burningTyger** [comment]
As in #395 installing cups might solve the issue, too.
