### ISSUE TITLE
How to remove the logo?

### ISSUE THREAD

**Issue by benbro** [laurentj/slimerjs#183]
How can I remove the slimerjs logo and version form the top left?
I'm capturing the screen with avconv and the logo covers part of the page.

![slimerjs](https://cloud.githubusercontent.com/assets/75841/3115027/cb26e3bc-e700-11e3-9e68-ac1097a9d31d.png)

Thanks

**Comment by shviller** [comment]
If #339 gets merged, the logo window will be accessible from the script, so it can be closed.

**Comment by Niek** [comment]
FYI, the ``window.focus()`` trick does not work for me, a workaround is e.g. using xdotool: ```xdotool search webpage windowraise```
