### ISSUE TITLE
Please support require("system").stdin

### ISSUE THREAD

**Issue by fred-wang** [laurentj/slimerjs#188]
Just opening a feature request for stdin, which is a commonJS requirement for the system module: http://wiki.commonjs.org/wiki/System/1.0

The slimer.js documentation does not seem to mention stdin and I was enable to figure out how to access it (http://docs.slimerjs.org/current/api/system.html). require("system").stdin works for me with phantomjs.

**Comment by fred-wang** [comment]
So I assume we can do as in slimer.exit() and introduce a quick hack for that: use `read` to get the content of stdin and print it into a profile file and then make the implementation of require("system").stdin directly read from that profile file. @laurentj what do you think about that?

**Comment by masi** [comment]
PhantomJS implements both stdin and stderr, but has no documentation for it. At least write() and read() are available as methods.

IMHO it would also allow some Node scripts run within SlimerJS or at least ease the conversion, eg

// simple wrapper for Node modules
var process = {
	stdout: system.stdout,
	stderr: system.stderr,
	stdin: system.stdin
}

**Comment by fentas** [comment]
Phantomjs has on example of stdin/stdout/stderr
https://github.com/ariya/phantomjs/blob/master/examples/stdin-stdout-stderr.js

Would be awesome to see it in slimerjs.

**Comment by dcworldwide** [comment]
:+1: 

I really need this to enable slimerjs to be used within a pipeline. 

Will it be delivered in the next release?

**Comment by wyongzhi** [comment]
how long is needed？

**Comment by laurentj** [comment]
It seems there is no API in the Gecko platform to read stdin....

**Comment by laurentj** [comment]
Found a way but it will does not work under Windows..

**Comment by kensoh** [comment]
Hi @laurentj good day to you. May I check if you are aware of any issue with running SlimerJS system.stdin.read()? I've checked [0.10.3 documentation](https://docs.slimerjs.org/current/api/system.html) and the web without error reports.

When running below in a CasperJS script within a casper block, the script ends after invoking read(). 

```js
var system = require('system');
var input = system.stdin.read();
```

When running outside of a casper block, I get the error message below and the script ends.

Error reading from stream: [Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIBinaryInputStream.readBytes]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://slimerjs/addon-sdk/toolkit/loader.js -> resource://slimerjs/addon-sdk/sdk/io/byte-streams.js :: ByteReader_read :: line 68"  data: no]

I'm running Firefox 52.0.2, SlimerJS 0.10.3, CasperJS 1.1.4, macOS 10.12.4.
