### ISSUE TITLE
Please support require("system").stderr

### ISSUE THREAD

**Issue by macbre** [laurentj/slimerjs#189]
This is a feature request for adding ``stderr`` to system module as defined in [CommonJS spec](http://wiki.commonjs.org/wiki/System/1.0) and [available in PhantomJS](https://github.com/ariya/phantomjs/blob/master/examples/stdin-stdout-stderr.js).

**Comment by masi** [comment]
Yes, please :)

**Comment by ensecoz** [comment]
Is there any workaround?

**Comment by masi** [comment]
Try
```
if (!system.stderr) {
	system.stderr = system.stdout;
}
```
It won't write to stderr, but at least it won't break your code.

**Comment by ensecoz** [comment]
Thanks, but I want to be able to detect error in the script and notify back to the app.

I ended up using console.log() but in the message i prefixed with "[error]" and let's the app decide.

**Comment by wskorodecki** [comment]
I think there is still some problems.
Test script:
```
var system = require('system');

console.debug('This is a debug message.');
console.log('This is a log message.');
console.info('This is a info message.');
console.warn('This is a warning message.');
console.error('This is an error message.');

system.stderr.write('This is an error message written via system.stderr.write().' + "\n"); // Invisible.

slimer.exit(0);
```

1. I don't see the last message written via system.stderr.write() method.
2. It looks like warnings and errors are still being written to stdout instead of stderr.

I also launched `test/launch-initial-tests.js` and one error message is also invisible:
```
------ you should see the output of system.stdout
output: 
Hello World # Missing error message after this line.
------ check yourself if following values are ok
```
