### ISSUE TITLE
casper.back() not working (script appears to hang)

### ISSUE THREAD

**Issue by DarrenCook** [laurentj/slimerjs#199]
When I call casper.back() the script appears to hang, but only with SlimerJS (0.9.1), not with PhantomJS.

Looking at the window it appears the browser has moved back. The code looks like:

```
casper.then(function(){
  this.back();
  this.waitForUrl(expectedUrl);
  this.wait(200,function(){
    this.capture("eg.png");
    });
 });
```
I have `casper.options.stepTimeout = 6000`, but it sits there for at least a number of minutes (I suspect forever), so I don't think the script is reaching `waitForUrl()`. (The screenshot is not taken.)

I've added some more debug lines, and if I `console.log` just after `this.back()` that is printed. But if I change the `waitForUrl()` to look like this:
```
this.waitForUrl(expectedUrl,function(){
    console.log("URL ("+expectedUrl+") was found");
    },function(){
    console.log("TIMEOUT ("+expectedUrl+")");
    },1000);    //Only give it one second
```
it does not do anything: neither callback gets called. I.e. casper appears to get as far as calling `waitForUrl` but then neither succeeds nor times out.

(I'm testing my web app's use of the HTML history API; the tests run to completion in PhantomJS.)
(Using casperjs 1.1.0-beta3)

**Comment by muffinresearch** [comment]
Fwiw. I've seen the same thing. I had to use a `casper.open()` as a workaround.

**Comment by laurentj** [comment]
Unit tests of CasperJS show that casper.back() is working with SlimerJS.
