### ISSUE TITLE
fs api ignores fifo temp files

### ISSUE THREAD

**Issue by jamesmfriedman** [laurentj/slimerjs#230]
I've been building a distributed rendering app with Slimer, a master process is delegating jobs to sub processes. As you guys know, there is no stdin implemented in system, so I've been using individual job files.

Ideally I'd be able to use fifo (first in first out), a type of temp file that has blocking reads. This way none of the renderers will pick up the same jobs. Unfortunately the file system api as implemented registers that the file is readable, but does not register that it is a file. This failure is triggered with ensureFile on line 89 of fs.js.

To make matters worse, ensureFile is not part of exports, so I can't monkey patch it :). Any ideas will be welcome. In the meantime, I'm stuck with multiple renderers picking up the same jobs.

BONUS: or implement file locking, but that hasn't even been established in the commonjs core.

**Comment by laurentj** [comment]
@jamesmfriedman if it is not too late, i implemented system.stdin few days ago and fixed the ensureFile function ;-)
