### ISSUE TITLE
no render output file on large web site 

### ISSUE THREAD

**Issue by aliouiii** [laurentj/slimerjs#240]
as i described here :
http://stackoverflow.com/questions/26386415/phantomjs-and-slimerjs-fail-to-render-some-sites
I get no image file after executing render_multi_url.js on some website
I don't know the cause.
can any one investigate  on this .
thanks

**Comment by mingdaolu** [comment]
I see you have fixed this issue in master. but it's not included in latest release yet. (0.9.4)
is there any workaround for this issue before there is a new release available?

**Comment by laurentj** [comment]
@mingdaolu the fix I made will be available in the incoming 0.9.5 version.

**Comment by laurentj** [comment]
I created a specific issue about failed tests. We can close this issue.

**Comment by mingdaolu** [comment]
@laurentj Thanks. So when 0.9.5 plan to release?
this bug are quite frequently occur in our environment

**Comment by laurentj** [comment]
this week

**Comment by mingdaolu** [comment]
nice, thx!
