### ISSUE TITLE
Failed to load image information

### ISSUE THREAD

**Issue by juliensobrier** [laurentj/slimerjs#256]
Slimerjs 0.9.3 and Firefox 31 on Linux (CentOS 6.6)with this script:

var page = require('webpage').create();
page.open("http://lemonde.fr", function (status) {
    page.viewportSize = { width:1024, height:768 };
    page.render('screenshot.png');
//    slimer.exit();
});

 ./slimerjs test.js
Failed to load image information -
Failed to load image information -
Failed to load image information -
./slimerjs: line 172: 30362 Segmentation fault      (core dumped) "$SLIMERJSLAUNCHER" -app $SLIMERDIR/application.ini $PROFILE -no-remote "$@" 2> /dev/null

real    1m15.639s
user    0m5.415s
sys     0m0.654s

**Comment by DarrenCook** [comment]
I'm getting just one "Failed to load image information -", but no segfault; updating to the latest git version did not change this. This is through casperjs, and I don't get it using phantomjs. But everything seems fine, so at the moment it just looks like noise.
Before I open a new bug report I wanted to understand it better. What does the message mean exactly, and is there anything I can do (ideally from within casper) to get more troubleshooting information?

**Comment by laurentj** [comment]
"Failed to load image information" says that the net-log.js cannot read image informations of an image loaded by the webpage. This is a debug message that is now disabled in the latest stable version.
