### ISSUE TITLE
"quality" parameter for screenshot capturing is ignored

### ISSUE THREAD

**Issue by vbauer** [laurentj/slimerjs#259]
I tried to change quality for jpg & jpeg formats (from 0 to 1), but it did not work.

```javascript
page.render(outputFile, {
    onlyViewport: true,
    quality: quality,
    format: format
});
```

**Comment by laurentj** [comment]
It still work for me. with quality =100 or quality=10 or quality=0.1 or quality=0.9. I see differences..
