### ISSUE TITLE
Support of page.onLongRunningScript and page.stopJavascript() (PhantomJS 2.0)

### ISSUE THREAD

**Issue by abozhilov** [laurentj/slimerjs#268]
There is possible DDoS with long running JS on the opened page. There is no way to exit from slimerjs using its API. 

longrunningpage.html

```
<script>
    while(true) {}
</script>
```

```
var page = require('webpage').create();

setTimeout(function () {phantom.exit();}, 1000);
page.open('longrunningpage.html');
```

PhantomJS has callback `page.onLongRunningScript` and method `page.stopJavaScript()` with their usage the problem is solvable.

**Comment by CMCDragonkai** [comment]
What constitutes a long running script? Is it time? If it is time, how long does a script need to run before it's considered too long? @abozhilov

**Comment by abozhilov** [comment]
The script should run 10 seconds and then the `onLongRunningScript` callback is fired. For example if you have code like this on your page: 

```
while (true){}
```

After 10 seconds of execution of that snippet you will be able to stop it using `page.stopJavascript()`.

**Comment by CMCDragonkai** [comment]
How does this affect web-workers?

**Comment by abozhilov** [comment]
You should check FF documentation about the case. If Firefox emits "Stop script dialog" on long running worker, then SlimerJS will trigger onLongRunningScript callback.
