### ISSUE TITLE
Problem with arguments values that begin with "s"

### ISSUE THREAD

**Issue by adefretin** [laurentj/slimerjs#276]
When we try to use slimerjs (0.9.3) with an argument value that begin with "s", it fail and launch this error : 
 [Exception... "Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsIFile.isFile]"  nsresult: "0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST)"  location: "JS frame :: resource://slimerjs/addon-sdk/toolkit/loader.js -> resource://slimerjs/addon-sdk/sdk/io/file.js :: isFile :: line 116"  data: no]

Call example : 
 xvfb-run casperjs --engine=slimerjs test executeTests.js --inPath=XXX --vp=smart

**Comment by metaphorical** [comment]
Hi, who can push this to slimerjs NPM? Newest version available is 0.9.2. Thank you!

**Comment by laurentj** [comment]
@metaphorical you should ask it to the owner of the npm package. I don't manage it.

**Comment by Mds92** [comment]
I have the same error, the following command line;
```
casperjs.exe --userAgent="Mozilla/5.0_(Windows_NT_10.0;_Win64;_x64)_AppleWebKit/537.36_(KHTML,_like_Gecko)_Chrome/50.0.2661.102_Safari/537.36#3b2637" --engine=slimerjs Sample.js
```
returns the following error:
```
_AppleWebKit/537.36_(KHTML was unexpected at this time.
```
How should I send args?
