### ISSUE TITLE
slimerjs/xulrunner doesn't load Flash Player plugin on Fedora Linux, workaround

### ISSUE THREAD

**Issue by jeffbonhag** [laurentj/slimerjs#279]
I'm running SlimerJS 0.9.4 64-bit on Fedora Linux 20.

After installing the Flash Player yum repository from Adobe, Flash worked in Firefox but not in SlimerJS.  I managed to get around the issue by deleting the xulrunner directory distributed with SlimerJS and creating a symlink to Fedora's xulrunner:

    cd slimerjs-0.9.4
    rm -fr xulrunner
    ln -s /usr/lib64/xulrunner

I'm not sure if this will have any other consequences for SlimerJS, but it's working the way I want it to (so far).

Thanks for sharing this project!

**Comment by laurentj** [comment]
thanks for this workaround. i updated documentation.

**Comment by puravida** [comment]
Unfortunately, Fedora (tested v24) and Ubuntu still have this issue, but slimerjs v0.10.0 no longer uses xulrunner. So, I'm not sure if there's a viable workaround now. I tried numerous attempts but could not get it working. Flash was working in Firefox directly and even in slimerjs (if taking a screenshot of the desktop, outside of slimerjs, just using slimerjs to load the URL), but slimerjs could not render the flash into a screenshot image. All I ever got was an all white or all black image where the Flash would be.

**Comment by puravida** [comment]
I just confirmed that this is also an issue on CentOS 7.2. While Flash is detected and technically working, even through slimerjs, it will not capture Flash video. I suspect this affects all newer versions of Firefox (since they removed the support that was breaking OOP plugins), on any Linux platform.

**Comment by puravida** [comment]
For test purposes, to consider Flash successfully captured, you need to be able to capture the Flash version shown on this [Adobe Flash video test page](https://www.adobe.com/swf/software/flash/about/flashAbout_info_small.swf).
