### ISSUE TITLE
can you add startssl to the list of known CAs? 

### ISSUE THREAD

**Issue by makc** [laurentj/slimerjs#299]
Right now, an attempt to load files over https results in this:
![screen shot 2015-01-31 at 0 17 34](https://cloud.githubusercontent.com/assets/242577/5985258/4a9b2c24-a8e0-11e4-83cb-bc89ae056e21.png)
while it works perfectly in the browser.

**Comment by makc** [comment]
Oh, and I have this
```
--ignore-ssl-errors not supported yet
```

**Comment by laurentj** [comment]
No. Sorry. I won't change the default list of known CA of Firefox/Xulrunner. I'm not enough expert in security about SSL to change something in the default CA list. 

Any way, StartSSL is already in Firefox/XulRunner, so you have probably an other problem. Check your server configuration.
