### ISSUE TITLE
 Script Error: too much recursion

### ISSUE THREAD

**Issue by ckir** [laurentj/slimerjs#300]
I'm using SlimerJS 0.9.2 on Linux.

Why when i do this:

    var webPage = require('webpage');
    var page = webPage.create();

    page.open('http://finance.yahoo.com/echarts?s=QQQ+Interactive#', function(status) {
      if (status === "success") {
        console.log("Page Opened");
      }
    });

I get 
    Script Error: too much recursion
           Stack:
             -> undefined: 0

and some elements on the page (charts) are missing ??

**Comment by laurentj** [comment]
Please upgrade to 0.9.5 and tell me if it works

**Comment by laurentj** [comment]
I confirm the error message. However, it seems this is an error from the page itself. So I don't know what could I do...

**Comment by laurentj** [comment]
This website is a nightmare and a bloatware: there are hundred javascript and CSS warnings (in strict mode). And in Firefox there are two JS errors:

```
ReferenceError: DARLA is not defined echarts:3550
SecurityError: The operation is insecure. combo:56
```

With 500ko of minified JS, I cannot investigate
