### ISSUE TITLE
slimerjs@0.9.5 broken on macos

### ISSUE THREAD

**Issue by diffsky** [laurentj/slimerjs#301]
After using npm to install the latest slimerjs, the binary doesn't seem to be functional.

```
$ sudo npm -g update slimerjs
Password:
/usr/local/bin/slimerjs -> /usr/local/lib/node_modules/slimerjs/bin/slimerjs

> slimerjs@0.9.5 install /usr/local/lib/node_modules/slimerjs
> node install.js

Looks like an `npm install -g`; unable to check for already installed version.
Downloading http://download.slimerjs.org/releases/0.9.5/slimerjs-0.9.5-mac.tar.bz2
Saving to /usr/local/lib/node_modules/slimerjs/slimerjs/slimerjs-0.9.5-mac.tar.bz2
Receiving...
Received 781K...
Received 1565K...
Received 2352K...
Received 3134K...
Received 3919K...
Received 4701K...
Received 5486K...
Received 6275K...
Received 7061K...
Received 7848K...
Received 8633K...
Received 9426K...
Received 10209K...
Received 10993K...
Received 11775K...
Received 12557K...
Received 13342K...
Received 14124K...
Received 14919K...
Received 15702K...
Received 16484K...
Received 17267K...
Received 18063K...
Received 18846K...
Received 19630K...
Received 20426K...
Received 21209K...
Received 21993K...
Received 22783K...
Received 23567K...
Received 24353K...
Received 25162K...
Received 25949K...
Received 26731K...
Received 27513K...
Received 28301K...
Received 29124K...
Received 29907K...
Received 30703K...
Received 31490K...
Received 32277K...
Received 33066K...
Received 33852K...
Received 34637K...
Received 35455K...
Received 36239K...
Received 37021K...
Received 37805K...
Received 38587K...
Received 39369K...
Received 40151K...
Received 40936K...
Received 41730K...
Received 42531K...
Received 43313K...
Received 44113K...
Received 44895K...
Received 45684K...
Received 46466K...
Received 47251K...
Received 48033K...
Received 48818K...
Received 49604K...
Received 50393K...
Received 51175K...
Received 51960K...
Received 52787K...
Received 53583K...
Received 54368K...
Received 54533K total.
Extracting tar contents (via spawned process)
Copying extracted folder /usr/local/lib/node_modules/slimerjs/slimerjs/slimerjs-0.9.5-mac.tar.bz2-extract-1423091918907/slimerjs-0.9.5 -> /usr/local/lib/node_modules/slimerjs/lib/slimer
Writing location.js file
Done. Slimerjs binary available at /usr/local/lib/node_modules/slimerjs/lib/slimer/slimerjs
slimerjs@0.9.5 /usr/local/lib/node_modules/slimerjs
├── which@1.0.8
├── rimraf@2.2.8
├── kew@0.1.7
├── ncp@0.4.2
├── mkdirp@0.3.5
├── adm-zip@0.2.1
└── npmconf@0.0.24 (inherits@1.0.0, once@1.1.1, osenv@0.0.3, ini@1.1.0, semver@1.1.4, nopt@2.2.1, config-chain@1.1.8)
opacus: ~
$ slimerjs --version
opacus: ~
$ slimerjs --version
opacus: ~
$ which slimerjs
/usr/local/bin/slimerjs
opacus: ~
$ /usr/local/bin/slimerjs --version
opacus: ~
$
```

This is on OSX yosemite and seen on a couple of machines.

**Comment by laurentj** [comment]
Sorry, as indicated on the download page of SlimerJS, we are not responsible of npm packages...

Did you try to install SlimerJS directly [from the official tar.gz](http://slimerjs.org/download.html), and does it work?

**Comment by laurentj** [comment]
Sorry, I see in your logs that it downloads the official package of Slimerjs.

Anyway, I don't have OSX yosemite to test and debug...

**Comment by diffsky** [comment]
I have the same issue when downloading the package directly. Let me know if there's any additional debug info I can provide.

**Comment by elliotboney** [comment]
I'm getting this too on Yosemite no matter how I install. -h is the only way I can get output with v0.9.5.

However, slimerjs-0.10.0pre is working great from the package.

**Comment by laurentj** [comment]
Shame on me, I didn't test this release on my old macbook pro/Snow Leopard. And i have the same issue. Nothing happen.

It seems this is a XulRunner issue. In the SlimerJS directory, when I launch ./xulrunner/xulrunner:

```
Couldn't load XPCOM
```

Do you have the same error by launching xulrunner alone ?

I've got the same issue with XulRunner 34. Xulrunner 33 (provided with Slimerjs) is working fine.

Could you confirm on Yosemite by downloading [Xr34 from here](http://ftp.mozilla.org/pub/mozilla.org/xulrunner/releases/34.0.5/runtimes/xulrunner-34.0.5.en-US.mac.tar.bz2)? (then extract the archive and go inside XUL.framework/Versions/Current)

**Comment by diffsky** [comment]
Looks like I am getting the same

```
opacus: ~/tmp/slimerjs-0.9.5
$ ./xulrunner/xulrunner
Couldn't load XPCOM.
opacus: ~/tmp/slimerjs-0.9.5
$ cd ../XUL.framework/Versions/Current/
opacus: ~/tmp/XUL.framework/Versions/Current
$ ./xulrunner
Couldn't load XPCOM.
```

**Comment by laurentj** [comment]
Mozilla has changed its file structure since Firefox 34, for Mac. See [bug 1105044](https://bugzilla.mozilla.org/show_bug.cgi?id=1105044). I tried to package SlimerJS following same file structure as Firefox. I don't have any more the error "Couldn't load xpcom", but it doesn't launch Slimerjs, even if i do ./xulrunner --app ../Resources/application.ini.

I need help. Thanks

**Comment by diffsky** [comment]
I don't really know what I'm looking at with XULRunner tbh. I looked over the [offical docs](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/XULRunner/Getting_started_with_XULRunner) and then tried running [this helloWorld example](https://github.com/matthewkastor/XULRunner-Examples/tree/master/helloWorld) but got the same `Couldn't load XPCOM.` outcome.

The other bugs on the [tracker](https://bugzilla.mozilla.org/buglist.cgi?component=XULRunner&product=Toolkit&bug_status=__open__) suggest xulrunner bugs are going to get any attention :-/

**Comment by skycaptain** [comment]
In the Homebrew community this error is also known for a while, see Homebrew/homebrew#33558. We provided a workaround, which installs Firefox via cask.

**Comment by noose** [comment]
I have that same issue
```
root@shots:/tmp# ./slimerjs-0.9.5/slimerjs  -v
root@shots:/tmp# echo $?
255

root@shots:/# uname -a
Linux shots 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

root@shots:/# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty
```

No difference between npm version and official download.

**Comment by dmitryizmerov** [comment]
When I run slimerjs in Ubuntu 14.04 I got same bug.

**Comment by laurentj** [comment]
@dmitryizmerov I develop with ubuntu 14.04 and all is working fine for me. And the present issue is specific to MacOS. You probably have an other problem. Open an other issue (and explain exactely what happened). Or before you probably want to discuss about it on the mailing list: perhaps some requirements are not met.

**Comment by noose** [comment]
@dmitryizmerov maybe you don't have some deps? 
http://docs.slimerjs.org/current/installation.html

**Comment by dmitryizmerov** [comment]
Excuse me, my problem was in version of Firefox. Slimerjs doesnt work with FF 37 version, I dont know it's normally or no, but when I installed 36, all worked. I got next problem, that I described in theme in google groups, here link - https://groups.google.com/forum/#!topic/slimerjs/9hXjMHFfUlc

**Comment by skycaptain** [comment]
@dmitryizmerov in slimerjs 0.9.5 the maxversion of firefox is set to 36.*. you can change that by setting the maxversion to 37.* in the application.ini, as described in http://docs.slimerjs.org/current/installation.html#using-unstable-version-or-very-old-versions-of-firefox-xulrunner

**Comment by laurentj** [comment]
XulRunner is dead and is no more built by Mozilla. So there will not be releases of standalone edition of SlimerJS after Firefox 40. Users should install Firefox. So I won't fix this issue.
