### ISSUE TITLE
C:\\nppdf32Log\\debuglog.txt gets created

### ISSUE THREAD

**Issue by DarrenCook** [laurentj/slimerjs#302]
I notice after running `casper --engine=slimerjs` that "C:\\nppdf32Log\\debuglog.txt" sometimes appears in that directory (I'm using Mint 17, aka Ubuntu 14.04)  (It probably happens running slimerjs directly, but I hardly ever use it that way.)

I found some information about it here: http://askubuntu.com/a/144429/93794

I believe I'm running a vanilla clone of latest github slimerjs, and it should be using the default gecko engine, not my local firefox, but if I'm the only person seeing this let me know and I will try and narrow down which command, or which configuration, is triggering it. My local Firefox does have the Adobe PDF 9.5 plugin installed.

P.S. This can be flagged low priority. It is an annoyance, nothing more.

**Comment by laurentj** [comment]
It seems we couldn't do anything since this is an issue into the adobe pdf plugin. 

Probably we could disabled the plugin...
