### ISSUE TITLE
can't press enter

### ISSUE THREAD

**Issue by makc** [laurentj/slimerjs#303]
I tried multiple things from page.sendEvent('keydown', page.event.key.Enter); to page.sendEvent('keypress', String.fromCharCode(13)); none of them could simulate pressing enter successfully. I had to do
```javascript
page.evaluate (function () {
		var e = new Event ('keydown'); e.keyCode = 13;
		$('blah blah')[0].dispatchEvent (e);
});
```
finally. What is correct way to do this?

**Comment by laurentj** [comment]
Well, it seems that you "blah blah" does have the focus, so it doesn't receive the event....

**Comment by makc** [comment]
it does receive any other keystrokes, just not enter.

**Comment by laurentj** [comment]
After some search and tests, yes it doesn't work. The support of the Enter key code [has been removed in Firefox 30](https://developer.mozilla.org/en-US/Firefox/Releases/30/Site_Compatibility#KeyboardEvent.DOM_VK_ENTER_has_been_removed). Use the Return key code instead.

```
page.sendEvent('keypress', page.event.key.Return);
```

**Comment by makc** [comment]
Thanks for looking that up. Hope that helps someone else too.
