### ISSUE TITLE
ssl_error_no_cypher_overlap

### ISSUE THREAD

**Issue by jcalonso** [laurentj/slimerjs#304]
Not sure if this is really is an issue with slimerJs or with Gecko, maybe someone can point me in the right direction.

When I execute:

```
export SLIMERJSLAUNCHER=/Applications/Firefox.app/Contents/MacOS/firefox
casperjs --engine=slimerjs myScript.js
```
Firefox opens and shows this error:

>Secure Connection Failed
>
>An error occurred during a connection to [THE_WEBSITE_URL]. Cannot communicate >securely with peer: no common encryption algorithm(s). (Error code: ssl_error_no_cypher_overlap)
>
>The page you are trying to view cannot be shown because the authenticity of the received data could >not be verified.
>
>    Please contact the website owners to inform them of this problem.

After this it times out and closes. Any ideas? My script is opening a https website, if I open Firefox normally and go to that website, it works fine, not issues with certificates at all.

**Comment by jcalonso** [comment]
Ok I solved it by adding the `--ssl-protocol=any` option:

`casperjs --ssl-protocol=any --engine=slimerjs myScript.js`

**Comment by laurentj** [comment]
In your firefox , in about:config, what are the values for security.tls.version.min and security.tls.version.max? And which version of Firefox do you have?

**Comment by jcalonso** [comment]
Hi @laurentj 

I modified the values to be:

`security.tls.version.min = 0`
`security.tls.version.max = 3`

I'm running firefox 35.0.1

**Comment by Lukich** [comment]
I actually see the same issue.  Not using casper though. A number of sites are throwing this error, 
secure.vistaprint.com,
firstrepublichb.com,
blueshieldca.com

security.tls.version.min = 1
security.tls.version.max = 3

I'm using firefox 36.0

**Comment by laurentj** [comment]
@Lukich it seems these websites are using insecure SSL version. Mozilla disabled these insecure SSL protocol by setting security.tls.version.min  to 1.
