### ISSUE TITLE
changeUrl() function not work

### ISSUE THREAD

**Issue by mxnpu** [laurentj/slimerjs#305]
I need to change request url when onResourceRequested is triggered, just like this:
```
onResourceRequested : function(requestData, request){
    if (requestData.url.indexOf(".jpg") >= 0){
        request.changeUrl("http://example.com/example.jpg");
    }
}
```
But I received nothing in this way, it print like this in the onResourceReceived event:
```
{"id":5713, "url":"http://example.com/example.jpg", "time":"2015-02-09T03:28:27.798Z"", "headers":"[]", "bodySize":0,“contentType”:null, "contentCharset":null,"redirectURL":null,"stage":"end","status":null,"statusText":null,"referrer":"","body":""}
```
When I use phantomjs to do the same thing, it works well.
I noticed that `When doing manual redirections (by calling changeUrl() on the request object), SlimerJS (Gecko) create a request, then cancels it and create a second request, so your onResponseReceive is called for the two requests.. PhantomJS just reuse the same request`, does this feature has something to do with the above problem?

**Comment by laurentj** [comment]
Well, your 'if' test is bad, because even if  requestData.url is already http://example.com/example.jpg, you change the url. It seems the result here is an infinite loop...

**Comment by mxnpu** [comment]
Thanks for the reminding, proplem solved.
