### ISSUE TITLE
SlimerJS custom Firefox settings

### ISSUE THREAD

**Issue by Fvanraes** [laurentj/slimerjs#306]
I've been using the standalone SlimerJS for a while now, what an awesome tool :+1: Recently i needed to make SlimerJS execute with a custom Firefox in which i changed some of the preferences on an Ubuntu machine. I downloaded the SlimerJS lightweight edition and configured the `SLIMERJSLAUNCHER` environment variable to `/usr/bin/firefox`. However, SlimerJS is clearly not loading my custom preferences. 

I'm sure of the Firefox path, since:

- when running `/usr/bin/firefox` manually, a Firefox instance is in fact launched which my custom preferences, so the path is correct.
- when changing `SLIMERJSLAUNCHER` to an invalid path, SlimerJS gives me an error, so the SlimerJS instance is also correct.

As a last resort, i created a new profile with `slimerjs -CreateProfile customprofile` and replaced the contents of `~/.cache/innophi/slimerjs/iqfvuvvt.custom` with the contents of  `~/.mozilla/firefox/ya7mm1w4.default-1416092445625`, which contains my Firefox profile. This also didn't load my preferences.

Is there any way to make this possible? More specifically, i'm setting the 'Automatic proxy configuration URL' in Firefox under Edit > Preferences > Advanced > Network > Settings. 

Thanks

**Comment by laurentj** [comment]
In fact, it probably works. However SlimerJS set its own proxy preferences so it probably overwrite your own proxy settings. See [Proxy configuration](http://docs.slimerjs.org/current/configuration.html#about-proxy-configuration).
