### ISSUE TITLE
slimerjs iframe support

### ISSUE THREAD

**Issue by mxnpu** [laurentj/slimerjs#307]
I'm using casperjs + slimerjs to do some testing, but it turned out that slimerjs can't do login operation within a iframe. I also tried casperjs + phantomjs with the same code and it worked fine. This is the page I'm testing:https://login.aliexpress.com/buyer.htm?return=http%3A%2F%2Fid.aliexpress.com%2F

**Comment by laurentj** [comment]
I don't see an iframe in the page you indicate.

And I can't help you if you don't give a minimal script that show the issue.
