### ISSUE TITLE
require() with a relative path does not working?

### ISSUE THREAD

**Issue by laurentj** [laurentj/slimerjs#310]
it seems that in some case it  does not working. see https://muffinresearch.co.uk/taming-slimerjs/

**Comment by masi** [comment]
May happen also with fs.read():

Script Error: Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.appendRelativePath]

       Stack:
         -> resource://slimerjs/addon-sdk/sdk/io/file.js: 57 (in function MozFile)
         -> resource://slimerjs/addon-sdk/sdk/io/file.js: 308 (in function open)
         -> resource://slimerjs/addon-sdk/sdk/io/file.js: 162 (in function read)

**Comment by laurentj** [comment]
I did some tests, require works well with relative path. In fact, I fixed that for issue #147, for Slimerjs 0.9.2. But it seems that Stuart is using 0.10pre, with CasperJS. I need to test if the issue is with casperjs.

@masi not the same api, not related. Please create a minimal test case showing the issue and open an issue.

**Comment by laurentj** [comment]
Ok, understand why it fails. But I should see how to fix it (in casperjs or slimerjs)...

**Comment by laurentj** [comment]
bugs in capserjs side, issue n1k0/casperjs#1229

**Comment by laurentj** [comment]
it seems it has been fixed

**Comment by vikaskanani** [comment]
@laurentj I am using SlimerJS 0.10.0 but now I face new issue with VNC path:

```
D:\node\casperscripts>casperjs \\10.0.0.5\node\casperscripts\myscript.js --engine=slimerjs
Unable to open file: \\10.0.0.5\node\casperscripts\myscript.js
Error phantom.injectJs: Can't open '\\10.0.0.5\node\casperscripts\myscript.js'
Unable to load script \\10.0.0.5\node\casperscripts\myscript.js; check file syntax
```
However `\\10.0.0.5\node\casperscripts\myscript.js` exists
