### ISSUE TITLE
Is ` support available?

### ISSUE THREAD

**Issue by soaj1664** [laurentj/slimerjs#311]
Hi.

In ES6 or ES2015, one can use \` instead of parenthesis in function call. e.g., confirm\`1\` works in stable Firefox.  see http://jsfiddle.net/bf45svff/ 

My question is: Is SlimerJS's current version supports it or not? Thanks.

**Comment by laurentj** [comment]
Please ask questions on the mailing list. nd read [the Faq](http://slimerjs.org/faq.html) or [the features page](http://slimerjs.org/features.html), you have the answer.
