### ISSUE TITLE
Just dies. Exit code 255?

### ISSUE THREAD

**Issue by iliakan** [laurentj/slimerjs#319]
I installed it with npm:
```
npm i -g slimerjs
```

Then it just doesn't work. Running it on an empty file or with an example from the docs gives error 255, no output at all.

**Comment by iliakan** [comment]
P.S. I tried to download -> unpack ->  ./slimerjs ../test/initial-tests.js

Also dies 255.
MacOS latest, FF36 installed.

**Comment by iliakan** [comment]
P.P.S. Downloaded lightweight, works w/ my FF.

**Comment by laurentj** [comment]
Duplicate of #301
