### ISSUE TITLE
Give option to manually upload files

### ISSUE THREAD

**Issue by shviller** [laurentj/slimerjs#326]
It would be nice to be able to manually change the values of a form that a script filled in (Slimer not being entirely headless has its own advantages), and that includes files to upload. Currently there is no way to manually choose files to upload since Slimer's FilePicker component completely overloads the one that comes with XULRunner.

**Comment by laurentj** [comment]
Well, there is already a solution: set a handler on [webpage.onFilePicker](http://docs.slimerjs.org/0.9/api/webpage.html#webpage-onfilepicker) which will return your file path, then [send a click event](http://docs.slimerjs.org/0.9/api/webpage.html#webpage-sendevent) on the field....

**Comment by shviller** [comment]
"manually", as in "interactively and in runtime".
