### ISSUE TITLE
Array not an instanceof Array when passed into a module

### ISSUE THREAD

**Issue by masi** [laurentj/slimerjs#328]
This code reports "true" (no surprise here):

var a = [];
console.log(a instanceof Array);

But when I pass a into a function exposed by a module like in the code below, I get "false":

module.exports = function test(a) {
	console.log(a instanceof Array)
}

Actually a still behaves like an array, but the bug prevents me from verifying if the argument is an array. For what it's worth, I have no issues with the code in PhantomJS or Node.

**Comment by masi** [comment]
Interestingly in both cases the constructor is:

function Array() {
    [native code]
}

**Comment by abozhilov** [comment]
Don't rely on instanceof for Array detection. The first "bug" about that was reported long time ago in context of cross-frame scripting. Every frame has own Global Execution Context and therefore own built-in constructors. 
Seem with the modules is exactly the same case. 

If you want to detect Array object use ECMAScript 5 `Array.isArray(obj)` or if you are in ES3 environment use:    `({}).toString.call(obj) === '[object Array]'` 

What I don't understand is, why you need to detect the arrays? Personally I will permit any array-like object and want do any type detection.

**Comment by masi** [comment]
You are right, I was thinking too strict. I'll allow for array-like objects now.

I'll treat the issue with instanceof not working across execution contexts as a JavaScript oddity.

Thanks.
