### ISSUE TITLE
use https for downloading slimerjs e.g. https://download.slimerjs.org/releases/0.9.5/slimerjs-0.9.5-linux-x86_64.tar.bz2

### ISSUE THREAD

**Issue by kaizhu256** [laurentj/slimerjs#332]
i work in china and am a little paranoid about mitm code injections

please switch your downloads links to use https.  phantomjs already does so by default e.g. https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip

**Comment by laurentj** [comment]
https://download.slimerjs.org is now alive ;-) I still need to change links on the web site.

**Comment by kaizhu256** [comment]
thx! :)

**Comment by kaizhu256** [comment]
just for reference, here's a screenshot of mitm ad injection for slimerjs homepage, inside china
![chinese spyware popup ad screen shot 2014-12-22 at 0 34 28](https://cloud.githubusercontent.com/assets/280571/7336439/1406348a-ec31-11e4-8255-374dc511c884.png)

**Comment by laurentj** [comment]
nice :-)
