### ISSUE TITLE
CoffeeScript error with Firefox/Xulrunner 37

### ISSUE THREAD

**Issue by jelu** [laurentj/slimerjs#334]
Hi,

I'm getting this with latests Firefox/Xulrunner 37.0 with SlimerJS 0.9.5 and master branch, works with 36.0.4.

```
$ SLIMERJSLAUNCHER=~/xulrunner-37/xulrunner xvfb-run --auto-servernum --server-num 1 ./slimerjs ...
Error during the script execution
[Exception] Error: Permission denied to access property "CoffeeScript"  filename:coffee-scripts.js  line:8

Stack trace:
0:@coffee-scripts.js:8:177012
@coffee-scripts.js:8:2
```

**Comment by hallvors** [comment]
Error occurs here:

    typeof define == "function" && define.amd ? define(function() {
        return CoffeeScript
    }) : root.CoffeeScript = CoffeeScript

Seems there is no function named define()..

**Comment by skycaptain** [comment]
As a workaround one can deactivate coffeescript, if its not needed - like in my case - by setting `enableCoffeeScript: false` in modules\slConfiguration.jsm

**Comment by jelu** [comment]
The problem doesn't look like `define()`, its `root.CoffeeScript=CoffeeScript` which is basically `this.CoffeeScript = CoffeeScript` which is denied.

This is executed around line 100 in slLauncher.jsm. Looking at MDN this may be a issue with the principle of the sandbox and/or the origin of the objects that are denying access to `this.CoffeeScript`.

**Comment by vikeri** [comment]
Same issue here, my workaround was that I downloaded Firefox 36: https://support.mozilla.org/en-US/kb/install-older-version-of-firefox

**Comment by jelu** [comment]
I've seem to found a fix for it by defining `CoffeeScript` before loading `coffee-script.js`, can someone else test also? PR #350

**Comment by vikeri** [comment]
How do I test? I suppose I have to build slimer somehow since I don't have a modules directory in the folder I got from homebrew.

**Comment by jelu** [comment]
@vikeri You can clone my fork of slimerjs and checkout the `fix-coffee-script-37` branch or look at the commit (cc5a30b0f46db3f361f94d97fea64e7154b65e32) and make the changes to your local files.

**Comment by vikeri** [comment]
@jelu It worked :)
