### ISSUE TITLE
SlimerJS using SSLv3 by default.

### ISSUE THREAD

**Issue by navbhu** [laurentj/slimerjs#335]
This (http://docs.slimerjs.org/current/configuration.html) document says default SSL protocol is TLS but it looks like SlimerJS is using SSLv3 by default. The document also mentions that SSLv3 is deactivated because of the POODLE vulnerability.

I have tested with 0.9.5 and pre0.10.0

**Comment by laurentj** [comment]
Duplicate of issue #304
