### ISSUE TITLE
window != this outside of a module

### ISSUE THREAD

**Issue by masi** [laurentj/slimerjs#336]
In PhantomJS this and window (and global) are the same, in SlimerJS this and window are different  though both are Window objects. I don't know which approach is better, but it is a difference you must be aware when you use phantom.injectJS().

**Comment by laurentj** [comment]
The main script is considered as a module, [as indicated in the documentation](http://docs.slimerjs.org/0.9/script-execution.html). So this is a "normal" behavior, even if it brakes the compatibility with PhantomJS.
