### ISSUE TITLE
exports exposed outside of modules

### ISSUE THREAD

**Issue by masi** [laurentj/slimerjs#337]
Unlike PhantomJS an empty exports object exists in the main scope. This stops some UMD modules () from working correctly when used with phantom.injectJs(). While some of them can be used with `require()` issues may arise as SlimerJS is not Node compatible, so `phantom.injectJs()` should work in theory better if the module in question can work within the global scope.

Eg [URI.js](http://medialize.github.io/URI.js/). I can use the URI.js only with `delete(exports)` before `phantom.injectJs()`.

```javascript
(function (root, factory) {
  'use strict';
  // https://github.com/umdjs/umd/blob/master/returnExports.js
  if (typeof exports === 'object') {
    // Node
    module.exports = factory(require('./punycode'), require('./IPv6'), require('./SecondLevelDomains'));
  } else if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['./punycode', './IPv6', './SecondLevelDomains'], factory);
  } else {
    // Browser globals (root is window)
    root.URI = factory(root.punycode, root.IPv6, root.SecondLevelDomains, root);
  }
}
```javascript

**Comment by laurentj** [comment]
Sorry, this is [a choice by design](http://docs.slimerjs.org/current/script-execution.html): the main script is considered as a module. If the exports object is not there, it brakes the loading of many modules from the Mozilla Addons SDK.

Use require().

**Comment by masi** [comment]
I would, if I could. The point is that some packages are carefully designed to work either with Node or in the browser. As SlimerJS does neither find Node modules nor provides all modules shipped with Node, the only option is to use the browser version within SlimerJS. Unlike Node that has no DOM this works great even outside of a page created by the "webpage" module.

So what I am really asking for is that phatom.injectJS does not expose the modules property to the injected code. But I guess that this will be technically impossible.

**Comment by masi** [comment]
Anyway as PhantomJS does not have a module variable in the global space, the fact should be mentioned on differences-with-phantomjs.html.

Also missing:
* There is no variable "global" in SlimerJS
* "this" and "window" are not the same object (they are in PhantomJS)
