### ISSUE TITLE
Error  render SVG with filter staurate > 1

### ISSUE THREAD

**Issue by kamitori** [laurentj/slimerjs#346]
My SVG
>>&lt;svg&nbsp;id=&quot;SvgjsSvg1202&quot;&nbsp;xmlns=&quot;http://www.w3.org/2000/svg" version=&quot;1.1&quot;&nbsp;width=&quot;306&quot;&nbsp;height=&quot;400&quot;&nbsp;xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;g&nbsp;id=&quot;SvgjsG1205&quot;&nbsp;filter=&quot;url(#SvgjsFilter1206)&quot;&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;image&nbsp;id=&quot;main_image&quot;&nbsp;xlink:href=&quot;http://lorempixel.com/400/400&quot;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;width=&quot;400&quot;&nbsp;height=&quot;400&quot;&nbsp;x=&quot;0&quot;&nbsp;y=&quot;0&quot;&nbsp;&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/image&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/g&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;defs&nbsp;id=&quot;SvgjsDefs1203&quot;&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;filter&nbsp;id=&quot;SvgjsFilter1206&quot;&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;feColorMatrix&nbsp;id=&quot;saturate&quot;&nbsp;type=&quot;saturate&quot;&nbsp;values=&quot;10&quot;&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/feColorMatrix&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/filter&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/defs&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;/svg&gt;

I can't render to PNG.

Please help me !

**Comment by laurentj** [comment]
Well, what is your script?

**Comment by kamitori** [comment]
this is my script

>>var webpage = require('webpage').create();
webpage
  .open('http://domain.com/svg_file.svg') // loads a page
  .then(function(){ // executed after loading
    // store a screenshot of the page
    webpage.viewportSize =
        { width:400, height:400};
    webpage.render('svg_screen.png',
                   {onlyViewport:true});
    // then open a second page
  })

**Comment by laurentj** [comment]
duplicate of issue #283 (which is fixed now)
