### ISSUE TITLE
Embed WebDriver / GhostDriver

### ISSUE THREAD

**Issue by laurentj** [laurentj/slimerjs#35]
Webdriver is a library to support the Selenium protocol. We should include it and support these cli options:

--webdriver or --wd or -w            
--webdriver=ip:port                  
--webdriver-logfile=/path/to/logfile 
--webdriver-loglevel=[ERROR|WARN|INFO|DEBUG]
--webdriver-selenium-grid-hub=url

**Comment by masi** [comment]
Any news on that one?

**Comment by andrusha** [comment]
Meanwhile, PhantomJS 2 realsed

**Comment by cades** [comment]
+1

**Comment by bootstraponline** [comment]
I guess GhostDriver isn't supported at all currently?

**Comment by Swatinem** [comment]
Firefox has webdriver / marionette embedded. So there is really no need for this I think. Since neither is really headless, and you may need xvfb for both.

**Comment by bootstraponline** [comment]
I'd hope slimerjs is faster than using firefox directly?

**Comment by Swatinem** [comment]
slimerjs is basically a wrapper around firefox that implements the phantomjs api.

**Comment by laurentj** [comment]
@Swatinem yes, but it doesn't load the UI of Firefox, nor all components needed for the UI (no extensions for instance). Technically, SlimerJS is a wrapper around the Firefox **html rendering engine**, not around Firefox itself.

**Comment by laurentj** [comment]
@bootstraponline this is almost implemented, but some issues prevent to use it for the moment... :-/

**Comment by varya** [comment]
Would love to use this too.

**Comment by laurentj** [comment]
Ghostdriver is now activated in builds of 0.10pre, and it seems it is working. At least, there is no JS error and Ghostdriver seems to connect and listen after a selenium grid hub correctly. So I can close this issue.

See also [the documentation to know options](https://docs.slimerjs.org/master/configuration.html) to use in the command line (same as PhantomJS)

However, I didn't success to launch some Selenium tests.  With the program I used to do tests (a PHP script), I had some errors like:

```
Error forwarding the new session new session request for webdriver should contain a location header or an 'application/json;charset=UTF-8' response body with the session ID.
```

(It works well by using Phantomjs instead of SlimerJS for the selenium "driver")

But as I'm not an expert of Selenium, probably I configured something badly. And I have no idea how to fix it.

So please, [download SlimerJS 0.10pre](https://download.slimerjs.org/nightlies/0.10.0pre/), and test it with your Selenium installation. And open new issues if you have some problem, by explaining how to reproduce it. Thank you :)
