### ISSUE TITLE
Linux x86_64 package does not work on Ubuntu 14.04

### ISSUE THREAD

**Issue by chlab** [laurentj/slimerjs#353]
I tried using the slimerjs standalone edition 0.9.5 for Linux x86_64 on my Ubuntu 14.04 box.
The first pitfall is that errors aren't shown by default, so running things like `slimerjs --version` do not output anything.
Once errors are displayed I get:

    XPCOMGlueLoad error for file /opt/slimerjs-0.9.5/xulrunner/libxul.so:
    libXdamage.so.1: cannot open shared object file: No such file or directory
    Couldn't load XPCOM.

After some [brief googling](http://community.zimbra.com/desktop/f/1905/t/1130641) it looks like there seems to be a dependency on the ia32-libs library? Any help on this?

**Comment by laurentj** [comment]
Did you read [documentation about requirements](https://docs.slimerjs.org/current/installation.html)?

**Comment by laurentj** [comment]
You probably have to install the libxdamage1 package

**Comment by chlab** [comment]
Nope I missed that part of the documentation @laurentj. I'll try it again when I get around to it. Thanks for the reply.
