### ISSUE TITLE
SSL security errors

### ISSUE THREAD

**Issue by stathizzz** [laurentj/slimerjs#358]
I'm trying to open a page with slimerjs (https://www.fun-bet.com/) but it fails with error on browser :
Secure Connection Failed
An error occurred during a connection to www.fun-bet.com. Cannot communicate securely with peer: no common encryption algorithm(s). (Error code: ssl_error_no_cypher_overlap). 

I have used the latest supported Firefox and have also tested Xulrunner, but it also fails. The page successfully loads on Phantomjs and on Firefox if i open it manually. I know it has something to do with the ssl certificates on the page. Can this be fixed?

Code;
var page = require('webpage').create();
page.viewportSize = { width:1280, height:1024 };
page.open("https://www.fun-bet.com");

**Comment by laurentj** [comment]
duplicate #341
