### ISSUE TITLE
Gecko/Firefox version not compatible with SlimerJS

### ISSUE THREAD

**Issue by andreasrosdal** [laurentj/slimerjs#359]
[Freeciv-web](https://github.com/freeciv/freeciv-web) uses CasperJS with SlimerJS to provide testing of JavaScript functionality. However, recently the following error message has prevented the CasperJS tests completing correctly:

"Gecko error: it seems /usr/bin/firefox is not compatible with SlimerJS. See Gecko version compatibility."

The error message can be seen in the TravisCI build logs here:  https://travis-ci.org/freeciv/freeciv-web
This is the script which installs SlimerJS and CasperJS, then runs the test-cases: 
 https://github.com/freeciv/freeciv-web/blob/master/scripts/freeciv-web-travis.sh

TravisCI has Firefox version firefox 31.0esr. It has also been tested with Firefox 38.0.5 on a local Linux distribution.

We use  SlimerJS master from github. On 25 April, SlimerJS master version from github worked correctly.
However, the current  SlimerJS master version does not work, and gives the error message about "Gecko error" given above. Slimerjs-0.10.0pre has the same problem.  I have also tested version 0.9.5, but that didn't work. 

So which version of Slimerjs, Firefox and CasperJS can I use to get JavaScript testing on TravisCI?

**Comment by abozhilov** [comment]
Change the max version in src/application.ini 

```
MaxVersion=37.*
```

Change to: 

```
MaxVersion=38.*
```

**Comment by abozhilov** [comment]
I ran main-tests with Gecko38 and there are some regressions: 

```
------------------------ failures details
webpage with listeners should generate the expected trace for the error page
  Expected 'LOADSTARTED:http://localhost:8083/plop.html    loading url=http://qsdqsdqs.qsfdsfi/plop.html
  LOADFINISHED:http://qsdqsdqs.qsfdsfi/plop.html - undefined fail
    loaded url=http://qsdqsdqs.qsfdsfi/plop.html
  CALLBACK:fail
  ' to equal 'LOADSTARTED:http://localhost:8083/plop.html
    loading url=http://qsdqsdqs.qsfdsfi/plop.html
  LOADFINISHED:http://localhost:8083/plop.html - 4 fail
    loaded url=http://qsdqsdqs.qsfdsfi/plop.html
  CALLBACK:fail
  '.
    @file:///home/abozhilov/Projects/slimerjs/test/test-webpage-listeners.js:554:9
    b/this.AsyncSpec/<@file:///home/abozhilov/Projects/slimerjs/test/jasmine/jasmine.async.min.js:5:104
webpage with listeners should have received correct data with manual redirection
  TypeError: result.req is null in file:///home/abozhilov/Projects/slimerjs/test/test-webpage-listeners.js (line 142)
    searchRequest/listR<@file:///home/abozhilov/Projects/slimerjs/test/test-webpage-listeners.js:142:13
    searchRequest@file:///home/abozhilov/Projects/slimerjs/test/test-webpage-listeners.js:138:21
    @file:///home/abozhilov/Projects/slimerjs/test/test-webpage-listeners.js:1011:9
    b/this.AsyncSpec/<@file:///home/abozhilov/Projects/slimerjs/test/jasmine/jasmine.async.min.js:5:104
  timeout: timed out after 15000 msec waiting for something to happen
    Sorry, no stack
webpage with listeners should have received the helloframe.html page
  TypeError: result.req is null in file:///home/abozhilov/Projects/slimerjs/test/test-webpage-listeners.js (line 142)
    searchRequest/listR<@file:///home/abozhilov/Projects/slimerjs/test/test-webpage-listeners.js:142:13
    searchRequest@file:///home/abozhilov/Projects/slimerjs/test/test-webpage-listeners.js:138:21
    @file:///home/abozhilov/Projects/slimerjs/test/test-webpage-listeners.js:1051:13
    b/this.AsyncSpec/<@file:///home/abozhilov/Projects/slimerjs/test/jasmine/jasmine.async.min.js:5:104
  timeout: timed out after 15000 msec waiting for something to happen
    Sorry, no stack
webpage.onConsoleMessage should receive the message of an iframe
  Expected undefined to equal 2.
    @file:///home/abozhilov/Projects/slimerjs/test/test-webpage-callbacks.js:78:13
  TypeError: message2[0] is undefined in file:///home/abozhilov/Projects/slimerjs/test/test-webpage-callbacks.js (line 79)
    @file:///home/abozhilov/Projects/slimerjs/test/test-webpage-callbacks.js:79:13
WebPage with frames has a sub frame that can be focused
  Expected '' to equal 'frametop'.
    @file:///home/abozhilov/Projects/slimerjs/test/test-webpage-frames.js:105:9
  Expected -1 to equal true.
    @file:///home/abozhilov/Projects/slimerjs/test/test-webpage-frames.js:106:9
  Expected 'frameleft' to equal 'frametop'.
    @file:///home/abozhilov/Projects/slimerjs/test/test-webpage-frames.js:107:9
------------------------

Finished in 78.351 seconds
346 specs, 10 failures
```

**Comment by laurentj** [comment]
fixed

**Comment by andreasrosdal** [comment]
Thanks, upgrading to SlimerJS version 0.9.6 solved the problem for me.

If possible, I would prefer a warning rather than slimerjs quitting, when a too new version of Firefox is used, if that version of Firefox is likely to have worked anyway.

**Comment by abozhilov** [comment]
Quitting is better approach. IMHO before updating the application.ini all of the tests should be run to detect regressions with the new version of Firefox. Firefox devs regularly introduce regressions for extension and xulrunner apps, so it should be carefully tested, otherwise it's possible to have a non-working slimer at all.

**Comment by andreasrosdal** [comment]
If quitting, it would be nice with a more detailed error message. For example:

"Gecko error: it seems /usr/bin/firefox is not compatible with SlimerJS. You are running Firefox version 38, while SlimerJS supports versions 37 and older. See Gecko version compatibility."

**Comment by laurentj** [comment]
@andreasrosdal I would like to show this kind of message but there is a problem: how to detect the installed version of Firefox/Xulrunner BEFORE to run it... patch is welcomed (and good luck for slimerjs.bat ;-)

**Comment by abozhilov** [comment]
Probably the solution is to parse Version= in `/usr/lib/firefox/application.ini`

**Comment by tibibud** [comment]
I seem to be running into the same issue as the OP. I chose to not open a separate issue as this seems to be related.

I am using the standalone version for UNIX (0.10.0pre, 01.03.2016, nightly build). 

I do not have FF installed on my Ubuntu VM and the standalone version should automatically use the bundled XulRunner. Despite checking the application.ini (min 37.*, max 44.*) it is still somehow throwing the version incompatibility error.

Is something wrong with the 0.10.0pre?

**Comment by ariangreatzone** [comment]
Please help!
What happened with the new update?
I get the same error.. What should I change it to?

[App]
Vendor=Innophi
Name=SlimerJS
Version=0.10.0
BuildID=20160502
ID=slimerjs@slimerjs.org
Copyright=Copyright 2012-2016 Laurent Jouanneau & Innophi

[Gecko]
**MinVersion=38.0.0
MaxVersion=48.***

[XRE]
EnableExtensionManager=1

**Comment by laurentj** [comment]
@ariangreatzone  Well, you don't have the new update. The latest version is 0.10.1 https://slimerjs.org/download.html

**Comment by ariangreatzone** [comment]
Thank you..
Yea I just had to update a number in there.

**Comment by axe312ger** [comment]
So for everybody running into the same issue at the moment, here you can get the latest supported version for the time being:
https://ftp.mozilla.org/pub/firefox/releases/50.0/

**Comment by RReverser** [comment]
I'm still getting it from time to time with FF 52 and SlimerJS 0.10.3. Especially weird is how inconsistent it is, maybe some cleanup not performed when SlimerJS is shut down abnormally.

**Comment by ariangreatzone** [comment]
It solved my issues by updating the JS file

**Comment by RReverser** [comment]
Which JS file? In this case the JS I'm running doesn't matter, behaviour is occasionally reproducible with any script.

**Comment by FDiskas** [comment]
SlimerJS: "0.10.3"
Firefox: "53.0.2"
```bash
Error: Platform version '53.0.2' is not compatible with
minVersion >= 38.0.0
maxVersion <= 52.*
Gecko error: it seems /usr/bin/firefox is not compatible with SlimerJS.
See Gecko version compatibility. If version is correct, launch slimerjs
with --debug=true to see Firefox error message
```

**Comment by axe312ger** [comment]
Guys, relax, soon chrome headless is working with phantomjs and we can finally use a real browser to emulate browser tests instead of using buggy slimerjs/(old) phantomjs :)

**Comment by RReverser** [comment]
@axe312ger This is off-topic comment, and not helpful or appropriate to advertise something else on this repo. SlimerJS already uses a real browser - Firefox - and has API compatible with PhantomJS, which is one of the main reasons we're migrating to it and not Chrome Headless. Chrome Headless is just Chrome with their own debugging protocol for which, in turn, you need other tools and adapters.

**Comment by greggmojica** [comment]
How do I fix this?
