### ISSUE TITLE
Render multiple page pdf

### ISSUE THREAD

**Issue by hadim** [laurentj/slimerjs#363]
Would it be possible to render multiple pages as pdf using `page.render` ?

I am trying to render slides (made with reveal.js). So basically I am rendering the first slide then I call a method `Reveal.next` which go to the second slide and so forth until the last slide.

For now I am rendering each slide separatly which is not optimal.

Any idea ?

See the following for more details : https://github.com/astefanutti/decktape/issues/6

**Comment by laurentj** [comment]
No, it's not possible to render multiple page by doing several call of page.render.

However, you can manipulate the DOM & css (or call some JS code inside the page..), to show all slides at the same time on the page (each one below others), and the pdf will content all slides. You can adjust the size of the pdf page, to have only one slide per pages.
