### ISSUE TITLE
Antialiasing in webpage.render()

### ISSUE THREAD

**Issue by lazyeugene** [laurentj/slimerjs#367]
When xulrunner window opens,  I can clearly see that antialiasing is used on scaled or rotated images. However, in screenshot produced with webpage.render() images are scaled poorly.
Can it be fixed or there are some fundamental problems?

**Comment by laurentj** [comment]
Did you try all the available options on webpage.render()? What is you code? Which format do you output?

**Comment by vikbez** [comment]
Reproduced:

firefox rendering:
![firefox rendering](http://www.cjoint.com/doc/15_12/ELgoEbYYxwt_firefox.png)

slimerjs rendering:
![slimerjs rendering](http://www.cjoint.com/doc/15_12/ELgoEI0Vyet_slimerjs.png)


following html used:

```html
<style type="text/css">
  body {
    perspective: 1000px;
  }

  div {
    position: absolute;
    top: 20px;
    left: 20px;
    border: 1px solid black;
    transform: rotateY(20deg);
    width: 100px;
    height: 100px;
  }
</style>

<div></div>
```

slimerjs script used: 

```javascript
var page = require('webpage').create(),
    system = require('system'),
    address, output, size;

address = system.args[1];
output = system.args[2];

console.log('Processing ' + output);

page.open(address, function() {
  page.render(output);
  phantom.exit();
});
```

**Comment by OlavHN** [comment]
+1

**Comment by laurentj** [comment]
@vikbez I don't reopen this issue, since I can do nothing. SlimerJS is using Firefox's engine and does not modify it.

See the [Faq about rendering issues](https://docs.slimerjs.org/current/faq.html#the-rendering-of-my-web-site-is-not-really-like-in-my-favorite-browser-even-in-firefox).
