### ISSUE TITLE
Is SlimerJs support /dev/stdout and pipe the object to FFmpeg?

### ISSUE THREAD

**Issue by mtasuandi** [laurentj/slimerjs#369]
Hi,
I am working on one project that require to render HTML5 Animation into video file. I was using PhantomJs to directly pipe the object using /dev/stdout to FFmpeg using image2pipe and I can get it worked. The problem with the latest version of PhantomJs is, it doesn't render all the HTML5 Animation elements. Some elements are missing from the video output.

Is it possible to do the same thing with SlimmerJS? I 've tried to google the issue but I got no luck for finding the best answer.

So, it could be something like:
```javascript
page.render('/dev/stdout', { format: 'png', quality: '90' });
```
and the complete command when executing via terminal is something like:
```
xvfb-run ./slimerjs html5.js | ffmpeg -y -c:v png -f image2pipe -r 25 -t 10 -i - -c:v libx264 -vf "crop=640:360:0:0" -pix_fmt yuv420p -movflags +faststart VIDEO.mp4 2>Test/LOG.log
```

Here's my complete js file that executed by SlimmerJS:
```javascript
var webPage = require('webpage');
var page = webPage.create();

page.viewportSize = { width: 640, height: 360 };
page.open("URL_TO_HTML5_ANIMATION", function start(status) {
	function waitit(){
		var checkComp = page.evaluate(function(){
			return compready();
		});
		if(!checkComp){
			setTimeout(waitit, 500);
		}else{
			page.evaluate(function(){
				controls(false);
			});
			
			var duration = page.evaluate(function(){
				return getduration();
			});
			
			var frames = (duration * 25) / 1000;
			
			for (var i = 1; i <= frames; i++) {
				page.evaluate(function(){
					nextframe();
				});
				page.render('/dev/stdout', { format: 'png', quality: '90' });
			};
			
			slimer.exit();
		}
	}
	waitit();
});
```
I got empty result with this message comes from FFmpeg:
```
ffmpeg version N-73632-g39a04eb Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04)
  configuration: --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-avresample --disable-debug --enable-nonfree --enable-gpl --enable-version3 --enable-libopencore-amrnb --enable-libopencore-amrwb --disable-decoder=amrnb --disable-decoder=amrwb --enable-libpulse --enable-libdcadec --enable-libx264 --enable-libx265 --enable-libfdk-aac --enable-libvorbis --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libspeex --enable-libass --enable-avisynth --enable-libsoxr --enable-libxvid --enable-libvo-aacenc --enable-libvidstab
  libavutil      54. 28.100 / 54. 28.100
  libavcodec     56. 47.100 / 56. 47.100
  libavformat    56. 40.100 / 56. 40.100
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 21.100 /  5. 21.100
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.100 /  1.  2.100
  libpostproc    53.  3.100 / 53.  3.100
[image2pipe @ 0x3308ce0] Could not find codec parameters for stream 0 (Video: png, none(pc)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
pipe:: could not find codec parameters
Input #0, image2pipe, from 'pipe:':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: png, none(pc), 25 tbr, 25 tbn, 25 tbc
Output #0, mp4, to '1.mp4':
Output file #0 does not contain any stream
```

Regards,
M Teguh

**Comment by laurentj** [comment]
With your command line, ffmeg gets the output of xvfb, not slimerjs. Now, a thing I don't know: is xvfb outputs the output of slimerjs. If no, then your error is normal.

**Comment by mtasuandi** [comment]
I also tried using this command:
```
xvfb-run -e /dev/stdout ./slimerjs html5.js | ffmpeg -y -c:v png -f image2pipe -r 25 -t 10 -i - -c:v libx264 -vf "crop=640:360:0:0" -pix_fmt yuv420p -movflags +faststart VIDEO.mp4 2>Test/LOG.log
```
I'm not really sure with the -e /dev/stdout but I still got empty stream.

But, basically I can use /dev/stdout on page.render()?

Still trying to figure out.

**Comment by laurentj** [comment]
>But, basically I can use /dev/stdout on page.render()?

I don't know. Never tried.

**Comment by dcworldwide** [comment]
:+1: I have the same requirement. Our project is blocked without it :(

**Comment by dcworldwide** [comment]
@mtasuandi Any success? Have you tried running slimerjs without xvfb?

**Comment by mtasuandi** [comment]
@dcworldwide Sorry for late reply, I couldn't online for few days :)
Running the slimerjs without xvfb give me Firefox window opened. My current solution is to render the frame by frame from HTML5 animation into PNG files and then from the PNG files I just need to run the FFmpeg command to combine the PNGs into video.

Something like this:
```
page.render('PATH_TO_PNG_DIRECTORY'+i+'.png', { format: 'png', quality: '100' });
```
It will create thousand of PNG files in a folder.

After the PNG files created then combine it using FFmpeg
```
ffmpeg -y -i PATH_TO_PNG_DIRECTORY/%d.png -c:v libx264 -r 20 -t 35 -vf "crop=640:360:0:0" -pix_fmt yuv420p -movflags +faststart VIDEO.mp4 2>LOG.log &
```

Now I can get my project runs and provide better video quality with slimerjs.

**Comment by dcworldwide** [comment]
Thanks @mtasuandi. I am using the same solution. It works well but it is not efficient. 

@laurentj FYI there is a workaround as above. However piping dramatically improves the efficiency of this use case. It is also a feature presently supported in phantom.js. Please consider finding time for a fix. I would help if I could :) Thanks again

**Comment by g0morra** [comment]
An alternative solution would be to set your xvfb desktop to be the same size as your animation, render your animation on an otherwise empty page with 0 margin etc., then record the whole xvfb with ffmpeg.  

With my setup I have to use a window manager with xvfb (I use fluxbox) in order to get Slimer to respect the desktop dimensions specified.

**Comment by aread22** [comment]
@g0morra,
Could you write a tutorial on how you setup xfvb, fluxbox and slimer? I am in a similar situation and would like to know how you accomplished it.

Thank you!

**Comment by xtecox** [comment]
Does it works on windows?

page.render('/dev/stdout');

**Comment by YousefED** [comment]
An alternative (didn't get /dev/stdout working either):

    console.log(page.renderBase64("png"););

and then use as follows:

    slimerjs yourscript.js | base64 --decode | ffmpeg <your ffmpeg args>

Hope this helps!

**Comment by laurentj** [comment]
I fixed an issue in the fs module about the usage of /dev/ files. Could you try your script again with [the latest 0.10pre build](http://download.slimerjs.org/nightlies/0.10.0pre/) ?

**Comment by laurentj** [comment]
In your script you can also check the boolean returns by render(), to know it has failed (false) or not (true)

**Comment by laurentj** [comment]
I made a test with convert (from imagemagick, i don't know ffmpeg), it works for me now ;-)

```
slimerjs capture.js | convert - test.jpg
```

capture.js:

```
var page = require('webpage').create();
page.open("http://slimerjs.org/", function (status) {
    page.render('/dev/stdout', {format:'png'});
    phantom.exit();
});
```

**Comment by sami-b95** [comment]
The example given above doesn't work in my case (SlimerJS version: 0.10.3; OS: Ubuntu 16.04).

**Comment by sami-b95** [comment]
The example mentioned above doesn't work in my case (SlimerJS 0.10.3, Ubuntu 16.04, Firefox 49.0).
