### ISSUE TITLE
Why SlimerJS does not work in Ubuntu

### ISSUE THREAD

**Issue by gam2046** [laurentj/slimerjs#370]
I tried the Windows and Linux versions. In Windows it works fine, but Linux (Ubuntu) in the command line without any output. (There is no error message)
I have seen these: http: //docs.slimerjs.org/current/installation.html#requirements

I downloaded the Standalone Edition

**Comment by laurentj** [comment]
I'm developping SlimerJS with Ubuntu. it works well with me. Try with the --debug=true. Or launch xulrunner/xulrunner  directly. It should show some help if it works well, or it should show error messages if a dependency is missing.

**Comment by laurentj** [comment]
You can also launch SlimerJS with Firefox...

**Comment by gam2046** [comment]
Thank you to notice me.
I tried to run it with "--debug=true", and it says :
(process:1105): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Error: no display specified

**Comment by gam2046** [comment]
I have a website that uses a lot of XMLHttpRequest (XHR). Such as logging, load data. But the operation is not a new navigation requests, it is not guaranteed by the promise mode to perform certain operations after XHR executed. By looking at the document, I tried "webpage" object "onUrlChanged" / "onNavigationRequested" callback. But still can not after XHR finished, do specific actions.

**Comment by laurentj** [comment]
>I tried to run it with "--debug=true", and it says :
>(process:1105): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
>Error: no display specified

Well, it seems you don't have a graphical interface, right?  is it on a server ? did you install X-Windows or xvfb ?

**Comment by gam2046** [comment]
@laurentj Thank you for your answer again.
Yes, it runs on the server. I tried using xvfb, work correctly. So, it must have a graphical interface? (Xvfb is a virtual graphical interface)
So, I take it this way: In any case, SlimerJS will render web pages. Even if I do not call the render method.

**Comment by laurentj** [comment]
>So, it must have a graphical interface? 

Yes, as indicated in the faq, documentation and the home page: it is not a "headless" browser.
