### ISSUE TITLE
Add BMP support to webpage.render 

### ISSUE THREAD

**Issue by dcworldwide** [laurentj/slimerjs#372]
On my macbook (retina display), JPG and PNG quality (setting of 100) looks poor. Please allow us to export the raw screen data (BMP)

**Comment by laurentj** [comment]
> PNG quality (setting of 100) looks poor

Quality is only for jpeg, as this option does not make sens for PNG: PNG is a  lossless image format.

And BMP output is implemented in the 0.10pre (master branch).
