### ISSUE TITLE
Iterating navigator breaks with NS_ERROR_FACTORY_NOT_REGISTERED

### ISSUE THREAD

**Issue by cheald** [laurentj/slimerjs#373]
To reproduce, point slimerjs at a sample page containing:

    <script>for (var t in navigator) {}</script>

This looks like the same issue reported here: https://bugzilla.mozilla.org/show_bug.cgi?id=1094714

Per the recommendation in that thread, I cracked open omni.ja and added

    Components.utils.import("resource://gre/modules/Webapps.jsm");

to `phantom.jsm` and it seems to have resolved itself. However, I don't know enough about the project to know if this is the correct fix.

**Comment by diox** [comment]
Ran into the same issue with 0.9.6 (integrated xulrunner) and that same workaround fixed it.

**Comment by laurentj** [comment]
I think there is a better place than phantom.jsm to do this import...
