### ISSUE TITLE
Page does not update after page.sendEvent

### ISSUE THREAD

**Issue by astefanutti** [laurentj/slimerjs#375]
In [DeckTape](https://github.com/astefanutti/decktape), there is a generic mode that emulates the end-user interaction to navigate HTML presentations and export them as PDFs. Basically, the right arrow `keypress` event is sent to navigate to the next slide until no changes in the DOM is detected.

While I'm testing this generic plugin with SlimerJS, I'm facing an issue as the DOM is not updating as expected after a keyboard event is sent. Basically, when the right arrow `keypress` event is sent:

    page.sendEvent('keypress', this.page.event.Right);

The event is correctly received:

    page.evaluate(function() {
        window.addEventListener("keypress", function (e) {
            console.log("EVENT:" + e.keyCode);
        });
    );

But the Web page does not refresh.

The whole code is here: https://github.com/astefanutti/decktape/blob/ba5006a1d6d2bf7e2adbeee5c1553b6675d30453/plugins/generic.js

This works fine while executed in PhantomJS.

**Comment by laurentj** [comment]
Please provide a minimal test case showing the bug. I don't know Decktape, and don't have enough time to learn how it work.

**Comment by astefanutti** [comment]
After further troubleshooting, it happens that the root cause of this issue originates from the fact that PhantomJS is actually emitting a `keydown` DOM event when a `keypress` event is sent with the `sendEvent` API, while SlimerJS is emitting the corresponding DOM event as expected.

**Comment by laurentj** [comment]
Yes [PhantomJS have some inconsistencies with key events](https://code.google.com/p/phantomjs/issues/detail?id=1094)
