### ISSUE TITLE
Silently fails when using Firefox Nightly

### ISSUE THREAD

**Issue by neopostmodern** [laurentj/slimerjs#378]
Because of a bug in the current Firefox implementation I would like to use the Nightly build, this seems to be currently not possible. Is there any reason for the maximum version restriction?

It should also always throw an error message - even if not in debug mode - to make this more obvious. 
This is my console interaction/output:

```
$ SLIMERJSLAUNCHER=/.../firefox /.../slimerjs /tmp/tmpm8dfoerd.js
$ SLIMERJSLAUNCHER=/.../firefox /.../slimerjs --debug=yes /tmp/tmpm8dfoerd.js
Error: Platform version '42.0a1' is not compatible with
minVersion >= 17.0.0
maxVersion <= 39.*
```

**Comment by neopostmodern** [comment]
Okay, apparently there is a reason for the maximum version restriction:
```
JavaScript warning: resource://slimerjs/slUtils.jsm, line 155: JavaScript 1.7's let blocks are deprecated
2015-08-08T13:49:47.678Z [DEBUG] Gecko version: 42.0a1
2015-08-08T13:49:47.678Z [DEBUG] script args: /tmp/tmpm8dfoerd.js
2015-08-08T13:49:47.679Z [DEBUG] Configuration: debug=yes
2015-08-08T13:49:47.679Z [DEBUG] Configuration: Script=/tmp/tmpm8dfoerd.js
2015-08-08T13:49:47.679Z [DEBUG] Configuration: workingDirectory=/.../firefox
JavaScript strict warning: resource://gre/modules/TelemetryEnvironment.jsm, line 398: ReferenceError: reference to undefined property this._environment._currentEnvironment.addons
Error during the script execution
[Exception] Error: Sandbox must subsume sandboxPrototype  filename:  line:0

Stack trace:
0:JS frame :: chrome://slimerjs/content/slimerjs.js :: startup :: line 23
1:JS frame :: chrome://slimerjs/content/slimerjs.xul :: onload :: line 1
2:native frame :: <unknown filename> :: <TOP_LEVEL> :: line 0
JavaScript strict warning: resource://gre/modules/TelemetryStorage.jsm, line 1529: ReferenceError: reference to undefined property ex.becauseNoSuchFile
```

I'd then just ask for a more obvious error message ;)

Any idea when it will be `42.*` compatible?

**Comment by jelu** [comment]
Hi, can you test https://github.com/laurentj/slimerjs/pull/380 ?

**Comment by neopostmodern** [comment]
Sure (I changed the `.ini` to allow `42.*`):
```plain
Gecko error: it seems /.../firefox is not compatible with SlimerJS. See Gecko version compatibility.
```

**Comment by jelu** [comment]
@neopostmodern: Yes, I only bumped the Gecko version to 40.* in the PR so you will need to change that. But did the PR work for you?

**Comment by neopostmodern** [comment]
No, I got the above error. That's *not* the error message you get if you have a version number mismatch, but an actual *Gecko* incompatibility error.
Not sure what's happening around Gecko right now to provoke such a thing, but that's what *it* said.

**Comment by laurentj** [comment]
Try the [latest unstable build](https://download.slimerjs.org/nightlies/0.10.0pre/slimerjs-0.10.0pre.zip) and tell me if it is ok for you

**Comment by neopostmodern** [comment]
FF40: Yes.
FF42.0a1: No, error message as above.

**Comment by laurentj** [comment]
>FF42.0a1: No, error message as above. 

of course, you have to set maxversion to 42.*. I didn't set it to this value because some unit tests fail for 41.0b1 and 42.0a2...

**Comment by neopostmodern** [comment]
I had forgot that, indeed. 
But it turns out `42.*` somehow isn't enough, `43.*` does the trick. Rendered, and image looks correct.

Is this that already the error message I was filing this bug for?
