### ISSUE TITLE
Latest build cannot exit on Windows

### ISSUE THREAD

**Issue by smiziara** [laurentj/slimerjs#386]
Dears,

Im using the 0.10.0-pre on Windows with Firefox 40.0.3, and both slimer.exit or phantom.exit throws an exception and not close.

[Exception... "Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS
_DENIED) [nsIFileOutputStream.init]"  nsresult: "0x80520015 (NS_ERROR_FILE_ACCES
S_DENIED)"  location: "JS frame :: resource://slimerjs/slUtils.jsm :: slUtils.wr
iteExitStatus :: line 186"  data: no]

Previous versions works.

**Comment by abozhilov** [comment]
Could you run slimerjs with custom profile dir with 777 permissions and tell us the result.

**Comment by smiziara** [comment]
I am running with a custom profile, and in a cmd with Administrator permissions.

You mean give the profile folder permission Full Control for Everyone?

**Comment by abozhilov** [comment]
Yes, seems as permissions problem. Unfortunately there is no way to implement exit status codes from SlimerJS and we use that monkey patch.

**Comment by laurentj** [comment]
I don't know how to reproduce. It works for me
