### ISSUE TITLE
slimerjs-0.9.6.zip won't unzip

### ISSUE THREAD

**Issue by JulianBirch** [laurentj/slimerjs#391]
Has anyone seen this?

```
> wget http://download.slimerjs.org/v0.9.6/slimerjs-0.9.6.zip
> unzip ./slimerjs-0.9.6.zip 
Archive:  ./slimerjs-0.9.6.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ./slimerjs-0.9.6.zip or
        ./slimerjs-0.9.6.zip.zip, and cannot find ./slimerjs-0.9.6.zip.ZIP, period.
```

The same zip file opens up fine in the file explorer in Ubuntu/Unity, but won't unpack on the command line. I've got a travis build demonstrating the same problem: 

https://travis-ci.org/JulianBirch/cljs-ajax

The .tar.bz file doesn't display any such problems.

**Comment by JulianBirch** [comment]
Clank. The file is actually an html file.

**Comment by laurentj** [comment]
Where did you get this link?

The [download page](https://slimerjs.org/download.html) doesn't have this link (or did I miss something?)

**Comment by JulianBirch** [comment]
Actually, I was reading the instructions from https://github.com/travis-ci/travis-ci/issues/1290, which contains an incorrect link. :(
