### ISSUE TITLE
Problems with using CLI on Windows 7

### ISSUE THREAD

**Issue by 2ur1st** [laurentj/slimerjs#392]
Example:
simple CLI command not retrun version SlimerJS
<code>
slimerjs -v
</code> 

This code raised exception
<code>
slimerjs --proxy=192.100.1.1:3129 --proxy-auth=user:pass --proxy-type=socks5 script.js 
</code> 
unknown option: --proxy=192.100.1.1:3129

but command 
<code>
slimerjs -h
</code> 
good working and return the help-text

What i should doing for using CLI options in SlimerJS

OS: Windows 7 Proffesional 64-bit
SlimerJS: version 0.9.6.

**Comment by laurentj** [comment]
>simple CLI command not retrun version SlimerJS

It works for me (under Cygwin)

>What i should doing for using CLI options in SlimerJS

The documentation of the next version [indicates how](http://docs.slimerjs.org/nightly/configuration.html) : For Windows users: if an option does not work, remove the equal sign and the first dash. For example, --proxy=localhost becomes -proxy localhost.
