### ISSUE TITLE
Configuration --proxy-type=system not working

### ISSUE THREAD

**Issue by klausbayrhammer** [laurentj/slimerjs#393]
In the [slimerjs-docs](https://docs.slimerjs.org/current/configuration.html) I've found that it is possible for to configure slimerjs to use the proxy specified by the operating system `--proxy-type=system`. Unfortunately it didn't work as I tried it with the following setup:

OS: Centos7
Proxy set via environment variables in .bashrc `export http_proxy=http://user:pwd@proxyip:port`

```javascript
//helloworld.js
var page = require("webpage").create();
page.open("http://slimerjs.org")
    .then(function(status){
         if (status == "success") {
             console.log("The title of the page is: "+ page.title);
         }
         else {
             console.log("Sorry, the page is not loaded " + status);
         }
         page.close();
         phantom.exit();
    })
```
When I now run `slimerjs --proxy-type=system helloWorld.js` I would expect slimerjs to pick up the proxy configuration from the $HTTP_PROXY environment variables, but unfortunately it doesn't work.

**Comment by DarrenCook** [comment]
SlimerJS passes the hard work on to Firefox:
   https://github.com/laurentj/slimerjs/blob/87e0ff1d666897754a914131d8f1744195ee4d7a/src/modules/slConfiguration.jsm#L196

And here is what I found on the subject, regarding Firefox:
   http://kb.mozillazine.org/Network.proxy.type

Why not try setting network.proxy.type to 5 in your local firefox, and check it works as you expect. Or, in other words, get it to work in Firefox, and it should start working in SlimerJS :-)

**Comment by laurentj** [comment]
I investigated into the code source of Firefox, to see what it does for "system" proxy type. It seems, [under linux](http://mxr.mozilla.org/mozilla-release/source/toolkit/system/unixproxy/nsUnixSystemProxySettings.cpp), that Firefox is using  GConf or Gnome settings to retrieve proxy settings. So it seems Firefox doesn't use the http_proxy environment variable. 

I will document that informations.
