### ISSUE TITLE
Pre 0.10 version pdf hangs in Ubuntu 15.04

### ISSUE THREAD

**Issue by svjkumar** [laurentj/slimerjs#395]

**Comment by svjkumar** [comment]
The PDF process is working well in Debian 7

**Comment by burningTyger** [comment]
There can any number of reasons for failure. For one I had some dependencies missing in Arch, notably Ghostwriter and or cups which I installed.

**Comment by svjkumar** [comment]
Thanks @burningTyger i just installed cups in ubuntu 15.04 and PDF is working just fine.

**Comment by burningTyger** [comment]
Ok, I tried again and it boils down to only cups. Same solution worked on Arch, too.

**Comment by abecks** [comment]
Trying to get PDF generation working with 0.10 on Centos6. I've installed CUPS but still not getting any PDFs written. Do I need to do any additional configuration on CUPS for this to work?

**Comment by burningTyger** [comment]
@abecks do you get any error messages? Is png-generation working?

**Comment by abecks** [comment]
Figured it out, CUPS was not automatically started after ``yum install cups``.

For anyone else on CentOS6, I am using ``yum install firefox`` (currently v38, 40 did not work) with the command line ```SLIMERJSLAUNCHER="/usr/bin/firefox" xvfb-run slimer script.js```

The packaged XulRunner in 0.10 does not work on CentoS6 (Gecko incompatibility error), hence needing to install Firefox 38 manually.

**Comment by burningTyger** [comment]
Yikes, this should produce some error message. I spent at least three hours again on my production server to find out why PDF can't be printed until I remembered to `apt-get install cups`.
