### ISSUE TITLE
Basic auth and page access

### ISSUE THREAD

**Issue by burningTyger** [laurentj/slimerjs#396]
I have a site protected by basic auth. I have a script like this:

```Javascript
var page = require('webpage').create(),
    system = require('system'),
    address, output, size;
page.settings.userName = system.args[5];
page.settings.password =  system.args[6];

address = system.args[1];

output = system.args[2];
page.paperSize = {
  format: system.args[3],
  orientation: system.args[4],
  margin: '0px'
};
page.open(address, function (status) {
  if (status !== 'success') {
      console.log('Unable to load the address!');
      phantom.exit(1);
  } else {
      window.setTimeout(function () {
          page.render(output);
          phantom.exit();
      }, 200);
  }
});
```

So I'm setting my login credentials via `page.settings.userName` and 
`page.settings.password`.

Slimer does use these credentials to access my site but it first tries to access the site w/o authentication which results in a lot of 401s. Is there a way to tell slimer to always use credentials?

**Comment by laurentj** [comment]
I updated the documentation by indicating how to avoir 401 response: you have to set directly headers on your requests.
