### ISSUE TITLE
OS X El Capitan

### ISSUE THREAD

**Issue by brunowego** [laurentj/slimerjs#398]
I get issues with El Capitan, perhaps have incompatibilities with this version of OS X. When try see the version don't display anything.

![bug](https://cloud.githubusercontent.com/assets/441774/10996222/588fd5da-846a-11e5-8d3a-117a84cad0cc.gif)

Thanks!

**Comment by brunowego** [comment]
More details:

```bash
$ uname -a
Darwin macbook 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 19:41:34 PDT 2015; root:xnu-3247.1.106~5/RELEASE_X86_64 x86_64
$ brew install slimerjs                                                                                                                                                                         
Warning: slimerjs-0.9.6 already installed
```

**Comment by laurentj** [comment]
and with 

```
slimerjs --version --debug=true 
```

?

**Comment by brunowego** [comment]
Yes, we have a output!

![bug](https://cloud.githubusercontent.com/assets/441774/11030833/aaf3c864-86b7-11e5-935a-fd4bad048323.gif)

**Comment by laurentj** [comment]
Ok, so no issue...

**Comment by brunowego** [comment]
@laurentj, I understood the issue is with firefox edge version. Thanks!
