### ISSUE TITLE
SlimerJS 0.10.0pre broken with Firefox 42

### ISSUE THREAD

**Issue by andreasrosdal** [laurentj/slimerjs#399]
SlimerJS 0.10.0pre is broken with Firefox 42.  

The error message is: "Gecko error: it seems /usr/bin/firefox is not compatible with SlimerJS. See Gecko version compatibility."

https://travis-ci.org/freeciv/freeciv-web/builds/89671632

May we have a new pre-release of SlimerJS working with the latest stable version of Firefox?

**Comment by burningTyger** [comment]
change the `application.ini` file to have `MaxVersion=42.*`.

**Comment by wmhilton** [comment]
Already fixed in 5dac5db6e0fe6c0f8c7ab6ff4c227c0982ec2f97 :)

**Comment by laurentj** [comment]
@wmhilton even if the MaxVersion has been set, we should be sure that all tests are ok before releasing a new version declared "compatible with Fx42" (this is why I keep this issue opened)

**Comment by burningTyger** [comment]
I think it's more a question of documentation. If there was a proper error message telling the user what's going on then I think we could leave things as they are. I think many of us are just irritated by a "broken" slimer.js because we updated our Firefox without noticing that it also breaks slimer.js.

**Comment by wmhilton** [comment]
@laurentj Oh, I see. 
@burningTyger It would be nice if it just threw a warning rather than a fatal error. Or if it had a "--force" flag to ignore the MaxVersion or something like that.

**Comment by laurentj** [comment]
>It would be nice if it just threw a warning rather than a fatal error. Or if it had a "--force" flag to ignore the MaxVersion or something like that.

No, we can't without patching Gecko/Firefox. This is Gecko/Firefox which reads application.ini and which exit if values do not correspond, not SlimerJS.

**Comment by laurentj** [comment]
Maxversion is now set to 44. Almost tests are green. SlimerJS is working well with 44. However I leave this issue opened until I fix remaining failed tests.
