### ISSUE TITLE
Running SlimerJS from PHP script on Ubuntu 14.04

### ISSUE THREAD

**Issue by Sitronik** [laurentj/slimerjs#413]
Dear Laurent Jouanneau, I can not get a script to run slimerjs in php script.
From the console, everything works without problems.

php script:
putenv("PHANTOMJS_EXECUTABLE=/usr/local/bin/phantomjs");
putenv("CASPERJS_EXECUTABLE=/usr/local/bin/casperjs");
putenv("SLIMERJS_EXECUTABLE=/usr/local/bin/slimerjs");
putenv("DYLD_LIBRARY_PATH"); 
putenv("SLIMERJSLAUNCHER=/home/sitronik/slimerjs/xulrunner/xulrunner");
echo shell_exec("xvfb-run -a slimerjs exslimer.js some_url"); 
a php script just hangs.

slimerjs script:

var page = require('webpage').create();
system = require('system'),
url = system.args[1];
var startTime;

page.onLoadStarted = function () {
    startTime = new Date()
};
page.onLoadFinished = function (status) {
    if (status == "success") {
        var endTime = new Date()
        console.log('The page is loaded in '+ ((endTime - startTime)/1000)+ " seconds" );
    }
    else
        console.log("The loading has failed");
};

page.open(url, function (status) {
page.includeJs('/var/www/html/js/jquery.js');	

var fridges = page.evaluate(function(){
    
	$( ".save-time" ).after( "<div id=\"myclickplay\" onclick=\"uppodSend('flash','play');\" title=\"Пуск\">play</div>" );
    $( "#myclickplay").click();
    return $('html').html();
        });

    console.log(fridges);

page.onResourceRequested = function(request) {
  var myRequested = 'Request ' + JSON.stringify(request, undefined, 4);	
  console.log(myRequested);

  var mp4 = myRequested.search( /http:\/\/[a-z]+[0-9]+\.some_url\/(.*?).(mp4|flv)/i );
            if(mp4 > 0) {
var content_mp4 = myRequested.match( /http:\/\/[a-z]+[0-9]+\.some_url\.pw\/(.*?).(mp4|flv)/mi );
slimer.exit()  

 }

   };
});

Please tell me how to get to work slimerjs script in php?

**Comment by Sitronik** [comment]
Thank you all, I solved the problem of start-up groups and change user Apache

**Comment by ImpactSeo** [comment]
Hey @Sitronik,

could you please provide more informations on how you change user/group permission

I'm able to launch casperjs+(phantom|slimer) from command line with my regular user.
I'm able to launch casperjs+(phantom|slimer) from php script command line with my regular user.
I'm able to launch casperjs+phantom from php script command line with apache user.
I'm UNABLE to launch casperjs+slimer from php script command line with apache user.

So my conclusion is firefox binary is not accessible (excecutable) to apache user ! Would you conclude the same ?
