### ISSUE TITLE
Slimerjs POST, GET, AJAX, JSON

### ISSUE THREAD

**Issue by Sitronik** [laurentj/slimerjs#414]
Dear Laurent Jouanneau, please tell me i can transfer data in slimersjs script by methods POST, GET, AJAX, JSON of PHP?

**Comment by laurentj** [comment]
I don't understand your question. "AJAX" or "JSON of PHP" are not HTTP methods.  And what is "JSON of PHP"?

**Comment by Sitronik** [comment]
Ok, I'll try to explain.
How can I transfer data from a php script in the slimerjs script?
Is it possible?

"JSON of PHP" http://api.jquery.com/jquery.getjson/
I tried to run this code:

php script:
header('Content-Type: application/x-javascript; charset=utf8');
$url = "http://example.com";        
$json = array("url" => $url);
echo json_encode($json);

slimerjs script:
var page = require('webpage').create();
system = require('system');
url = "http://example.com";
page.viewportSize = {width: 800, height: 600};

page.open(url, function (status) {
page.includeJs('jquery.js');
page.evaluate(function() {

      $.getJSON('json.php', function(data) {
        s = "";
        $.each(data, function(key, val) {
          //s= s + key+' => ' + val + '<br/>'
          s = val
        });
        console.log(s);
      });
   
       });
  });

**Comment by laurentj** [comment]
why don't you call directly the json ??

```
var page = require('webpage').create();
page.open("http://example.com/json.php", function (status) {
     if (status == "success") {
         let json = page.content;
         // do something with json
        
     }
     slimer.exit();
});
```

And please ask questions on the mailing list.
