### ISSUE TITLE
0.9.5 missing but 0.9.6 present!

### ISSUE THREAD

**Issue by ekkis** [laurentj/slimerjs#418]
if I do a simple upgrade of npm I get an error that points to slimerjs as the culprit.  I've tried clearing the npm cache, removing the `~/.npm` directory, uninstalling slimerjs but to no avail.  in fact, if I look in the `~/.npm/slimerjs` directory I see 0.9.6 but not 0.9.5... so something is requiring the older version.  can anyone help me figure out what it might be?

```
ekkis$ npm upgrade
npm WARN deprecated lodash@0.9.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "upgrade"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code EREADFILE

npm ERR! Error extracting /Users/ekkis/.npm/slimerjs/0.9.5/package.tgz archive: ENOENT: no such file or directory, open '/Users/ekkis/.npm/slimerjs/0.9.5/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ekkis/Downloads/client-side-testing-0.1/npm-debug.log
```

**Comment by laurentj** [comment]
[As indicated onto the website](https://slimerjs.org/download.html), we are not responsible of the npm package. See with the npm package maintainer.
