### ISSUE TITLE
environment variables are not being passed

### ISSUE THREAD

**Issue by nathanboktae** [laurentj/slimerjs#421]
with 0.9.6 and current master (0.10.0pre)

```shell
$ echo console.log(JSON.stringify(Object.keys(require(\'system\').env))) > evars.js
$ FOO=bar slimerjs evars.js
[]
```

**Comment by laurentj** [comment]
Environments are passed. If you do 

```
console.log(require('system').env.FOO)
```

You'll see "bar".

However there is an issue with Object.keys. Then `env` property is a javascript Proxy object and probably something is missing in the implementation...
