### ISSUE TITLE
onResourceError doesn't fire for missing CSS

### ISSUE THREAD

**Issue by nathanboktae** [laurentj/slimerjs#424]
https://travis-ci.org/nathanboktae/mocha-phantomjs-core/builds/104250465

See test [here](https://github.com/nathanboktae/mocha-phantomjs-core/blob/669bc98d68a00f7fbeab16e281f7bee15a2aa235/test/resource-errors.html) and [here](https://github.com/nathanboktae/mocha-phantomjs-core/blob/669bc98d68a00f7fbeab16e281f7bee15a2aa235/test/core.tests.coffee#L330-L333)

Works in phantomjs1 and 2, but not slimerjs.

**Comment by laurentj** [comment]
New unit tests shows that onResourceError is called. It works for me.
