### ISSUE TITLE
doesn't work with Firefox 44

### ISSUE THREAD

**Issue by janecakemaster** [laurentj/slimerjs#425]
environment: 
* SlimerJS 0.9.6
* Mac OSX El Capitan
* Firefox 44

**Comment by burningTyger** [comment]
That's because `application.ini` has a setting that limits slimer.js to a fixed `MaxVersion`. Feel free to change the calue to `44.x` to make it work again. Usually no problem.

**Comment by laurentj** [comment]
Fixed in 0.10pre
