### ISSUE TITLE
page.content is wrong for a page

### ISSUE THREAD

**Issue by yakshaman** [laurentj/slimerjs#427]
Hello,

ENV : Debian jessie 8, slimerjs 0.9.5, firefox 35.0.1

I am running this script : 

    var page = require('webpage').create(),
        system = require('system'),
        address;

        address = system.args[1];

       console.log('request dump for id 1');

        page.onResourceReceived = function (res) {
            if (res.id == 1) {
                    console.log('received: ' + JSON.stringify(res, undefined, 4));
            }
        };

        page.open(address, function (status) {
            console.log('page.content :');
            console.log(page.content);
            phantom.exit();
        });

on this urls : http://www.chanel.com/fr_FR/parfums-beaute/parfums/p/femmes.html

and the page.content is completely off is you compare it to the dump from the onressourcereceived
which is bringing back the correct content.

if i do a curl http://www.chanel.com/fr_FR/parfums-beaute/parfums/p/femmes.html it comes back ok

just with page.content the result is completely off

will continue my tests and source exploration to find better info

**Comment by laurentj** [comment]
it seems that many JS script took too much time to build the page, and so page.content is called too early. page.content returns the live content, not the original source code.

From my point of view, the page you point really needs some improvements. Almost 6Mo of content, 263 http requests. Well...
