### ISSUE TITLE
XULRunner application layout docs are available

### ISSUE THREAD

**Issue by bmcorser** [laurentj/slimerjs#428]
@laurentj not sure if you're aware, but the guys over at Mozilla have made some nice docs showing application layout for XULRunner 39/38 ... not sure if that's enough to squash https://github.com/laurentj/slimerjs/blob/master/buildpackage.sh#L11

I'm happy to help out, but having no experience of XULRunner I might not be all that useful ...

**Comment by laurentj** [comment]
XulRunner is dead. No more build by Mozilla since few month, and Its sources are not anymore in the Mozilla tree. So I won't fix MacOS layout. I should document this.

**Comment by bmcorser** [comment]
Does this kill SlimerJS, or just the possibility of getting newer FF builds on Mac OS?

**Comment by laurentj** [comment]
No, it does not kill SlimerJS. You just have to install Firefox to run SlimerJs.

**Comment by bmcorser** [comment]
http://ftp.mozilla.org/pub/xulrunner/nightly/latest-trunk/Deprecation_notice.txt and https://groups.google.com/forum/#!msg/mozilla.dev.platform/_rFMunG2Bgw/C-4PcHj9IgAJ

**Comment by bmcorser** [comment]
@laurentj cool cool

But we are still limited to older versions of FF, however?

**Comment by laurentj** [comment]
No. 0.10pre is compatible with Firefox 44. Probably 0.9.6 too by changing the application.ini file (but I will not maintain it anymore and I plan to release 0.10 soon)

**Comment by bmcorser** [comment]
Groovy, I'll pass it on to our internal users `:D`

**Comment by bmcorser** [comment]
(reopen if you want the issue! ... but I'm happy)
