### ISSUE TITLE
page.sendEvent('click', x, y) is not firing a click event

### ISSUE THREAD

**Issue by nathanboktae** [laurentj/slimerjs#430]
In `mocha-phantomjs-core` we have a test ( [html](https://github.com/nathanboktae/mocha-phantomjs-core/blob/99980b3cfb14001e528ff725fedafd6d98a15f13/test/send-event.html#L8-L9), [browser code](https://github.com/nathanboktae/mocha-phantomjs-core/blob/99980b3cfb14001e528ff725fedafd6d98a15f13/test/lib/send-event.js#L6) ) that calls `page.sendEvent('click', 5, 5)` on a button on the page that is [failing only in slimerjs](https://travis-ci.org/nathanboktae/mocha-phantomjs-core/jobs/108208887#L246) but not phantomjs 1.9.8, 2.0, or [2.1](https://travis-ci.org/nathanboktae/mocha-phantomjs-core/jobs/108208886#L228). If I manually click the button while the window is up, the test passes.

**Comment by laurentj** [comment]
Please give us a minimal test case. Unit tests are ok.

**Comment by nathanboktae** [comment]
I have them liked in my report. You can run it via:

```shell
git clone https://github.com/nathanboktae/mocha-phantomjs-core
cd mocha-phantomjs-core
npm install
slimerjs mocha-phantomjs-core.js test/send-event.html
```

My Results:

```
~/temp/mocha-phantomjs-core b1e0323|master ✔
 7:00PM ᐅ phantomjs2 mocha-phantomjs-core.js test/send-event.html


  Send Event
    ✓ click on "Update target" button


  1 passing (26ms)


~/temp/mocha-phantomjs-core b1e0323|master ✔
 7:00PM ᐅ ~/github/slimerjs/src/slimerjs mocha-phantomjs-core.js test/send-event.html


  Send Event
    1) click on "Update target" button


  0 passing (9ms)
  1 failing

  1) Send Event click on "Update target" button:

      expected '' to equal 'button was clicked'
      + expected - actual

      +button was clicked
```

**Comment by laurentj** [comment]
Sorry, this is not a minimal test case, since there many other packages that may be responsible of this bug...

I would prefer a patch on our unit tests case, showing the issue.

**Comment by laurentj** [comment]
New unit tests shows that it works.
