### ISSUE TITLE
commandline.js :: externalScriptHandler.declareScript :: line 62"  data: no]

### ISSUE THREAD

**Issue by rohitkeshwani07** [laurentj/slimerjs#431]
Previously it was working fine on my Ubuntu but now it throws this error when i try to do 
 ~/Desktop/slimerjs/slimerjs textexample.js

[Exception... "Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsICommandLine.resolveFile]"  nsresult: "0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST)"  location: "JS frame :: jar:file:///home/supriyo/Desktop/slimerjs/omni.ja!/components/commandline.js :: externalScriptHandler.declareScript :: line 62"  data: no]

**Comment by abhinavgarg89** [comment]
Hey...how did you solved this issue...even I am getting the same..
