### ISSUE TITLE
webExtensions

### ISSUE THREAD

**Issue by jefleponot** [laurentj/slimerjs#434]
Hi @laurentj 

Sorry I can't access to google forum, so I make an issue .

Xulrunner is yet out of date and next version of Firefox (45) will be adapted to webExtensions add-ons.
Do you think it could be possible to rewrite SlimerJS with mozilla webExtensions ?

Regards,
jef

**Comment by DarrenCook** [comment]
You can have slimerjs use any installed version of Firefox, by setting the `SLIMERJSLAUNCHER` environment variable to point to it.

(If it does not run, try editing `MaxVersion` in src/application.ini; I think it is 44.* currently, so you might need to change it to be 45.*, then test to see if anything breaks.)

**Comment by laurentj** [comment]
SlimerJS is not an extension. It is a browser. And it is impossible to develop a browser with WebExtension. 

API provided by WebExtension are just a joke. It's ok to add a button and do "hello world" or  interact with a page. It's not ok to take screenshot, to inspect network activity, to manipulate page loading, to changes Gecko preferences, or to do everything else that SlimerJS must do...
