### ISSUE TITLE
Unable to install SlimerJs on ubuntu fresh instance

### ISSUE THREAD

**Issue by iPrateek032** [laurentj/slimerjs#435]
I tried following steps but still unable to install

 1. Downloaded latest SlimerJS(stand alone) [from this][1]
 2. Extracted the downloaded file and moved to /home/ubuntu/automation/
 3. then created symlinks by doing following commands

    > cd automation

    > sudo ln -s /slimerjs /usr/local/share/slimerjs

    > sudo ln -s /usr/local/share/slimerjs/src/slimerjs /usr/local/bin/slimerjs

  [1]: http://slimerjs.org/download.html#standalone

after all, when i tried to check whether it got installed or not by checking slimerjs version , it displays 
> slimerjs: command not found

**Comment by laurentj** [comment]
hi

You said you installed slimerjs into /home/ubuntu/automation/, and then you tried to create links from an other directory. So It's normal it doesn't work. Or something is wrong in your description.

**Comment by laurentj** [comment]
Given informations are invalid, and asked informations were not given.
