### ISSUE TITLE
Missing phantom.proxy() or slimer.proxy() method

### ISSUE THREAD

**Issue by wskorodecki** [laurentj/slimerjs#436]
PhantomJS have undocumented phantom.proxy() method which will return defined proxy as a string. I didn't find this method in SlimerJS.

For us this method is very useful, because we can check if a proxy has been set to determine if we should add a special header for every request. Without it we have only two possible solutions: adding new command line switch eg. "--proxyHasBeenSet" or adding this header every time, no matter if the proxy has been set which is not a good solution.

**Comment by laurentj** [comment]
>PhantomJS have undocumented phantom.proxy() 

If I read the PhantomJS source code (2.0+) there is  a `phantom.setProxy()` method (issue #445), but I don't find the implementation of the proxy() method :-/. So I don't know what it does exactly and how the returned string is formated.

**Comment by wskorodecki** [comment]
https://github.com/ariya/phantomjs/blob/master/src/phantom.cpp
https://github.com/ariya/phantomjs/blob/2.1/src/phantom.cpp
Line 427 - on both versions.

But you're right - the method is missing in 2.0:
https://github.com/ariya/phantomjs/blob/2.0/src/phantom.cpp
Perhaps someone has removed this method by mistake.
