### ISSUE TITLE
versioning compatible with npm slimerjs

### ISSUE THREAD

**Issue by graingert** [laurentj/slimerjs#437]
Currently "x.y.z-abc" does not work under npm anymore. The phantomjs-prebuilt team solved this by tracking the major and minor versions of phantomjs.

However slimerjs uses major.minor.patch where major==0.

@laurentj It would be great to come up with a solution that works for both npm slimerjs and slimerjs.

**Comment by graingert** [comment]
I'm currently thinking: 

```
`${slimer.major}.${slimer.minor}${pad(2, slimer.patch}.${npmSlimer.major}`

`0.908.0` for our next release, then `0.908.1` for any code changes in npm slimerjs.

Then when `0.10` gets released: `0.1000.1`
Then when `1.0.0` gets released: `1.0.1`
Then when `1.2.3` gets released: `1.203.1`

**Comment by laurentj** [comment]
Sorry, I don't understand the issue.  I'm not responsible of the npm package, and the package maintainer put what he wants in package.json, right? What is the relationship between the version in package.json and phantom.version or slimer.version?

**Comment by graingert** [comment]
@laurentj I'm maintaining the npm package right now. The idea is so that I can encode both the installer version and the SlimerJS version

**Comment by laurentj** [comment]
>I'm maintaining the npm package right now.

Thank you for your job :-)

Are you sure "x.y.z-prerelease" doesn't work anymore? [Their documentation](https://docs.npmjs.com/misc/semver) does not reflect this change. 

If i understand well, you ask me advice how to set the version in your package? not to change the semantic version of SlimerJS?

**Comment by graingert** [comment]
@laurentj if people pin to "^0.9.6" then pre-releases `0.9.6-1` or `0.9.6-2` are released, they won't get auto upgraded.

It seems that PhantomJS only uses Major.Minor and so there's no clash.

**Comment by laurentj** [comment]
I'm using [semver](http://semver.org/) for SlimerJS, and I don't want to change this. It's important for the project as the version refers to the state of the API. So for a user, it's important to have the patch part of the version, to know that he can do upgrade without changing his code.

For your version package, I see two solution :

The version refers to your installer version, not to SlimerJS version, and the patch part could refer to the slimerjs version : `1.0.10906` for the installer of Slimerjs 0.9.6. Or you can mix your installer version with the patch part of the Slimerjs version. I think it will be less disturbing for the user, as  `1.2.3` is too different than `1.203.1` (the user may ask himself : what is this SlimerJS 1.203?), whereas `1.2.301` may be ok. (in both case, it still refers to 1.2).

What do you think about it?

Note : for your installer, don't spend time to package standalone edition for SlimerJS 0.10 and higher. Mozilla ceased to build XulRunner, and even has removed XulRunner sources from Mozilla trees. XulRunner is dead. Futurs version of SlimerJS ( >= 0.10) will be available only as lightweight edition, and the user will have to install Firefox.

**Comment by graingert** [comment]
I don't understand the second solution

**Comment by laurentj** [comment]
For your version package, instead of doing

```
const version = `${slimer.major}.${slimer.minor}${pad(2, slimer.patch}.${npmSlimer.major}`;
```

I propose to do 

```
const version = `${slimer.major}.${slimer.minor}.${slimer.patch}${pad(2,npmSlimer.major)}.`;
```
 
The idea is to keep the same minor and major number, identical between the original SlimerJS version and the package version.

**Comment by graingert** [comment]
ah yes
```
const version = `${slimer.major}.${slimer.minor}.${slimer.patch}${pad(2,npmSlimer.major)}`;
```

is cool

**Comment by graingert** [comment]
actually I'm going to stick with 

```javascript
const version = `${slimer.major}.${slimer.minor}${pad(2, slimer.patch}.${npmSlimer.major}`;
```

because this lets people pin to a slimer version and allow npm slimer to auto-upgrade
