### ISSUE TITLE
.tar.bz file missing for 0.10.0-pre-3

### ISSUE THREAD

**Issue by adube** [laurentj/slimerjs#442]
### versions 

- SlimerJS: 0.10.0-pre-3
- Firefox: --
- Operating system: Xubuntu 14.4

### Steps to reproduce the issue

Try visiting: http://download.slimerjs.org/nightlies/0.10.0pre/slimerjs-0.10.0pre-linux-x86_64.tar.bz2

### Actual results:

Error 404!

### Expected results:

There should be a file there.  See:

https://download.slimerjs.org/nightlies/0.10.0pre/

### An other way to reproduce the issue

Requires: npm

1) Create an empty directory

```
mkdir ttt
cd ttt
```

2) Create an `package.json` file with the following content:

```
{
  "devDependencies": {
    "slimerjs-edge": "0.10.0-pre-3"
  }
}
```

3) Type `npm install`

You'll get the error because the above file is missing

**Comment by laurentj** [comment]
There are not anymore standalone edition of Slimerjs, since XulRunner is dead. see issue #381 . 

Where did you get this url : http://download.slimerjs.org/nightlies/0.10.0pre/slimerjs-0.10.0pre-linux-x86_64.tar.bz2 ? If it is from slimerjs.org, we should remove this url.

**Comment by adube** [comment]
@laurentj See "An other way to reproduce the issue" in the description.  You'll see that the npm package, when using "0.10.0-pre-3", produces that url.

So, it's an issue with the npm package ?

**Comment by laurentj** [comment]
Yes, it is an issue with the npm package. However, I'm not the maintainer of this package.

You should propably fill an issue on https://github.com/graingert/slimerjs

ping @graingert

**Comment by graingert** [comment]
I was having this issue with my package, then a merge from upstream phantom fixed it for me

**Comment by adube** [comment]
For the record: it's now working for me too as of today.  Thanks for your support.
