### ISSUE TITLE
page.open() Callback never called for some malformed URLs

### ISSUE THREAD

**Issue by MarkR42** [laurentj/slimerjs#443]
### versions 

- SlimerJS: master, latest at the time of writing.
- Firefox: 45.0
- Operating system: Linux Ubuntu 14.04 x86_64

### Steps to reproduce the issue

var page = require("webpage").create();

page.onLoadFinished = function(status) {
    console.log("onLoadFinished:" + status);
};

var url = 'http://:www.enottone.ru';
// var url = 'http://nonexistent.vectrex.org.uk/';
page.open(url, callback).then(
    function(status) {
        console.log("THEN callback returned:" + status);
        });

// console.log("open returned:" + st0);

function callback(status) {
    console.log("CALLED BACK: status=" + status);
    phantom.exit();
}

### Actual results:

Hangs forever, no callbacks called.

### Expected results:

Calls the callbacks with fail status.

**Comment by MarkR42** [comment]
URL to reproduce the issue is 'http://:www.enottone.ru'
URL which correctly calls the callback with "fail" is 'http://nonexistent.vectrex.org.uk/'

**Comment by laurentj** [comment]
It shows the Firefox error page (with some other issues). Strangely, PhantomJS returns a "success" status for the first url.

**Comment by spinpx** [comment]
There are some other sites which never call calllback function. I tested them with firefox 45.0.
```
answers.com
constantcontact.com
houzz.com
mirror.co.uk
```

**Comment by laurentj** [comment]
@spinpx I don't reproduce, it works perfectly with the sites you indicate.

**Comment by spinpx** [comment]
@laurentj Thanks. Might be my network environment problem( GFW in China).  However, I can visit them successful in browsers and phantomjs.

**Comment by MarkR42** [comment]
That was super-fast, thanks!
