### ISSUE TITLE
Handle onAuthPrompt for proxy auth

### ISSUE THREAD

**Issue by Niek** [laurentj/slimerjs#444]
Right now proxy authentication is only possible with the command line switch ``--proxy-auth``, not within the script. This limits proxy usage quite a bit.

Ideally, when a ``Proxy-Authenticate`` response header is returned, the ``onAuthPrompt()`` would be fired so it's possible to set different credentials based on the URL requested. It would also be nice if ``webpage.settings.userName`` and ``webpage.settings.password`` (or similar) can be used for proxy authentication.

On a related note, the documentation mentions the ``phantom.settings`` object for setting username and password info page-wide, but the ``phantom.settings`` object does not exist - at least in SlimerJS 0.9.6.

**Comment by laurentj** [comment]
>Ideally, when a Proxy-Authenticate response header is returned, the onAuthPrompt() would be fired so it's possible to set different credentials based on the URL requested

Note for contribution: _slimerPromptUsernameAndPassword in nsPrompter.js should be modified for this behavior.

>It would also be nice if webpage.settings.userName and webpage.settings.password (or similar) can be used for proxy authentication.

http auth and proxy auth are two different things, and so login/password may be different (we can have both at the same time). So it should be in different settings, let's say webpage.settings.proxyUserName and webpage.settings.proxyPassword, with user/password given on the command line as default value.


>the documentation mentions the phantom.settings object for setting username and password info page-wide

It's `phantom.defaultPageSettings`. I'll fix the documentation.

**Comment by laurentj** [comment]
>It would also be nice if webpage.settings.userName and webpage.settings.password (or similar) can be used for proxy authentication.

I created a separate issue #445 for this. In phantomJS 2.0, there is `phantom.setProxy(...)`
