### ISSUE TITLE
Strange behaviour of console.error(), console.warn() and system.stderr.write()

### ISSUE THREAD

**Issue by wskorodecki** [laurentj/slimerjs#450]
I think there is still some problems with #189.
Test script:
```
var system = require('system');

console.debug('This is a debug message.');
console.log('This is a log message.');
console.info('This is a info message.');
console.warn('This is a warning message.');
console.error('This is an error message.');

system.stderr.write('This is an error message written via system.stderr.write().' + "\n"); // Invisible.

slimer.exit(0);
```

1. I don't see the last message written via system.stderr.write() method.
2. It looks like warnings and errors are still being written to stdout instead of stderr.

I also launched `test/launch-initial-tests.js` and one error message is also invisible:
```
------ you should see the output of system.stdout
output: 
Hello World # Missing error message after this line.
------ check yourself if following values are ok
```

**Comment by laurentj** [comment]
Like PhantomJS, all console messages are displayed to stdout, not stderr.

In SlimerJS, to see stderr, you should see the --debug flag on the command line. stderr is deactivated without this flag, to not see all internal gecko messages that are not very useful.

**Comment by laurentj** [comment]
use --debug=errors to not see all debug messages, but only stderr
