### ISSUE TITLE
Wrong value in expires key in cookie object

### ISSUE THREAD

**Issue by wskorodecki** [laurentj/slimerjs#457]
### versions 

- SlimerJS: 0.9.6
- Firefox: 38.0.5
- Operating system: Ubuntu 14.04

### Steps to reproduce the issue

Return `phantom.cookies` for some website. Preferably immediately after the authorization.
Example:
```
var page = require('webpage').create();
page.viewportSize = {
    width: 1920,
    height: 1080
};
page.open('https://www.google.com/', function () {
    console.log(JSON.stringify(phantom.cookies));
});
```
### Actual results:
SlimerJS returned:
```
[  
   {  
      "name":"NID",
      "value":"78=drzhQMlkCU47rDRpmB2CwTCq1PNZ6-7i1iV0owmBekrKh3BzwEiAHFOOFTEUulL2n24ICIABlSx3CLII9svtNNWH7eIy1CJPwZ4c7h-vMvNjrfB2ZAwTPfXGSUC0ko-6",
      "domain":".google.pl",
      "path":"/",
      "httponly":true,
      "secure":false,
      "expires":1475318977,
      "expiry":1475318977
   }
]
```
`expires` key have an integer (0 or timestamp) instead of properly formatted expiration date. This is incompatible with PhantomJS.

### Expected results:

`expires` key should have a string value - the expiration date, formatted in ISO format as described here:
https://docs.slimerjs.org/current/api/cookie.html

PhantomJS correctly returned:
```
[  
   {  
      "domain":".google.pl",
      "expires":"pon., 02 maj 2016 10:50:14 GMT",
      "expiry":1462186214,
      "httponly":false,
      "name":"CONSENT",
      "path":"/",
      "secure":false,
      "value":"CG.251e01"
   },
   {  
      "domain":".google.pl",
      "expires":"sob., 01 paź 2016 10:50:14 GMT",
      "expiry":1475319014,
      "httponly":true,
      "name":"NID",
      "path":"/",
      "secure":false,
      "value":"78=H_ZhmFE4ecIi2gvHeoMuypD9pb1C_oPmq0ecBFDYTNYd3TWP-3wU3c3WJA-XzRLZGgiZzmVjhi9WnR7aUiN3ONLo_Zo4SU5VeeFNMgu26lFA5LjKYZMEWspSdOIxCWs9"
   }
]
```
Another issue is that the [inconsistent behavior of the expiry property](https://docs.slimerjs.org/current/api/cookies.html#expires) URL which is on this page:
https://docs.slimerjs.org/current/api/phantom.html
is invalid.

**Comment by laurentj** [comment]
Please provide steps to reproduce the issue: example of code and an url, that shows the issue for example.

>Another issue is that the inconsistent behavior of the expiry property URL is invalid.

Is invalid with which version of PhantomJS?

**Comment by wskorodecki** [comment]
> Please provide steps to reproduce the issue: example of code and an url, that shows the issue for example.

Ok I will add an example here later.

> Is invalid with which version of PhantomJS?

I mean that my browser returns 404 for this URL: https://docs.slimerjs.org/current/api/cookies.html#expires

This URL can be found on this page in the SlimerJS documentation:
https://docs.slimerjs.org/current/api/phantom.html
Sections: `addCookie` and `cookies`.

**Comment by laurentj** [comment]
Thanks for your report. Links in the documentation are fixed now.
