### ISSUE TITLE
PDF rendering crash/hang on Ubuntu when cups not installed, should have better behaviour

### ISSUE THREAD

**Issue by MarkR42** [laurentj/slimerjs#460]
### versions 

- SlimerJS: master
- Firefox: 45.0
- Operating system: Ubuntu 14.04

### Steps to reproduce the issue

Run the rendering tests

### Actual results:

Crash or hang running the PDF rendering test

### Expected results:

If it can't render a PDF, a nice error message (exception raised) or something, would be better than a crash. 

This is noted in the documentation, as fixed in #395 , but the behaviour is not ideal, I spent some time trying to discover why this was crashing.

**Comment by laurentj** [comment]
The crash occurs in Firefox, not in SlimerJS. I don't have the control on Firefox.
