### ISSUE TITLE
Can't pass -P argument from script

### ISSUE THREAD

**Issue by NeonPaul** [laurentj/slimerjs#463]
### versions 
- SlimerJS: 0.9.6
- Firefox: 45.0.2
- Operating system: Ubuntu 14.04

### Steps to reproduce the issue
Run the following in nodejs:
```javascript
require('child_process')
  .spawn('slimerjs', ['-P myProfile'])
  .stdout.on('data', data => process.stdout.write(data))
```
Or from the terminal:
```bash
nodejs -e "require('child_process').spawn('slimerjs', ['-P myProfile']).stdout.on('data', data => process.stdout.write(data))"
```

### Actual results:
Output:
> unknown option -P myProfile

### Expected results:
Open slimer with the "myProfile" profile or show the "select profile" window if that doesn't exist.

N.B. it works if specifying '-P' and 'myProfile' as two separate arguments, but this is counter-intuitive (and doesn't work when running from casperjs as that seems to change the order of the arguments).

**Comment by bmcorser** [comment]
#1559

**Comment by laurentj** [comment]
In fact, these parameters are processed by Firefox/Xulrunner, not by SlimerJS. Can't do anything about it.
