### ISSUE TITLE
Unexpected / weird error message

### ISSUE THREAD

**Issue by matthieu-ravey** [laurentj/slimerjs#470]
### versions 

- SlimerJS: 0.10.0pre-linux-x86_64
- Firefox: The one bundled with SlimerJS
- Operating system: CoreOS / Ubuntu

### Steps to reproduce the issue
The steps to reproduce the issue are complicated.

### Actual results:
One SlimerJS process exit with the following log:
```
/opt/slimerjs/slimerjs: line 180: 17790 Killed                  "$SLIMERJSLAUNCHER" -app "$SLIMERDIR/application.ini" $PROFILE -no-remote "$@" 2> /dev/null
```

And I have no idea what happens.

**Comment by MarkR42** [comment]
Have a look at the kernel logs, it might be that the SlimerJS (firefox)
process used too much memory and was killed by the "OOM killer".

Also, try repeating the test with --debug=no , at least that won't eat
stderr.

Mark

**Comment by laurentj** [comment]
>SlimerJS: 0.10.0pre-linux-x86_64

Please use the stable version of Slimerjs 0.10.

> Firefox: The one bundled with SlimerJS

There is no anymore Firefox bundled with SlimerJS (at least in the [official package](https://slimerjs.org/download.html#lightweight). Or you are using a very old 0.10pre package...
