### ISSUE TITLE
NS_BINDING_ABORTED

### ISSUE THREAD

**Issue by wskorodecki** [laurentj/slimerjs#480]
### versions
- SlimerJS: 1.0.0 (build: 20160510)
- Firefox: 41.0.2
- Operating system: Ubuntu 15.04 (vivid)
### Steps to reproduce the issue

I don't know how to reproduce the issue but the problem is occurring randomly.
### Actual results:

```
JavaScript error: resource://slimerjs/addon-sdk/toolkit/loader.js -> resource://slimerjs/slimer-sdk/net-log.js, line 473: NS_BINDING_ABORTED: Component returned failure code: 0x804b0002 (NS_BINDING_ABORTED) [nsIStreamListener.onStopRequest]
```

**Comment by spyjo** [comment]
I have also almost the same error with current git.
This message appears while the page is closing, just after:
> 2017-05-20T15:09:49.246Z [DEBUG] webpage: close
> JavaScript error: resource://slimerjs/addon-sdk/toolkit/loader.js -> resource://slimerjs/slimer-sdk/net-log.js, line 492: NS_ERROR_ABORT: Component returned failure code: 0x80004004 (NS_ERROR_ABORT) [nsIStreamListener.onStopRequest]

The page is not closed with exit() or so, it just exits because there is nothing more to do.
I'm using CasperJS current git and Firefox 52.1.1 ESR
