### ISSUE TITLE
onNavigationRequested parameter documentation for SlimerJS 0.10.0 potentially out of date

### ISSUE THREAD

**Issue by winghouchan** [laurentj/slimerjs#481]
Here is the current documentation for [`onNavigationRequested`](https://docs.slimerjs.org/0.10/api/webpage.html#onnavigationrequested)

> This callback is called when a navigation event happens in the page (a click on a link or when a form is submitted, for example). It receives these arguments:
> - url: The target URL of this navigation event
> - type: indicate where the event comes from. Theorically, possible values are: ‘Undefined’, ‘LinkClicked’, ‘FormSubmitted’, ‘BackOrForward’, ‘Reload’, ‘FormResubmitted’, ‘Other’
> - willNavigate: true if navigation will happen, false if it is locked (by navigationLocked)
> - main: Theorically, true if this event comes from the main frame, false if it comes from an iframe of some other sub-frame.
> 
> Because of lack of information in some API of Firefox, SlimerJS cannot give you the type and the main value. They are always respectively `'Undefined'` and `true`
> 
> Example:
> 
> ``` javascript
> page.onNavigationRequested = function(url, type, willNavigate, main) {
>     console.log('Navigate to: ' + url);
> }
> ```

We can see that there is a note that the values of passed to `type` and `main` will always be `Undefined` and `true` respectively.

> Because of lack of information in some API of Firefox, SlimerJS cannot give you the type and the main value. They are always respectively `'Undefined'` and `true`

However, in a project I am working on that has SlimerJS as a dependency, I have seen the `main` parameter being passed `false`. My questions regarding this are:
- Is this behaviour new to [SlimerJS 0.10.0](https://github.com/laurentj/slimerjs/releases/tag/0.10.0)? I can't see it in the [release notes](https://docs.slimerjs.org/current/release-notes-0.10.html) for 0.10.0.
- Can the behaviour be trusted since this is a fix for previously incorrect behaviour however it hasn't been documented?
- Is an upcoming version expecting to have the correct value passed to the `type` parameter? If not what exactly is blocking this and how can people contribute to resolve this?

**Comment by laurentj** [comment]
This is an error in the documentation. The "main" parameter can be true or false since early version of SlimerJS, and contain a correct value.
