### ISSUE TITLE
Ubuntu SlimerJS never exits. Whereas Mac OS X does.

### ISSUE THREAD

**Issue by EWhite613** [laurentj/slimerjs#492]
### versions 

- SlimerJS: 0.9.6
- Firefox: 45.0
- Operating system: Ubuntu

### Steps to reproduce the issue
* Clone https://github.com/EWhite613/ember-cli-visual-acceptance/tree/Travis 
* `npm install && bower install`
* Change `testem.js` to use `slimerjs` https://github.com/EWhite613/ember-cli-visual-acceptance/blob/Travis/testem.js#L6
* Run `ember test`
### Actual results:
On Ubuntu SlimerJS never exits. 
Where Mac actually ends with (closing the process):
```
1..1
# tests 1
# pass  1
# skip  0
# fail  0

# ok
```

**Comment by laurentj** [comment]
> Clone https://github.com/EWhite613/ember-cli-visual-acceptance/tree/Travis
> npm install && bower install

Sorry. No. I just can't analyze all this code. Please provide a minimal test case.
