### ISSUE TITLE
Videos not playing in ubuntu server

### ISSUE THREAD

**Issue by sbsomya** [laurentj/slimerjs#493]
Hi 
I have a html with video tag 
Took a screenshot of the same and the video dint came
Was running with xvfb

**Comment by laurentj** [comment]
What is the result when running the same script on computer with the same ubuntu but with a desktop and without xvfb etc?

**Comment by sbsomya** [comment]
Ahh i dont have desktop thing but yes tried on linux mint 17 it works perfectly fine

**Comment by sbsomya** [comment]
Ahh dont have a ubuntu machine but yes have linux mint 17 it works absolutely fine there even with xvfb

**Comment by laurentj** [comment]
So you have an issue with your server configuration, not with SlimerJS IMHO.

**Comment by sbsomya** [comment]
Ohh can you help with the possibilities of incorrect things 
I have firefox installed version 45.0
xvfb latest

**Comment by sbsomya** [comment]
Was issue with firefox only 
http://askubuntu.com/questions/475351/firefox-html5-video-support

just installed sudo apt-get install ubuntu-restricted-extras
