### ISSUE TITLE
slimerjs-0.10.0 not working with Firefox 47.0

### ISSUE THREAD

**Issue by stoyle** [laurentj/slimerjs#495]
### versions 

- SlimerJS: 0.10.0
- Firefox: 47.0
- Operating system: Mac OS X (10.11.5)

### Steps to reproduce the issue
As noted on https://slimerjs.org/download.html slimer works with firefox up to version 46.0. Now version 47.0 has been officially released, and surprisingly it doesn't work. Anyway, the error I get is this:

```Gecko error: it seems /Applications/Firefox.app/Contents/MacOS/firefox is not compatible with SlimerJS. See Gecko version compatibility.
Watching paths: /Users/stoyle/projects/hafslund/link2-app/src, /Users/stoyle/projects/hafslund/link2-app/test```

Cheers,
Alf

**Comment by burningTyger** [comment]
you need to update the `application.ini` file if you feel like crossing the border into the unknown.

**Comment by stoyle** [comment]
Firefox is my default browser, and they've now released out 47.0. I did a restart of the browser, and then slimer doesn't work... So I am guessing everyone using/updating Firefox will have this problem pretty soon.

I updated the application.ini file, and our tests without problems. So from my perspective, you could also bump the official application.ini version, and release a new version. But I guess you need to do some more testing... Let me know if there is anything I can do to help.

Cheers,
Alf

**Comment by puravida** [comment]
I've tested fairly heavily with Firefox 47.0 this week. I've run through 100 very problematic URLs that tend to push the limits. It seems to work as well as prior versions.

**Comment by laurentj** [comment]
I confirm that all unit tests are ok with Fx 47

**Comment by stoyle** [comment]
Perhaps bump the version in https://github.com/laurentj/slimerjs/blob/master/src/application.ini, as well? :)

**Comment by kangax** [comment]
Seeing same issue and bumping version doesn't help (on macOS 10.12.1)
