### ISSUE TITLE
Screenshot takes some time of its own 

### ISSUE THREAD

**Issue by sbsomya** [laurentj/slimerjs#496]
We have a requirement to take screenshots at 40 ms of time difference which means 25 frames per second
The time diff between before and after the functiin comes out to be 300 to 400 ms which looks like 10 times 
Can it be taken as a seperate process and can return at specifn

**Comment by laurentj** [comment]
no, I can't improve this part, since it is a Gecko feature (by using a canvas). So, if an improvement is needed, it is at Mozilla side.
