### ISSUE TITLE
slimer.exit() should be able to set exit status

### ISSUE THREAD

**Issue by jcoglan** [laurentj/slimerjs#50]
Currently (version 0.7) calling `slimer.exit(1)` makes the process exit with status `0`. This makes Slimer unsuitable for use as a testing platform since CI servers cannot tell whether the tests failed without relying on a special output format like TAP or XML.

It should be possible to write test scripts with Slimer and use the exit status to indicate failure.

**Comment by laurentj** [comment]
So now we have a workaround for the exit code, thanks to @abozhilov .

**Comment by nathanboktae** [comment]
Can we close this issue now that #278 has been merged?
