### ISSUE TITLE
Can we use slimerjs with chrome browser instead of firefox

### ISSUE THREAD

**Issue by sbsomya** [laurentj/slimerjs#500]
Hi 
Is it possible i just want to use the open page and callback two methods from slimer can i use chrome for it

**Comment by puravida** [comment]
I suppose it never hurts to ask, but that is quite the tall order! ;)

I would love the option to easily switch between Gecko/Firefox or Blink/Chrome, but I think it's a bit much to ask of the maintainers.

**Comment by laurentj** [comment]
> can i use chrome for it

No, it's not possible. SlimerJS is built on top of Firefox, using its internal API. 

However, there are some tools that allows to do such things in any browser, calling them by using a protocol (SlimerJS and PhantomJS can be called too): try Selenium.
