### ISSUE TITLE
console.log() from page is missing if do window.callPhantom('exit'); at the same function loop

### ISSUE THREAD

**Issue by timdream** [laurentj/slimerjs#507]
### versions

(Simply the ones got downloaded from `npm install slimerjs`)

- SlimerJS: Innophi SlimerJS 0.9.6, Copyright 2012-2015 Laurent Jouanneau & Innophi
- Firefox: Mozilla XULRunner 33.1.1 - 20141113143407
- Operating system: Mac OS X 10.11.5

### Steps to reproduce the issue

Run this script:

```javascript

'use strict';

var page = require('webpage').create();

page.onInitialized = function() {
  page.evaluate(function() {
    setTimeout(function() {
      console.log('console message 1');
    }, 100);

    setTimeout(function() {
      console.log('console message 2');
      window.callPhantom('callback message');
    }, 200);
  });
};

page.onConsoleMessage = function(msg) {
  console.log(msg);
};

page.onCallback = function(message) {
  console.log(message);
  phantom.exit();
};

var url = 'https://github.com/laurentj/slimerjs';

page.open(url, function(status) {
  if (status !== 'success') {
    console.error('Unable to access network: ' + status);
    phantom.exit(1);
  }
});

```

### Actual results:

Outputs

```
console message 1
callback message
```

with `console message 2` missing.

### Expected results:

```
console message 1
console message 2
callback message
```

**Comment by timdream** [comment]
This is a regression. I can confirm SlimerJS release 0.9.1 has no such problem, and the problem happens in 0.9.2. 0.9.1 comes with

    Mozilla XULRunner 25.0 - 20131025151332

0.9.2:

    Mozilla XULRunner 31.0 - 20140716183446

0.9.5 comes with a XULRunner that simply says "Couldn't load XPCOM.".

**Comment by timdream** [comment]
This pattern come from QUnit add-on long removed from their repo, which I am still using:

https://github.com/timdream/jszhuyin/blob/master/test/headless-runner.js

I can workaround this by wrapping a `setTimeout()` on that exit call, but it's would be better if it's fixed upstream.

**Comment by laurentj** [comment]
Sorry, SlimerjS 0.9.x is not supported any more. No time to maintain it. Please try SlimerJS 0.10.

**Comment by laurentj** [comment]
Note that since you execute something asynchronously (setimeout...), probably the callback given to page.open is executed before your settimeout callback, , so Slimerjs exits before it, this is why it is not executed.

**Comment by laurentj** [comment]
it worked with 0.9.1, probably because xulrunner 25.0 was slower than xulrunner 33.

**Comment by timdream** [comment]
I can confirm this does not happen in 0.10.0:

```
$ brew install slimerjs
$ slimerjs --version
  Innophi SlimerJS 0.10.0, Copyright 2012-2016 Laurent Jouanneau & Innophi
$ echo $SLIMERJSLAUNCHER
/Applications/FirefoxForSlimerJS.app/Contents/MacOS/firefox
$ /Applications/FirefoxForSlimerJS.app/Contents/MacOS/firefox --version
Mozilla Firefox 46.0
$ slimerjs oncallback.js
console message 1
console message 2
callback message
```

Looks like we should be resolving #489 in this repo or elsewhere so NPM ecosystem gets access to 0.10.0... thanks for the comment!
