### ISSUE TITLE
Cannot traverse document.getElementsByTagName in sec.sogou.com

### ISSUE THREAD

**Issue by 5up3rc** [laurentj/slimerjs#512]
### versions 

- SlimerJS: 0.10
- Firefox: 47.x
- Operating system: mac os x

### Steps to reproduce the issue
i use 
`var elements = document.getElementsByTagName(tag);
                        for (var i = 0; i < elements.length; i++) {
                            res = "{\"url\":\"" + elements[i][src] + "\",\"method\":\"get\",\"post\":\"\"" + ",\"Referer\":\"" + window.location.href + "\"}";
                            if (urls.indexOf(res) < 0 && elements[i][src].indexOf("javascript:") < 0 && elements[i][src].indexOf("mailto:") < 0) {
                                urls.push(res);
                                console.log(res);
                            }`
But I didn't get what I needed.In Firefox can get to content for tag a

**Comment by MarkR42** [comment]
You will need to write a complete example for a properly formed bug report. You do understand, that the main slimerjs script cannot access the web page's DOM, but that you need to call page.evaluate, right?

And you did wait for the page to load?

**Comment by 5up3rc** [comment]
Thank you. I have found the problem. But there is still a problem that cannot be solved. Can be implemented under the firebug Firefox
