### ISSUE TITLE
how can I sure that the page load the flash content?

### ISSUE THREAD

**Issue by lrbmike** [laurentj/slimerjs#517]
### versions 

- SlimerJS: 0.10.0
- Firefox: 45.0
- Operating system: win7 / ubuntu 14.04
- Flash: 22.0 / 21.0 / 20.0

### Steps to reproduce the issue
I  run SlimerJS with CasperJS version 1.1.3
open and capture 'https://www.adobe.com/swf/software/flash/about/flashAbout_info_small.swf' to test flash can work 

### Actual results:
the open window(Firefox) can see the flash content , but slimerjs capture the blank page (png)

this results can be a bit confusing , so i don't know does the flash work? 
I try to debug the page resource, I see that the swf file is loaded(HTTP 200), no errors.  but when I try the other with flash page site (such as www.douyu.com), it can capture the flash content. why?

I have tried different os or flash version, but the same results. I have been troubled by this problem for several days.

**Comment by KevinGrandon** [comment]
Have you tried embedding the swf inside a page and taking a screenshot of that page?

**Comment by lrbmike** [comment]
@KevinGrandon you mean I have tried a local page that embedding the swf?
I have tried a lot of video site that embedding the swf, and I find that some of them capture the blank content( the flash part ), but inside the pop-up window(firefox) , I can see the video (swf) !

**Comment by laurentj** [comment]
dup of issue #81
