### ISSUE TITLE
Re UTF8 encode the no-ascii word 

### ISSUE THREAD

**Issue by rain2fog** [laurentj/slimerjs#521]
### versions 

- SlimerJS: 0.10.0
- Firefox: 45.3.0
- Operating system: CentOS release 6.8 (Final)

### Steps to reproduce the issue
1. Access any website containing **non-ascii** word or capture **JPG/PNG** files 
2. The **response.body** in **onResourceReceived** will re-encode the **JPG/Unicode word** to UTF8
3. Then I can't identify original file  @_@
4. Open the file with xxd , then each original byte will plus 0xc3/0xc2 before it.

### Actual results:

```
........
page.onResourceReceived = function(response) {
  console.log("response: "+JSON.stringify(response));
};
........

[xyf@redbook ~]$ xxd index_title.html 
00000000: c3a5 c292 c2a8 c3a8 c2af c2a2 202d 20c3  ............ - .
00000010: a6c2 99c2 bac3 a8c2 88c2 aac3 a6c2 95c2  ................
00000020: 99c3 a8c2 82c2 b20a                      ........
[xyf@redbook ~]$ cat index_title.html 
å¨è¯¢ - æºèªæè²
```

### Expected results:
```
[xyf@redbook ~]$ xxd index_ori.html 
00000000: e592 a8e8 afa2 202d 20e6 99ba e888 aae6  ...... - .......
00000010: 9599 e882 b20a                           ......
[xyf@redbook ~]$ cat index_ori.html 
咨询 - 智航教育
```

**Comment by rain2fog** [comment]
The website is http://wap.crgkzsw.com/  (AD) . I need the original string. If it's UTF8 encoding string, I have to decode it by myself (do the bit ops).

```
def process_stack(stack)
  f,s=stack
  ori1=f^192
  raise "There is some error in ori1!" if ori1 >= 128
  ori2=s^128
  raise "There is some error in ori2!" if ori2 >= 64
  (ori1*64)|ori2
end

def decode_double_utf(str)
# thie method will not use in further SlimerJS version. It's a bug in slimerjs. It will encode anything in UTF8 twice. The second encoding action will encode byte by byte.
  string=''
  arr=str.bytes
  ori_str=[]
  stack=[]
  
  arr.each do |i|
    if stack.size == 0 
      trigger = i^192 
      if trigger >= 128
        ori_str << i
      else
        stack << i
      end
    elsif ( i^128 <= 63 ) and ( stack.size == 1 )
        stack << i 
        ori_str << process_stack(stack)
        stack=[]
    end
  end
  ori_str.each do |i|
    string<<i.chr
  end
  string
end
```

**Comment by wskorodecki** [comment]
It looks like this is a bug in Firefox, not in SlimerJS.

The conversion is being made in:
``src/modules/webpageUtils.jsm:getWindowContent()`` line 246

It outputs incorrectly encoded characters even if I add:
``encoder.setCharset("UTF-8");``

**Comment by rain2fog** [comment]
It's the original string I got from the console.log. I tried to capture the output by pipe '|' , then xxd view the hexstring . 0xc3/0xc2 is still exist.

command:
`$ xvfb-run ./slimerjs test.js | xxd | less`

find the place with html tag title

```
.......
0000850: 6c65 3d30 5c22 3e5c 6e20 2020 203c 7469  le=0\">\n    <ti
0000860: 746c 653e c3a5 c292 c2a8 c3a8 c2af c2a2  tle>............
0000870: 202d 20c3 a6c2 99c2 bac3 a8c2 88c2 aac3   - .............
0000880: a6c2 95c2 99c3 a8c2 82c2 b23c 2f74 6974  ...........</tit
0000890: 6c65 3e5c 6e20 2020 203c 6c69 6e6b 2072  le>\n    <link r
......

```

**Comment by wskorodecki** [comment]
For me everything is working fine, I could not reproduce this issue in my environment.
Try version 1.0.0-pre (there are 30 commits to master since release 0.10.0) instead of 0.10.0.
And test the output also without xvfb-run. I remember that it causes several different issues until I patched it manually.

**Comment by rain2fog** [comment]
**_wskorodecki_** , thanks for your response. I think it's a magic about my terminal environment. I tried  the version 1.0.0-pre. The problem is still exist. I also change the locale  to en_US.UTF-8. The problem is still in the world! It's frustrating. OMG , where is magic?

**Comment by wskorodecki** [comment]
```javascript
var page = require('webpage').create();
var fs = require('fs');

var sV = this.slimer.version;
var gV = this.slimer.geckoVersion;

console.log('SlimerJS version: ' + sV.major + '.' + sV.minor + '.' + sV.patch);
console.log('Gecko version: ' + gV.major + '.' + gV.minor + '.' + gV.patch);

page.open('http://wap.crgkzsw.com/', function () {
    //console.log(page.content);
    fs.write('encoding.html', page.content, 'w');

    phantom.exit();
});
```

Check contents of encoding.html file - if it contains properly encoded characters then it means that there is something wrong in your environment - not in SlimerJS nor Firefox.

**Comment by rain2fog** [comment]
**wskorodecki**  thanks for your feedback. When I run your code in the version 1.0.0-pre , the content in encodeing.html is right. So I change some code like this:
```
var page = require('webpage').create();
var fs = require('fs');

var sV = this.slimer.version;
var gV = this.slimer.geckoVersion;

console.log('SlimerJS version: ' + sV.major + '.' + sV.minor + '.' + sV.patch);
console.log('Gecko version: ' + gV.major + '.' + gV.minor + '.' + gV.patch);

page.onResourceReceived = function (res){
  console.log(res.body)
};

page.open('http://wap.crgkzsw.com/', function () {
  //console.log(page.body);
  //fs.write('encoding.html', page.content, 'w');
  phantom.exit();
});
```

**0x03/0x02 come again**. It's very interesting. Can you reproduce it? 
My locale is en_US.UTF-8.  Maybe.  I guess console.info is in bit mode , not the line mode to output the string.

**Comment by rain2fog** [comment]
Fixed by @wskorodecki
