### ISSUE TITLE
Travis CI integration

### ISSUE THREAD

**Issue by godban** [laurentj/slimerjs#532]
Hello. I know you probably don't have to worry about third party integrations, but I can't figure out how to use SlimerJS in Travis CI.

I found out for myself that SlimerJS works much better with visual & functional tests then phantom and want to use it for automated build. I asked same question here:
https://github.com/travis-ci/travis-ci/issues/6566
and here
http://stackoverflow.com/questions/39344521/how-to-use-slimer-js-in-travis-ci
but only earned "Tumbleweed" badge :)

Any ideas?

**Comment by typekpb** [comment]
see my SO answer: http://stackoverflow.com/a/39732874/1581069

**Comment by laurentj** [comment]
Probably the result of `which firefox` does not returns the path of the right version of Firefox, and so SLIMERJSLAUNCHER is not good.

**Comment by godban** [comment]
@typekpb yay 🎉 

Thank you, with small changes for node environment it finally works!

````yaml
language: node_js
node_js:
  - node
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH
addons:
  firefox: "24.0"
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "curl https://slimerjs.org/slimerjs-pubkey.gpg | gpg --import"
  - "wget http://download.slimerjs.org/releases/0.9.6/slimerjs-0.9.6-linux-x86_64.tar.bz2"
  - "wget http://download.slimerjs.org/releases/0.9.6/slimerjs-0.9.6-linux-x86_64.tar.bz2.asc"
  - "gpg --verify-files *.asc"
  - "tar jxfv slimerjs-0.9.6-linux-x86_64.tar.bz2"
  - "mv slimerjs-0.9.6 ./slimerjs"
sudo: required

**Comment by unthinkingly** [comment]
For posterity: 

Slimer is available via npm now so it's a little easier to do this. You no longer need to `wget`, `curl`, `gpg` or `tar`. You do need to update node (if it's not a node project on Travis.) Then you can `npm install -g slimerjs@0.10.3`.

Here's how I do it for a ruby project: https://gist.github.com/unthinkingly/ec917d957b7d729711360bbc6c35abca
