### ISSUE TITLE
Not working in linux Ubuntu command line headless

### ISSUE THREAD

**Issue by csimpi** [laurentj/slimerjs#533]
### versions 

- SlimerJS: lastest stable
- Firefox: lastest stable binary from firefox.com
- Operating system: Ubuntu trusty (vagrant) without X

### Steps to reproduce the issue
I've installed firefox from here:
https://www.mozilla.org/en-US/firefox/all/

Unzipped (tar), and linked(ln -s) firefox binary file to /usr/local/bin/firefox
When environment variable added, i try to start slimerjs -v i don't get error message but i don't get nothing else. It just runs and stops without any reason, or print, or message, or error. Nothing. 
I tried to start with xvfb, i got same reason.
I would like to use slimerjs with casperjs with command line.
I tried to run casperjs --engine=slimerjs i got same reason. When i run with phantomJS everything is fine. (but phantomJS very buggy and there is a lot of memory problems that's the cause what i would like to change slimerjs browser)

UPDATE:
There is a lot of requirements to install firefox. I have to install X and Sound engines. It's a nigtmare. I have a stable test system, then i need to install more then 150MB packages only for firefox. Is it necessary? Please give me a help, how can i use slimerjs really headless with casperjs. 
Which packages required to install to make slimerJS and firefox to work without X?

Please help :)
Peter

### Actual results:
Nothing

### Expected results:
Everything :)

**Comment by laurentj** [comment]
Install the Firefox package available from your distro, it will install all dependencies. Then you can use the binaries from Mozilla.

**Comment by laurentj** [comment]
I also updated [the documentation](http://docs.slimerjs.org/current/installation.html#requirements)
