### ISSUE TITLE
All calls to page.paperSize(...) freeze the SlimerJS script

### ISSUE THREAD

**Issue by pantaluna** [laurentj/slimerjs#536]
### versions

- SlimerJS: 0.10.0
- Firefox: 48.0.2
- Operating system: 
Windows 10 running CYGWIN_NT-10.0 MYGAMINGPC1 2.6.0(0.304/5/3) 2016-08-31 14:32 x86_64 Cygwin

### Steps to reproduce the issue

1. Take any working SlimerJS script that outputs a PDF document file or a JPG document file.
2. Add a call to ObjPage.paperSize({format: 'A4',orientation: 'landscape'}); or a call to ObjPage.paperSize({width:'3507', height:'2481'}); before the line containing ObjPage.render(...)
3. Run the script from either the Cygwin terminal or the Windows COmmand Prompt (both result in the same problem).

### Actual results:
The script hangs on the api call ObjPage.render(...).
It even hangs when you do not supply the function parameters e.g. ObjPage.paperSize();
Using an older version of Firefox did not fix it.

### Expected results:
Return from the API calll and continue with the next line in the code, being a ObjPage.render(...)

**Comment by laurentj** [comment]
>Take any working SlimerJS script that outputs a PDF document file or a JPG document file.

Please give us the script you use.

If you don't call `ObjPage.paperSize()`, does it hang too?

**Comment by pantaluna** [comment]
Hi,
I found the reason why the script hanged. I called the function page.paperSize({...}) but instead I have to set the JS Object page.paperSize = {...}
```
/////page.paperSize({format: 'A4',orientation: 'landscape'});
page.paperSize = {format: 'A4',orientation: 'landscape'};
```

FYI The working script:
https://gist.github.com/pantaluna/f3b38bea0630bbd34be5e41b35d8968f

I assume that using an option is the correct use of the API.

**Comment by laurentj** [comment]
Oh yes, sorry, I forgot that paperSize was a property, not a function :-)
