### ISSUE TITLE
Unknown option -jsconsole when using Firefox 50+

### ISSUE THREAD

**Issue by wskorodecki** [laurentj/slimerjs#537]
### versions 

- SlimerJS: 0.10.1 / master (commit 7294da27d7e3d46f09ae3d8163da908323e0234c)
- Firefox: 50a2
- Operating system: Ubuntu 15.04 (Vivid Vervet)

### Steps to reproduce the issue

Launch SlimerJS with "-jsconsole" or "--jsconsole" parameter. Previously it was opening "Error Console" window. But as of Firefox 50 version it does not work.

### Actual results:

`unknown option -jsconsole` or `unknown option --jsconsole`
Both messages comes from SlimerJS.

### Expected results:

There should be possibility to launch developer tools or at least some kind of error console.

I have no idea where is the problem. I tried to investigate this by modifying files `slConfiguration.jsm` and `commandline.js` but with no success. There is not enough info about changes related to developer tools in https://developer.mozilla.org/en-US/Firefox/Releases/50 changelog.

Launching Firefox directly with `-jsconsole` or `--jsconsole` opens "Browser Console".

**Comment by laurentj** [comment]
I does not open anything because I think the Browser Console is inside the browser package (that is not available when launching a xulrunner app like SlimerJS), instead of the toolkit package. we should verify if the old javascript console is still there, inside the toolkit package, and then we should override the implementation of the -jsconsole (if we can).

**Comment by wskorodecki** [comment]
You're right, the `toolkit/components/console/` directory is missing in Firefox 50. Previously there was `jsconsole-clhandler.js` file responsible for handling `jsconsole` parameter. I'm afraid that, the only thing we can do is to check if SlimerJS is running under top of Firefox 50 with `jsconsole` parameter passed in and if so - display a warning that it will not work in this version and then continue.

**Comment by wskorodecki** [comment]
Note for future - we should follow the following topic:
[Bug 1244163 - DevTools inaccessible to XUL apps using "firefox -app"](https://bugzilla.mozilla.org/show_bug.cgi?id=1244163)
