### ISSUE TITLE
JS DOM evaluation returns html entities in <noscript> tag

### ISSUE THREAD

**Issue by rathalos64** [laurentj/slimerjs#542]
### versions 
- SlimerJS: 0.10.0
- Firefox: Firefox 44
- Operating system: Ubuntu 15.10 

### Steps to reproduce the issue
```javascript
var page = require('webpage').create();

page.onClosing = function(page) {
		var dom = page.evaluate(function() {
				return new XMLSerializer().serializeToString(document);
		});
		console.log(dom);
}

page.onLoadFinished = function(status) {
	timer = window.setTimeout(phantom.exit, 5000);
};

page.open("http://defacement.got-defaced.com/");
```

### Actual results:
All tags inside the noscript tag (at the bottom) are replaced by html entities, e.g 
`<noscript>
<p><img src...
</noscript>` 
is converted to 
`<noscript>
&lt;p&gt;&lt;img src...
</noscript>`

### Expected results:
No HTML entities inside noscript

**Comment by wskorodecki** [comment]
This is a correct behavior. Please open Firefox or Chrome, navigate to `http://defacement.got-defaced.com/` then open browser's console and run `new XMLSerializer().serializeToString(document);`. You will see the same results.

**Comment by rathalos64** [comment]
Ok, you're right. Is there anything I could do about it within Slimer? Or is this issue completely restricted to Firefox?

**Comment by wskorodecki** [comment]
Use `page.content`:

```javascript
page.onLoadFinished = function(status) {
    console.log(page.content);
    phantom.exit();
};
```

**Comment by laurentj** [comment]
I agree with @wskorodecki ;-)

There is no bug here.

**Comment by rathalos64** [comment]
Ok, thank you :+1:
