### ISSUE TITLE
Need to use "Exit /b exitcode" for of "Exit" call

### ISSUE THREAD

**Issue by SamuraiJack** [laurentj/slimerjs#548]
### versions
- SlimerJS: 0.10.1
- OS : Windows 7
### Steps to reproduce the issue

1) Open a "cmd" terminal. 
2) Launch slimerjs.bat with some non-existing js file: "slimerjs.bat yoyo.js"
### Actual results:

3) Note, how the whole cmd window is closed, after the command completes
### Expected results:

4) Should return to a command line prompt

This is because the "EXIT" command is used w/o the /b switch: http://ss64.com/nt/exit.html

After adding /b (used in 2 places) problem is fixed.

Side note: seems there's a forgotten debug output of the "programfiles" variable at the bottom of the script:

```
echo %programfiles%
if exist "%programfiles%\Mozilla Firefox\firefox.exe" (
    SET "SLIMERJSLAUNCHER=%programfiles%\Mozilla Firefox\firefox.exe"
)
if exist "%programfiles(x86)%\Mozilla Firefox\firefox.exe" (
    SET "SLIMERJSLAUNCHER=%programfiles(x86)%\Mozilla Firefox\firefox.exe"
)
echo "SLIMERJSLAUNCHER is set to %SLIMERJSLAUNCHER%"
```

The SLIMERJSLAUNCHER output is also redundant (it is shown in separate place in case it is not set)

**Comment by laurentj** [comment]
Is this /b swith is compatible with all versions of Windows, from Window 7 to Windows 10?

**Comment by SamuraiJack** [comment]
As long as they keep backward compatibility - yes.
