### ISSUE TITLE
Exit code is always 0

### ISSUE THREAD

**Issue by jakelacey2012** [laurentj/slimerjs#549]
I've seen this problem consistently raised an an issue but I cannot seem to find a fix.
### versions
- SlimerJS:               **0.9.6**  
- Firefox:                   **49.0**
- Operating system: **ubuntu 16.04**
### Steps to reproduce the issue

``` javascript
console.log('Hello Slimer!');
phantom.exit(10);  // I've also tried slimer.exit(10) no luck
```

``` bash
(╯°□°）╯︵ ┻━┻ ..../slimerjs$ slimerjs sli.js 
Hello Slimer!
```

``` bash
(╯°□°）╯︵ ┻━┻ .../slimerjs$ echo $?
0
```
### Actual results:

``` bash
(╯°□°）╯︵ ┻━┻ .../slimerjs$ echo $?
0
```
### Expected results:

I'm expecting to receive a exit code of 10

``` bash
(╯°□°）╯︵ ┻━┻ .../slimerjs$ echo $?
10 
```

Thank you in advance :)

**Comment by jakelacey2012** [comment]
Upgrading to slimerjs-0.10.1 exits with 10 :+1: 
Would love a stable npm package, Is this somthing that I can contribute to?

**Comment by wskorodecki** [comment]
Please read #489
