### ISSUE TITLE
How to run slimerjs with SSH

### ISSUE THREAD

**Issue by clipvui2512** [laurentj/slimerjs#560]
### versions 

- SlimerJS:  0.10.1
- Firefox:  3.6
- Operating system:  ubuntu

Hi . I try to run slimerjs with ssh. it look like 
--- ssh 1--> open website --> close after 30s
--- ssh 2--> open website --> close after 30s
--- ssh 3--> open website --> close after 30s

**Comment by laurentj** [comment]
>Firefox: 3.6

3.6? are you sure? It is a very old version, not tested with SlimerJS 0.10.

>I try to run slimerjs with ssh

How? What do you try to do exactly? Have you got an example of a shell script you run?

**Comment by markasoftware** [comment]
You could try using `xvfb-run` to run it without a gui, you can do something like `xvfb-run -a -s "-screen 0 1024x768x24" slimerjs script.js` on the other hand, if you want a gui, you can try to set up SSH's X forwarding, try opening the ssh session with  the `-Y` option or `-X` option enabled.
