### ISSUE TITLE
Cannot find module 'slimerjs'

### ISSUE THREAD

**Issue by lope** [laurentj/slimerjs#563]
Using node v7.2.1 (npm v3.10.10)

**install slimerjs locally**
/tmp/test $ npm i slimerjs@*
test@1.0.0 /tmp/test
└── slimerjs@0.10.2 

**install slimerjs globally also**
/tmp/test $ npm i -g slimerjs@*
/home/bob/.nvm/versions/node/v7.2.1/bin/slimerjs -> /home/bob/.nvm/versions/node/v7.2.1/lib/node_modules/slimerjs/src/slimerjs-node
/home/bob/.nvm/versions/node/v7.2.1/lib
└── slimerjs@0.10.2 

$ which node
/home/bob/.nvm/versions/node/v7.2.1/bin/node

**/tmp/test/test.js contains**
```
console.log(require('phantomjs').path);
console.log(require('slimerjs').path);
```
/tmp/test $ node test.js 
/tmp/test/node_modules/phantomjs/lib/phantom/bin/phantomjs
module.js:472
    throw err;
    ^

**Error: Cannot find module 'slimerjs'**
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/test/test.js:9:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

- Firefox: Mozilla Firefox 50.0.2
- Operating system: Ubuntu 14.04

**Comment by KevinGrandon** [comment]
I believe this is because the package.json does not specify the "main" script. Previously the other project was building a main file on install, but there might be a more simple way of bundling something. I'll submit a PR for this.

**Comment by KevinGrandon** [comment]
@laurentj - To actually fix this we'll need to release a version on npm to npmjs. Any plans on doing that soon? I'm happy to help publish things if it were to help.
