### ISSUE TITLE
#8211; instead of '-' in documentation prevents copypasting

### ISSUE THREAD

**Issue by WonderRat** [laurentj/slimerjs#564]
http://docs.slimerjs.org/current/configuration.html
`<td>&#8211;cookies-file=/path/to/cookies.txt</td>`

**Comment by laurentj** [comment]
When I copy-paste from the web page, I have the `–cookies-file=/path/to/cookies.txt`. So it is good for me. I don't understand how you can have the html. How do you copy-paste?

**Comment by WonderRat** [comment]
Copy "–" symbol before "cookies", press Ctrl-F and try to find it on the page - you don't find "-" between "cookies" and "file". Because it different symbols.

**Comment by WonderRat** [comment]
By copypasting you will get non-working crap.

**Comment by laurentj** [comment]
Sphinx translated ``--`` to ``–``...
