### ISSUE TITLE
How to use navigator.mozTCPSocket ?

### ISSUE THREAD

**Issue by Paxa** [laurentj/slimerjs#568]
I notice that webserver server is slow, the simplest request take at least 30ms

```js
var webserver = require("webserver").create();

webserver.listen('127.0.0.1:9001', (request, response) => {
  response.write("Hello");
  response.close();
});
```

Benchmark with:
```
ab -n 100 -c 5 http://127.0.0.1:9001/
```

I found here that slimerjs has TCP Socket support https://github.com/laurentj/slimerjs/blob/5d6cec74bbc19b3f909f12afd7182149629de6cb/docs/release-notes-0.9.rst#new-api-1

But it doesn't work:
```js
console.log(JSON.stringify(slimer.geckoVersion));
console.log(navigator.mozTCPSocket);

var socket = navigator.mozTCPSocket.open('localhost', 9002);
console.log(socket);
```

It gives error (tested with 0.10.2 and latest from master):
```
{"major":50,"minor":1,"patch":0,"prerelease":"","__exposedProps__":{"major":"r","minor":"r","patch":"r","prerelease":"r"}} 
undefined 

Script Error: navigator.mozTCPSocket is undefined
```

How to use `navigator.mozTCPSocket`?

**Comment by laurentj** [comment]
>I notice that webserver server is slow, the simplest request take at least 30ms

Well, the web server is suitable only to do tests. It is not suitable to serve a public web site.

>How to use navigator.mozTCPSocket

This is was an experimental feature of Mozilla [as said in the Mozilla documentation](https://developer.mozilla.org/en-US/docs/Mozilla/B2G_OS/API/Navigator/mozTCPSocket). Probably something has changed into Firefox so we cannot use it anymore, or a kind of permission is missing into SlimerJS...

**Comment by laurentj** [comment]
I confirm that mozTCPSocket has been removed from Firefox, probably since version 50
