### ISSUE TITLE
Does SlimerJS support IPV6?

### ISSUE THREAD

**Issue by corderogerardo** [laurentj/slimerjs#569]
### versions 

- SlimerJS: 0.10.2
- Firefox: Lastest
- Operating system: Ubuntu Xenial

I am trying to make a CasperJS script to run with IPv6, but when I run the command I have no access to http://whatismyv6.com.

I know it's not the proxy server because I test it with curl -U app:apppass -g --socks5 [5555:5555:5:55::5] http://www.google.com, and it works perfectly.

How Do I know if the IP is the correct one? R. With CasperJS I open the website, http://whatismyv6.com , then wait for minutes to load, and then with FS, I save the source code in a file copyv6.html, I open it with nano copyv6.html and see if there is the IPv6 I pass as Proxy.

An unexpected behavior: If I pass the proxy as follows 
xvfb-run casperjs /home/app/testdoip.js --disk-cache=no --engine=slimerjs -proxy=[5555:5555:5:55::5]:5555 --proxy-auth=app:apppass --proxy-type=socks5 | grep -v GraphicsCriticalError

I got the IPv6 of the Production Server App. I don't know if that is normal.

### Steps to reproduce the issue
xvfb-run casperjs /home/app/testdoip.js --disk-cache=no --engine=slimerjs --proxy=[5555:5555:5:55::5]:5555 --proxy-auth=app:apppass --proxy-type=socks5 | grep -v GraphicsCriticalError

### Actual results:
**The IPV6 of the production server.**

<html><head><title>What is my IPv6 Address?</title></head>
<body bgcolor="#FFFFFF">
<center><b>This page shows your IPv6 and/or IPv4 address</b>
<table width="600" cellspacing="5" cellpadding="0" border="0">
<tbody><tr><td colspan="3" align="center">You are connecting with an <font color="#FF0000">IPv6</font> Address of:</td></tr>
<tr><td colspan="3" bgcolor="D0D0F0" align="center"><font size="+3" face="Arial, Monospace">5555:4300:a:63:b699:baff:feb0:5555</font></td></tr>
<tr><td align="left"><a href="http://ipv4.whatismyv6.com">IPv4 only Test</a></td>
<td align="center"><a href="http://whatismyv6.com">Normal Test</a></td>
<td align="right"><a href="http://ipv6.whatismyv6.com">IPv6 only Test</a></td></tr>
<tr><td colspan="3"><br> <br>If the IPv6 only test shows "The page cannot be displayed" (Internet Explorer), "Server not found" (Firefox), any error or search page the$
"Normal Test" shows which protocol your browser preferrs when you have both IPv4 and IPv6 connectivity.
This page should work even on computers with IPv6 only connectivity.
<br> <br>You can access this page with any of these easy to remember url's:
<br> <br><a href="http://ip4.me">ip4.me</a> (defaults to IPv4 only test)
<br><a href="http://ip6.me">ip6.me</a>
<br><a href="http://whatismyv6.com">whatismyv6.com</a><br><a href="http://whatismyipv6address.com">whatismyipv6address.com</a>
</td></tr></tbody></table>
</center>
</body></html>

### Expected results:
**The IPV6 of the proxy server.**

<html><head><title>What is my IPv6 Address?</title></head>
<body bgcolor="#FFFFFF">
<center><b>This page shows your IPv6 and/or IPv4 address</b>
<table width="600" cellspacing="5" cellpadding="0" border="0">
<tbody><tr><td colspan="3" align="center">You are connecting with an <font color="#FF0000">IPv6</font> Address of:</td></tr>
<tr><td colspan="3" bgcolor="D0D0F0" align="center"><font size="+3" face="Arial, Monospace">5555:5555:5:55:5555:5555:5555:5555</font></td></tr>
<tr><td align="left"><a href="http://ipv4.whatismyv6.com">IPv4 only Test</a></td>
<td align="center"><a href="http://whatismyv6.com">Normal Test</a></td>
<td align="right"><a href="http://ipv6.whatismyv6.com">IPv6 only Test</a></td></tr>
<tr><td colspan="3"><br> <br>If the IPv6 only test shows "The page cannot be displayed" (Internet Explorer), "Server not found" (Firefox), any error or search page the$
"Normal Test" shows which protocol your browser preferrs when you have both IPv4 and IPv6 connectivity.
This page should work even on computers with IPv6 only connectivity.
<br> <br>You can access this page with any of these easy to remember url's:
<br> <br><a href="http://ip4.me">ip4.me</a> (defaults to IPv4 only test)
<br><a href="http://ip6.me">ip6.me</a>
<br><a href="http://whatismyv6.com">whatismyv6.com</a><br><a href="http://whatismyipv6address.com">whatismyipv6address.com</a>
</td></tr></tbody></table>
</center>
</body></html>

**Comment by laurentj** [comment]
As Slimerjs is running on top of Firefox, it supports IPV6.

However, perhaps there is an issue in the parsing of the ip for the --proxy parameter..

**Comment by laurentj** [comment]
Thanks for your report
