### ISSUE TITLE
Trouble with https://slimerjs.org/ : firefox says : "Error Certificat : unsecure connection"

### ISSUE THREAD

**Issue by jefleponot** [laurentj/slimerjs#572]
La connexion n’est pas sécurisée

Les propriétaires de slimerjs.org ont mal configuré leur site web. Pour éviter que vos données ne soient dérobées, Firefox ne s’est pas connecté à ce site web.

Ce site a recours à HTTP Strict Transport Security (HSTS) pour indiquer à Firefox de n’établir qu’une connexion sécurisée. Ainsi il n’est pas possible d’ajouter d’exception pour ce certificat.

En savoir plus…

**Comment by laurentj** [comment]
Tu as dû tombé au moment où j'ai fait un upgrade du systeme..
