### ISSUE TITLE
Provide .tar.bz2 packages

### ISSUE THREAD

**Issue by CMCDragonkai** [laurentj/slimerjs#578]
Just a request to keep .tar.bz2 or .tar.gz instead of only zip packages.

**Comment by laurentj** [comment]
because packages are now 'platform' independant, and zip is available everywhere. And differences between the size of the zip and the size of the tar.gz is not really significant. 

However I could regenerate .tar.bz2, it is much smaller..

**Comment by CMCDragonkai** [comment]
Definitely would prefer to have `.tar.bz2` available. zip isn't always available on all unix platforms.

**Comment by laurentj** [comment]
Next version will be packaged as zip and tar.bz2
