### ISSUE TITLE
Compatibility with Firefox 51

### ISSUE THREAD

**Issue by laurentj** [laurentj/slimerjs#579]
Run unit-tests and fix existing issues about compatibility

**Comment by CMCDragonkai** [comment]
Currently running 0.10.3 pre on Firefox 51, and no problem at the moment.

**Comment by techsethi** [comment]
> /Applications/Firefox.app/Contents/MacOS/firefox -v


Mozilla Firefox 51.0.1

src/slimerjs --debug=true

> Error: Platform version '51.0.1' is not compatible with
> minVersion >= 38.0.0
> maxVersion <= 50.*
> Gecko error: it seems /Applications/Firefox.app/Contents/MacOS/firefox is not compatible with SlimerJS.
> See Gecko version compatibility. If version is correct, launch slimerjs
> with --debug=true to see Firefox error message
>

**Comment by leeDav** [comment]
I'm also receiving the same error.

**Comment by CMCDragonkai** [comment]
Hey take a look at the error message itself, all you need to do is change your application.ini and increment the maxVersion.

**Comment by laurentj** [comment]
Some unit tests fail with Firefox 51 (on http timeout and http authentication support). I will fix that.
