### ISSUE TITLE
Firefox extension does not work while using SlimerJS

### ISSUE THREAD

**Issue by trickysam44** [laurentj/slimerjs#581]
### Versions 

- SlimerJS: 0.10.2
- Firefox: 50.0a2.en-US
- Operating system: linux-x86_64

### Steps to reproduce the issue
Use SlimerJS with the ```-profile``` command-line option, provide a path where an ```extension``` folder resides, and in it an ```.xpi``` extension.
Also, ```extensions.json``` needs to be copied from a working Firefox with only this extension, and placed in the profile path.
In my case I also have a ```prefs.js``` file in the profile path, containing the following:
```
user_pref("app.update.enabled", false);
user_pref("xpinstall.signatures.required", false);
```

### Actual results:
When running the SlimerJS using the following command:
```
export $SLIMERJSLAUNCHER=/home/samvx/automation/firefox/firefox
./slimerjs --debug=yes -profile /tmp/test driver.js http://example.com
```
The extension if not working, and is probably not loaded, from my observations.
While if running the same Firefox binary directly, using the following command:
```
$SLIMERJSLAUNCHER -profile /tmp/test
```
The extension runs and works perfectly.

### Expected results:
The wanted extension in my scenario is AdBlockPlus, which is needed to speed up the loading of pages, after searching the net for a lot of time, I can't figure out how to make the extension run in Firefox while under SlimerJS.

**Comment by laurentj** [comment]
From [the documentation](http://docs.slimerjs.org/current/manual/addons.html)

> An addon made for Firefox may not work with SlimerJS because :
> -  the user interface is not the same, so the addon may not found what it wants. For example, there is no toolbar to add a button, so the extension code may not work when it wants to add a button.
> - the install.rdf manifest of an addon may only refer to Firefox as application target. The addon should at least refers to the mozilla toolkit (see below).

AdBlockPlus is a complex extension and may relies on components/UI stuff that are not activated or does not exists in the SlimerJS window. So there are many chances that it does not work...
