### ISSUE TITLE
Running under Windows

### ISSUE THREAD

**Issue by CarbonMan** [laurentj/slimerjs#582]
### versions 

- SlimerJS: latest
- Firefox: 51.0.1 (32-bit)
- Operating system: Windows server 2003

### Steps to reproduce the issue
Installed slimerjs and Firefox
Set the env. variable SLIMERJSLAUNCHER to point to the firefox.exe
Run slimerjs hello.js

### Actual results:
Error executing firefox at C:\...\slimerjs\src\slimerjs
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

I have tried %SLIMERJSLAUNCHER% at the command line and it launches firefox.
Will slimerjs run on Windows server 2003?

**Comment by laurentj** [comment]
SlimerJS is not yet compatible with Fx 51. see issue #589
