### ISSUE TITLE
CORS requests and responses not showing up when using `onResourceReceived`

### ISSUE THREAD

**Issue by jfkhoury** [laurentj/slimerjs#584]
### versions 

- SlimerJS: 0.10.2
- Firefox: 
- Operating system: Mac OS X 10.11.6

### Steps to reproduce the issue

I have a page that makes CORS requests. I need to investigate the request and response, but they don't show up in the callback for `onResourceReceived`.

I know that --web-security is not supported yet, is there any other way to make them show up?

**Comment by wskorodecki** [comment]
I doubt, but at least you can try to catch errors in `onError` callback. I was able to intercept any errors by modifying the `jsErrorListener` (`webpage.js` file) to report all messages returned by `QueryInterface` method which gave me more control over errors. There will be `CORS` category in `msg.category` variable when a CORS error occurs.

**Comment by jfkhoury** [comment]
@wskorodecki , @laurentj 

Here's an update on the ticket:

I was able to see CORS requests and responses :)

1. After investigating the errors, it turned out the requests were being aborted because I was using `slimer.exit()` prematurely. I have hooked it up to `page.loadFinished()`, but I don't think this waits for async calls, so slimer was exiting too early.

I solved it by calling exit inside a setTimout that gets reset every time `page.onResourceReceived()` gets called again. Make sure to wrap the login in that handler in a try/catch/finally.

2. I filtered the captured content by `/application\/json/`.

Here's the full code:

```javascript
page.captureContent = [ /application\/json/ ];

var timeoutId;
var isDoneReceiving = false;

page.onResourceReceived = function(response) {
    try {
        isDoneReceiving = false;
        timeoutId && clearTimeout(timeoutId);

        if (r.stage === "end") {
            console.log('\nResponse (#' + response.id + ', Status: "' + r.status +'): ' + response.url);
            console.log("\n");
            console.log('Response body:', JSON.stringify(JSON.parse(response.body), undefined, 4));
        }
    } catch (ex) {

    } finally {
        timeoutId = setTimeout(function () {
            if (isDoneReceiving) {
                slimer.exit();
            }
        }, 1500);

        isDoneReceiving = true;
    }
};
```

Thank you for the help @wskorodecki, and for the great library @laurentj.

**Comment by laurentj** [comment]
Ok that's fine. 

Do you really need to use a timer? Checking `r.stage === "end"` should be enough, isn't it?

**Comment by jfkhoury** [comment]
Hey @laurentj, I needed the timeout because when I have asynchronous requests/responses, there's no way to know when the last one has arrived, unless I'm missing some hook or event.
