### ISSUE TITLE
Is it really incompatible with Firefox 51?

### ISSUE THREAD

**Issue by amenadiel** [laurentj/slimerjs#586]
### versions 

- SlimerJS: 0.10.2
- Firefox: 51.0.1
- Operating system: Ubuntu 16.10

### Steps to reproduce the issue

```sh
slimerjs --debug=true
```

### Actual results:
```sh
Error: Platform version '51.0.1' is not compatible with
minVersion >= 38.0.0
maxVersion <= 50.*
Gecko error: it seems /usr/bin/firefox is not compatible with SlimerJS.
```

### Expected results:

No errors

**Comment by Snowfish1994** [comment]
alter application.ini 
change MaxVersion=50.* to MaxVersion=53.*

**Comment by laurentj** [comment]
See #579

**Comment by laurentj** [comment]
There are few issues with Fx51, and it seems it is broken with Fx52beta+

**Comment by Snowfish1994** [comment]
there are some problems when I take screenshot for too-long webpage,like new.baidu.com
the png is not complete,but phantomjs's is perfect
