### ISSUE TITLE
ErrorReference when running long time Script 

### ISSUE THREAD

**Issue by jefleponot** [laurentj/slimerjs#590]
### versions 

- SlimerJS: 0.10.0 / 0.10.3
- Firefox: 45.0.2
- Operating system: Ubuntu 16.04

### Steps to reproduce the issue
casperJs script TDD tests/suites/casper/navigation.js 

### Actual results:
JavaScript strict warning: resource://gre/components/SlowScriptDebug.js, line 17: ReferenceError: reference to undefined property this._activationHandler
JavaScript warning: http://localhost:8092/longScript, line 1: Error: Script terminated by timeout at:
@http://localhost:8092/longScript:1:8

### Expected results:
no warnings :-) no ReferenceError

```js

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

"use strict";

Components.utils.import("resource://gre/modules/XPCOMUtils.jsm");

function SlowScriptDebug() { }

SlowScriptDebug.prototype = {
  classID: Components.ID("{e740ddb4-18b4-4aac-8ae1-9b0f4320769d}"),
  classDescription: "Slow script debug handler",
  contractID: "@mozilla.org/dom/slow-script-debug;1",
  QueryInterface: XPCOMUtils.generateQI([Components.interfaces.nsISlowScriptDebug]),

  get activationHandler()   { return this._activationHandler; },
  set activationHandler(cb) { return this._activationHandler = cb; },

  get remoteActivationHandler()   { return this._remoteActivationHandler; },
  set remoteActivationHandler(cb) { return this._remoteActivationHandler = cb; },
};

this.NSGetFactory = XPCOMUtils.generateNSGetFactory([SlowScriptDebug]);


```
Best regards

**Comment by laurentj** [comment]
This component is provided by Firefox, not SlimerJS. So I can do anything except to submit a bug to bugzilla.mozilla.org.

However, we should see if we can deactivate it.
