### ISSUE TITLE
How to install slimerjs in debian without graphical environment

### ISSUE THREAD

**Issue by xaiborweb** [laurentj/slimerjs#592]
I'm installing slimerjs on a debian vps 8 without graphical environment. Followed by all documentation docs.slimerjs.org/current/installation.html With the following step, I connect via ssh:

1) Install dependencies.
> sudo apt-get install libc6 libstdc++6 libgcc1 libgtk2.0-0 libasound2 libxrender1
> sudo apt-get install xvfb

2) Install firefox.
> apt-get install firefox

As you receive this error E: Package 'firefox' has no installation candidate I found a solution in this path /etc/apt/sources.list add this command
> deb http://packages.linuxmint.com debian import

Save the sources.list file and then
> apt-get update
> apt-get install firefox

Now firefox is installed without problems.

3) Slimerjs download.
> cd ~
export SLIMER_JS="slimerjs-0.10.3"
wget http://download.slimerjs.org/releases/latest-slimerjs-stable/$SLIMER_JS.tar.bz2
sudo tar xvjf $SLIMER_JS.tar.bz2
sudo mv $SLIMER_JS /usr/local/share
sudo ln -sf /usr/local/share/$SLIMER_JS/slimerjs /usr/local/bin
export SLIMERJSLAUNCHER=/usr/bin/firefox

4) create a hello.js file and upload it in the same slimerjs folder.
> "use strict"; console.log('Hello, world!'); slimer.exit();

5) I run slimerjs of all these different ways by the console but with none I print anything the console, when it should print 'Hello, world!'
> slimerjs /usr/local/share/slimerjs-0.10.3/hello.js
xvfb-run /usr/local/share/slimerjs-0.10.3/slimerjs hello.js
xvfb-run /usr/local/share/slimerjs-0.10.3/slimerjs /usr/local/share/slimerjs-0.10.3/hello.js
slimerjs --version

I do not know what was wrong for slimerjs to work on my server, I appreciate any help;)

**Comment by laurentj** [comment]
try with the debug flag to see if there are some internal errors 

```
xvfb-run /usr/local/share/slimerjs-0.10.3/slimerjs --debug=true hello.js
```

**Comment by xaiborweb** [comment]
Thank you very much for answering my friend @laurentj , print this:
> XPCOMGlueLoad error for file /opt/firefox/libxul.so:
libdbus-glib-1.so.2: cannot open shared object file: No such file or directory
Couldn't load XPCOM.

**Comment by laurentj** [comment]
So you have to install the missing package. [According to the debian repository](https://packages.debian.org/search?mode=path&suite=jessie&section=all&arch=any&searchon=contents&keywords=libdbus-glib-1.so.2), you have to install the libdbus-glib-1-2 package.

I updated the doc.
