### ISSUE TITLE
Website is temporarily down? 

### ISSUE THREAD

**Issue by ax4** [laurentj/slimerjs#593]
Hi, I am learning SlimerJS these days! Everything worked fine, but today when I trying to enter [SlimerJS org ](http://slimerjs.org/), I couldn't visit the website. Is it just me? Or someone else have same problem (if so, the website is down)? Thx!

**Comment by spyjo** [comment]
yes it's down, since yesterday I think

**Comment by tomByrer** [comment]
I can ping, but get `ERR_CONNECTION_REFUSED` in browser.

**Comment by laurentj** [comment]
Yes, my apache server crashes often these days. I'm investigating why.
