### ISSUE TITLE
Simulate click slimerjs value sent from terminal

### ISSUE THREAD

**Issue by xaiborweb** [laurentj/slimerjs#594]
### versions
- SlimerJS: 0.10.3
- Firefox: 52
- Operating system: windows

### Steps to reproduce the issue
I'm clicking on a html id element and then I take a photo as follows
> url: http://localhost/slimerjs/myscript.php?u=https://domain/film/moana/watching.html?id=558960

> myscript.php
`<?php 
set_time_limit(0);
$link = explode("?id=",$_GET['u']);
$url = $link[0];
$id = 'ep-'.$link[1];
echo $html_url = shell_exec("slimerjs myscript.js $url $id");`

> myscript.js
var page = require('webpage').create();
var system = require('system');
page.open(system.args[1], function (status) {
  page.evaluate(function(){
    var a = document.getElementById("ep-558960");
    var e = document.createEvent('MouseEvents');
    e.initMouseEvent('click', true, true, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);
    a.dispatchEvent(e);
    waitforload = true;
  });
  page.render("myscript.png");
slimer.exit();
});

But when I want to take the value of the id that happened for the click from the terminal then it no longer works, I hope they can help me to find the problem.
> Changing this:
var a = document.getElementById("ep-558960");
For this:
var a = document.getElementById(system.args[2]);

And I know that I am sending the value correctly because when imrpimir this
> console.log(system.args[2]);
slimer.exit();
Print the value I want to send correctly
ep-558960

**Comment by laurentj** [comment]
Because the function you give to ```page.evaluate``` is evaluated inside the web page. So it has no access to variable of your script. ```system.args[2]``` means nothing inside the web page, as there are no ```system``` object into the web page.

Please ask questions on the mailing list, not on github.
