### ISSUE TITLE
Possibility to get object of just opened new window

### ISSUE THREAD

**Issue by Bakharevich** [laurentj/slimerjs#597]
Hello.

If I open new window by clicking at link with target="_blank", how can I get the object of that page? For example, to evaluate that page to scroll at the bottom of it.

### versions 

- SlimerJS: 0.10.2
- Firefox: 51.0.1
- Operating system: Mac OS X El Capitan (10.11.6)

### Steps to reproduce the issue

```javascript
var url = 'http://test.com/';
var x = 47;
var y = 95;

webpage.open('about:blank')
.then(function(){
  return webpage.open(url);
})
.then(function(){
  // clicking at link <a href="http://test2.com" target="_blank">Test2.com</a> by coordinates
  page.sendEvent('click', coordX, coordY, 1, 0);
  //  ... it opens page in new window ...

  //
  // THE QUESTION IS - how can I have get access to that new window? 
  //
})
.then(function() {
  slimer.exit();
});
```

Thank you a lot!

**Comment by jefleponot** [comment]
@Bakharevich 
Do you know the CasperJS project ?

http://casperjs.org/

**Comment by Bakharevich** [comment]
@jefleponot yeah, I know it, thanks. But in fact, I need "head" of the browser. I mean, I need to see how the process is going (clicking, visiting new pages, e.t.c.). That's why SlimerJS is good for me as it's not truly headless.

**Comment by jefleponot** [comment]
CasperJS drives SlimerJS and PhantomJS

**Comment by laurentj** [comment]
See the callback [webpage.onPageCreated()](https://docs.slimerjs.org/current/api/webpage.html#webpage-onpagecreated)
