### ISSUE TITLE
window.open() does not work anymore in Fx53+

### ISSUE THREAD

**Issue by laurentj** [laurentj/slimerjs#607]
### versions 

- SlimerJS: 0.10.4-pre
- Firefox: 53/54/55 

### Steps to reproduce the issue

window.open() in a web page open a new window, but it does not load the given URL.

slBrowserDOMWindow.openURI() returns win.content, but in Fx53+, it is null. If we pass win.browser.contentWindow, Gecko crashes.

**Comment by evger** [comment]
@laurentj did you find a solution?

**Comment by kensoh** [comment]
Thanks Laurent, got it. And I'm sorry that I miss that issue.

(copying @thim81 , fyi it is a known issue)
