### ISSUE TITLE
File upload seems broken in Firefox 55 nightly

### ISSUE THREAD

**Issue by spyjo** [laurentj/slimerjs#616]
### versions 

- SlimerJS: latest git master
- Firefox: 55.0a1 nightly
- Operating system: Debian Stretch
- CasperJS : latest git master

### Steps to reproduce the issue
Try to fill a form with CasperJS:
this.fillSelectors('div#myid form', {
						'input[name="file_upload"]': file_path
					}, false);

### Actual results:
With latest stable Firefox 53, it's ok, file is selected and uploaded on form submit.

But with Firefox 55 nightly, it throws an error on file selection:

JavaScript error: file:///root/tests/slimerjs/src/components/filePicker.js, line 204: TypeError: me.domWindowUtils.wrapDOMFile is not a function

JavaScript error: file:///root/tests/slimerjs/src/components/filePicker.js, line 279: NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "me.domWindowUtils.wrapDOMFile is not a function" {file: "file:///root/tests/slimerjs/src/components/filePicker.js" line: 204}]'[JavaScript Error: "me.domWindowUtils.wrapDOMFile is not a function" {file: "file:///root/tests/slimerjs/src/components/filePicker.js" line: 204}]' when calling method: [nsIFilePicker::domFileOrDirectoryEnumerator]

Thanks

**Comment by hohums** [comment]
As this been fixed or is there a workaround?
