### ISSUE TITLE
callbacks and feature to download files

### ISSUE THREAD

**Issue by jefleponot** [laurentj/slimerjs#617]
### versions 

- SlimerJS:  0.10.3
- Firefox: 53
- Operating system: Linux

Hi @laurentj and EveryBody

Another enhancement that could be nice : 

https://github.com/ariya/phantomjs/pull/14225

Do you think you could create 3 new callbacks to a WebPage object: onFileDownload, onFileDownloadError and onDownloadFinished.

onFileDownload:

page.onFileDownload = function(url, data) {
  return 'path/where/to/save/file';
};

You can return a string with a file name, directory (in this case filename will be taken from HTTP headers), or an empty string (this will interrupt downloading).
Arguments:

    url - source URL
    data - array with download info: filename, size (file size) and contentType.

onFileDownloadError:

page.onFileDownloadError = function(error) {
}

Arguments:

    error - a string representing an error occured.

onDownloadFinished:

page.onDownloadFinished = function() { }

This is a simple callback to notify the user about finished download.

**Comment by jefleponot** [comment]
Hi @laurentj 

Do you have a documentation link to understand how to code firefox/slimerjs modules (XUL or better doc) in english or in french ? Because I don't understand how it is organized ...

**Comment by laurentj** [comment]
Except onDownloadFinished(), it is already implemented. See #110

For documentation, see [src/IMPLEMENTATION_DOC.md](https://github.com/laurentj/slimerjs/blob/master/src/IMPLEMENTATION_DOC.md).

**Comment by jefleponot** [comment]
Hi @laurentj 
Thanks for all.

I haven't seen your documentation :smiley:

**Comment by jefleponot** [comment]
Hi @laurentj 

I test the onFileDownload callback and it works with "content-disposition: attachment;filename=file.ext"

But not on "content-disposition: inline;filename=file.ext"
