### ISSUE TITLE
set customHeaders breaks on \u0000

### ISSUE THREAD

**Issue by dpanic** [laurentj/slimerjs#618]
### versions 

- SlimerJS: 0.10.13
- Firefox: 52
- Operating system: Linux Ubuntu 16.04

### Steps to reproduce the issue
    page.customHeaders = {
      'Referer': 'http://google.com/asdasda\u0000'
    };

### Actual results:
An exception occurred NS_ERROR_ILLEGAL_VALUE: Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIHttpChannel.setRequestHeader]

	resource://slimerjs/slimer-sdk/webpage.js at line 206 column 21 in _create/getNetLoggerOptions/<._onRequest
	resource://slimerjs/slimer-sdk/net-log.js at line 170 column 9 in onRequestStart
	resource://slimerjs/addon-sdk/sdk/deprecated/observer-service.js at line 39 column 5 in listener
	resource://slimerjs/addon-sdk/sdk/system/events.js at line 59 column 7 in Observer<.observe

### Expected results:
expected to work

**Comment by laurentj** [comment]
>expected to work

No.  HTTP spec [says](https://tools.ietf.org/html/rfc7230#page-22) that a header value must have only "any visible USASCII character" (VCHAR) or any character from x80 to xFF code.

Any way, this is an error returned by one of the network component of Firefox, so I can't do anything.
