### ISSUE TITLE
The slimerjs does not support Firxfox v53

### ISSUE THREAD

**Issue by LuckyLuo** [laurentj/slimerjs#619]
### versions 

- SlimerJS: 
- Firefox: 53
- Operating system: Mac

### Steps to reproduce the issue
./node_modules/slimerjs/src/slimerjs --debug=true

### Actual results:
Error: Platform version '53.0' is not compatible with
minVersion >= 38.0.0
maxVersion <= 52.*
Gecko error: it seems /Applications/Firefox.app/Contents/MacOS/firefox is not compatible with SlimerJS.
See Gecko version compatibility. If version is correct, launch slimerjs
with --debug=true to see Firefox error message

### Expected results:
slimerjs should support new Firefox version 53

**Comment by KevinGrandon** [comment]
Now that Firefox updates every 6 weeks, it would be great to auto-update slimer if possible, or be more permissive with the max version. This can be pretty painful especially since Firefox auto-updates by default.

**Comment by LuckyLuo** [comment]
Hi Kevin

Thanks for letting me know.
Yes, if you can make the maximum number configurable, that'd be better.

Cheers

**Comment by laurentj** [comment]
@KevinGrandon no, i don't want an "auto-update" of the max version. Each new Firefox version brings new internal API breaks, changes in internal API behavior, and so it breaks SlimerJS. So I update the max version only when tests show that it is compatible. (and this is not the case with Firefox 53).

**Comment by laurentj** [comment]
@LuckyLuo you can modifiy the maxversion in application.ini, but you'll have some issues...

**Comment by LuckyLuo** [comment]
Thanks Laurent

Cheers

**Comment by laurentj** [comment]
Issues to be compatible with Fx53-56 have been fixed
