### ISSUE TITLE
Installation on linux aborts due to invalid bz2 file

### ISSUE THREAD

**Issue by marvinhagemeister** [laurentj/slimerjs#621]
Since today our CI aborts due to failing installations of slimerjs, because of a corrupt `bz2` file.

### versions 

- SlimerJS: 0.9.6
- Firefox: any
- Operating system: Linux

### Steps to reproduce the issue

1. `npm install slimerjs`

### Actual results:

```bash
Building master
npm install
Error extracting archive
Slimer installation failed { Error: Command failed: tar jxf /tmp/slimerjs/slimerjs-0.9.6-linux-x86_64.tar.bz2

bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
	Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

### Expected results:

Installation should work.

**Comment by apricot13** [comment]
We are also experiencing this issue.

**Comment by fractos** [comment]
Seeing this from wget output:

--2017-05-09 08:08:51--  (try: 6)  http://download.slimerjs.org/releases/0.9.6/slimerjs-0.9.6-linux-x86_64.tar.bz2
Connecting to download.slimerjs.org (download.slimerjs.org)|176.31.242.138|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 34393165 (33M), 30030925 (29M) remaining [application/x-bzip2]
Saving to: ‘slimerjs-0.9.6-linux-x86_64.tar.bz2.1’

slimerjs-0.9.6-linux-x86_64.t  12%[+++++                                          ]   4.16M  --.-KB/s    in 0s

2017-05-09 08:08:51 (0.00 B/s) - Connection closed at byte 4362240. Retrying.

It doesn't get any further than that.

**Comment by laurentj** [comment]
It seems that some disk failures occur on the server. I'm investigating

**Comment by laurentj** [comment]
It seems ok now, but I plan to migrate the website to anew server.

**Comment by marvinhagemeister** [comment]
@laurentj Awesome, thanks a lot 👍
