### ISSUE TITLE
RFE: speed up performance

### ISSUE THREAD

**Issue by RichardNeill** [laurentj/slimerjs#632]
### versions 

- SlimerJS: 10.3
- Firefox: 53 or 54
- Operating system: Linux (Ubuntu 17.04)

### Steps to reproduce the issue

Use SlimerJS to convert a URL to a PDF. 
Observe that it takes ~ 3 seconds to run.

### Actual results:

Takes about 3 seconds on a (fast) server; 2.5 seconds on a very fast desktop.

### Expected results:

Less than 1 second. For comparison, this is achieved by both headless Chromium and the latest Phantom, which can both run much faster (measured at < 1 second). But Phantom chokes on modern JS, while Chromium does not support PDF in landscape. The issue seems to be that Firefox's startup time is too long.

Is there any way to keep Firefox running as a long-lived process, or alternatively to start it, freeze it, and do some kind of copy-on-write? 

[For most issues, this 3 seconds doesn't matter, but for my application it really does... I'm running the PDF conversion server-side, as part of an Ajax request, and for a good user-experience, I really need this to be nearer 0.2 seconds.]

Btw, this is the invocation that works most reliably under Apache via PHP's 'exec', noting that Apache has a private /tmp (thanks to systemd):

mkdir /tmp/slimerhome; export HOME=/tmp/slimerhome; timeout 30 xvfb -a slimerjs pdf.js "$url" out.pdf A3 landscape

**Comment by laurentj** [comment]
Sorry. I can't do anything as I won't patch Firefox. Deal with Firefox's team ;-)

**Comment by RichardNeill** [comment]
For what it's worth... The new Firefox 56 breaks slimer entirely (it never seems to actually exit). On the other hand, Firefox 57 is very very much faster, and if only slimer would work with it, this would be the answer to all our wishes!

**Comment by laurentj** [comment]
For Firefox 56 : see issue #647 . For Firefox 57, there are some other issues, but I didn't look at them. I'm working on it.
