### ISSUE TITLE
Issue when clicking on link to open new / popup window

### ISSUE THREAD

**Issue by kensoh** [laurentj/slimerjs#636]
### versions 

- SlimerJS: v0.10.3
- Firefox: v54.0.1 (64-bit)
- Operating system: macOS (10.12.6 (16G29))

### Steps to reproduce the issue
Go to a web page (for example http://tebel.org/index_mobile.php)
Click on a link that opens up a new window (for eg Interface automation)

### Actual results:
New window opens up but remains blank

### Expected results:
New window opens up and loads normally

### Additional details:
Hi Laurent and SlimerJS users, I'm raising this on behalf of @thim81 who is experiencing this issue. He is using a tool that I made that wraps around CasperJS. When we tried using PhantomJS or Chrome it works. But for Firefox through SlimerJS somehow we experience this unexpected behavior. I'm not sure if anyone else experiences this effect, I can't find related issues on this here so I'm raising it.

I've pasted below generated CasperJS code which the issue can be replicated. Works for PhantomJS/Chrome but not Firefox. 
```js
casper.start('http://tebel.org/index_mobile.php', function() {
techo('http://tebel.org/index_mobile.php' + ' - ' + this.getTitle() + '\n');});

casper.then(function() {
{this.echo('click Interface automation');
casper.waitFor(function check() {return x('//*[contains(text(),"Interface automation")]');},
function then() {this.click(x('//*[contains(text(),"Interface automation")]'));},
function timeout() {this.echo('ERROR - cannot find Interface automation').exit();});}});
```

**Comment by laurentj** [comment]
Hi. Thanks for your report. But this issue is already known. issue #607

**Comment by kensoh** [comment]
Thanks Laurent, got it. And I'm sorry that I miss that issue.

(copying @thim81 , fyi it is a known issue)
