### ISSUE TITLE
Keypress modifier have no effect in slimerJS, how to write lower case using keypress

### ISSUE THREAD

**Issue by davedmarketing** [laurentj/slimerjs#640]
### versions 

- SlimerJS: 0.10.3
- Firefox: 54
- Operating system: OSX 10.11.6

### Steps to reproduce the issue

Focus on a text input field and do this:

`page.sendEvent('keypress', page.event.key.F, null, null, 0x02000000);`

### Actual results:

It gives an upper case F

### Expected results:

lower case f

**Comment by laurentj** [comment]
You give the shift code key at last argument. So your code says to press the F key + the shift key, which corresponds to the upper case F in most of computer in the world ;-)

So the actual result is the good result.

Be careful : `page.event.key.F` is the F key, not the F letter...
