### ISSUE TITLE
How to run SlimerJS with Firefox 50.09b and XVFB on an Ubuntu 16 VM?

### ISSUE THREAD

**Issue by michaelfriedman** [laurentj/slimerjs#641]
### versions 

- SlimerJS: 0.10.3
- Firefox: 50.09b
- Operating system: Ubuntu 16

Trying to run some Node Horseman scrapers on SlimerJS in a headless environment and cannot get the scrapers to run using XVFB.

### Actual results:
```
{ Error
    at ChildProcess.immediateExit (/home/xxxx/xxx/xxxx/node_modules/node-phantom-simple
/node-phantom-simple.js:153:23)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
  name: 'HeadlessError',
  message: 'Phantom immediately exited with: 126' }
Unhandled rejection Error
    at ChildProcess.immediateExit (/home/xxx/xxxx/xxxx/node_modules/node-phantom-simple
/node-phantom-simple.js:153:23)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Expected results:
Expecting scrapers to launch.

$100 bounty and much respect to anyone who can get me up and actually running.

**Comment by Paxa** [comment]
this error message just mean that process crashed, but no logs, you may get more information if run with:
```sh
DEBUG=horseman node your_script.js
```

---

Does it run on other platforms? or with other versions of firefox?

You can see example of how to run with XVFB in Dockerfile: https://github.com/laurentj/slimerjs/blob/e886cab447469fe9a03101e2b5593857918627cd/Dockerfile#L15

That script will make `firefox` executable run always with XVFB, if you want to make it only for your project then can create wrapper in project folder:

```sh
echo $'#!/usr/bin/env sh\n\
Xvfb :0 -screen 0 1920x1080x24 -ac +extension GLX +render -noreset & \n\
DISPLAY=:0.0 firefox $@ \n\
killall Xvfb' > ./bin/firefox
chmod +x ./bin/firefox
```
Then run your script with:
```
PATH=$PATH:$(pwd)/bin script_that_use_slimerjs
```

**Comment by Paxa** [comment]
I was able to run it with some small changes:

```js
var Horseman = require("node-horseman");

const horseman = new Horseman({ phantomPath: `slimerjs` })

horseman
  .userAgent("Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0")
  .open("https://www.wikipedia.org/")
  .type("input[name='search']", "pizza")
  .screenshot('./path.png')
  ...
  .finally(function() {
    console.log(arguments)
    horseman.close();
  });
```

run as:
```
DEBUG=* node example.js
```

**Comment by Paxa** [comment]
Why not use phantomjs? I think horseman works best with phantomjs

**Comment by laurentj** [comment]
Try with the latest of Firefox (56+), and add use the `--headless` flag instead of xvfb. Does it solve the issue ?
