### ISSUE TITLE
PDF links and bookmarks

### ISSUE THREAD

**Issue by dpanic** [laurentj/slimerjs#649]
### versions 

- SlimerJS: 0.10.13
- Firefox: 52
- Operating system: Ubuntu 16.04

### Steps to reproduce the issue
page.open("file:///tmp/1.html", function(status) {
page.render("/tmp/test.pdf");
});

### Actual results:
1. Links are not clickable
2. There are no bookmarks

### Expected results:
1. Links to be clickable and opened in browser
2. Bookmarks

**Comment by laurentj** [comment]
Hi,

> Links are not clickable

Where ? in the web page or in the PDF ?

>There are no bookmarks

Which bookmark do you talk about? Bokkmarks of what? Where these "bookmarks" are supposed to be?

**Comment by laurentj** [comment]
I just discover that a PDF could contain bookmarks. 

And you probably talk about links into the PDF. 

Sorry, I won't fix these issues. SlimerJS is using the internal PDF "printer" of Firefox to generate the PDF. So I cannot fix them. Probably you would want to fill a bug on bugzilla.mozilla.org.
