### ISSUE TITLE
Gdk-Message: slimerjs: Fatal IO error 11 (Resource temporarily unavailable) on X server :101

### ISSUE THREAD

**Issue by sydude365** [laurentj/slimerjs#652]
SlimerJS:  0.10.3
Firefox: 55.0.3 (desired version) have reproduced the results on all versions from 50.0 upwards (except 56+ which gives me the telemetry errors 100% of the time and the prefs changes dont fix it) 
Operating system: CentOS 7.4.1708 64 bit Kernel: 4.13.4
Casperjs: 1.1.4

Happens around 5% of the time regardless of which js I am running. Script runs partially through, then errors prior to completion (as in there are still steps to be executed when it crashes). 

Gdk-Message: slimerjs: Fatal IO error 11 (Resource temporarily unavailable) on X server :101.
Gecko error: it seems /usr/bin/firefox is not compatible with SlimerJS.

**Comment by laurentj** [comment]
Did you try to run only Firefox on this system?

**Comment by sydude365** [comment]
I'll try it and come back.

**Comment by sydude365** [comment]
After a bunch of screwing around, I simply stopped using xvfb and used the --headless option instead on FF 55 and it works. I don't think this was a slimer issue.

**Comment by ClannadBred** [comment]
I just meet the same issue,any update here? I must use xvfb display in my case .
