### ISSUE TITLE
Webscraping With Support of Visual Studio 

### ISSUE THREAD

**Issue by jt4000** [laurentj/slimerjs#653]
If you use Visual Studio 2015 and you have installed Slimer JS from Nuget.

How do I activate a javascript code in backend by using C# code when I want to do a web scraping a webpage?

Thank you!

**Comment by laurentj** [comment]
It seems the Nuget package of SlimersJS is outdated. Install SlimerJS directly from a zip package from here https://slimerjs.org/download.html.

Sorry, I can't answer to your question. I don't know Visual Studio.
