### ISSUE TITLE
How to execute file (cmd/bash) using slimmerJS

### ISSUE THREAD

**Issue by plonknimbuzz** [laurentj/slimerjs#654]
### versions 

- SlimerJS:  0.10.3
- Firefox: 52.0
- Operating system: windows 7 32bit and Ubuntu 14

### Steps to reproduce the issue
exec("notepad");

### Actual results:
```
Script Error: exec is not defined
       Stack:
         -> file:///D:/eko/slimerjs-0.10.3/test4.js: 1
         -> file:///D:/eko/slimerjs-0.10.3/test4.js: 1
```
### Expected results:
open notepad

if i googling it, i only find How to execute/run Slimmer using cmd/bash. But i didnt find any article to execute bash/cmd from slimmerJS.

my target: i want execute idm to save my link

**Comment by laurentj** [comment]
duplicate #215
