### ISSUE TITLE
Bad default styles for controls in headless firefox mode (firefox 56)

### ISSUE THREAD

**Issue by evger** [laurentj/slimerjs#655]
### versions 

- SlimerJS: slimerjs-1.0.0-alpha.2-pre (build from current master)
- Firefox: Mozilla Firefox 56.0 (headless mode cmd `MOZ_HEADLESS=1 SLIMERJSLAUNCHER=./firefox56/firefox ./slimerjs-1.0.0-alpha.2-pre/slimerjs"`)
- Operating system: Ubuntu 16.04.3 LTS

1. get 
`https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/submit` or
`https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox` or
`https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number` or

2. render
https://yadi.sk/i/-JGCDef63PikxU
https://yadi.sk/i/B_tGzE9s3PikxY
https://yadi.sk/i/HYAZLb4A3Pim2Q

Expected default styles for controls (white background, border, black font)

Actual result is a transparent checkbox without borders and black inputs with black font

**Comment by Bantam** [comment]
56.0.2 seems to work using Xvfb but not when using MOZ_HEADLESS=1, get same results as above

Using Xvfb:
htps://www.dropbox.com/s/2hf0chwi6zogi0p/c8dab7ac1f8482317f599584752cfab93b5477ac.png?dl=0

**Comment by laurentj** [comment]
Sorry, this is an issue with Firefox, not SlimerJS.
