### ISSUE TITLE
slimerjs 1.0.0-beta.1 - returning exit code 0 when script not found

### ISSUE THREAD

**Issue by cunneen** [laurentj/slimerjs#657]
### versions 

- SlimerJS: 1.0.0-beta.1
- Firefox: 57.0 64-bit mac OS
- Operating system: mac OS High Sierra 10.13.1

### Steps to reproduce the issue

Give slimerjs a non-existent script to run, and it will output an error but the exit status will be zero.

(with bash)
```
slimerjs foobar.js
```

### Actual results:

```
Error: script not found
0
```

### Expected results:

```
Error: script not found
```

(no exit status should be printed in the above example , since the slimerjs command failed and the exit-status should be non-zero)

**Comment by SamuraiJack** [comment]
From where did you download the beta-1 version? I could only find alpha2 from https://download.slimerjs.org/nightlies/

**Comment by laurentj** [comment]
@SamuraiJack  https://download.slimerjs.org/releases/1.0.0-beta.1/

**Comment by SamuraiJack** [comment]
Thanks!
