### ISSUE TITLE
when will slimer work with headless firefox 55?

### ISSUE THREAD

**Issue by andynuss** [laurentj/slimerjs#659]
Headless firefox 55 came out recently.  Slimer officially supports up to FF 52.0.  Using slimer in headless mode still requires xvfb.  However, I tried installing slimer with xvfb on a large aws ec2 centos 7 instance, and running two different slimer instances at the same time on the same such machine fails with error codes.  There is another unresolved issue on this in the database that you can't run muliple slimer instances that are doing openPage at the same time on the same ec2 machine.

**Comment by laurentj** [comment]
Try the latest beta https://download.slimerjs.org/releases/1.0.0-beta.1/
It is compatible with Firefox 52 to 57.
