### ISSUE TITLE
SlimerJS not compatible with Firefox 57 (Quantum)

### ISSUE THREAD

**Issue by ptandler** [laurentj/slimerjs#665]
### versions 

- SlimerJS: 0.10.3
- Firefox: 57.0
- Operating system: Win7

### Steps to reproduce the issue

just run slimerjs :-)

### Actual results:

There is an error message that slimerjs is not s´compatible with firefox 57.

### Expected results:

Well, the documentation (https://slimerjs.org/download.html) talks about a _preferred_ (nor _required_) version from 38.0 to 52.0. Is this a mistake in the documentation?

Any way to use the current firefox or do I need to install a 52 for now?

**Comment by laurentj** [comment]
Already fix #651 
1.0-beta.1 is working https://download.slimerjs.org/releases/1.0.0-beta.1/

**Comment by ptandler** [comment]
Thanks for the quick reply!
Sorry, I didn't check closed issues
