### ISSUE TITLE
Cannot render transparent background

### ISSUE THREAD

**Issue by Bilge** [laurentj/slimerjs#666]
### versions 

- SlimerJS: 1.0.0-beta1
- Firefox: 57.0.2
- Operating system: Win 7 x64

### Steps to reproduce the issue
Render page with `html, body { background: transparent; }` (just to make sure). Actual background still renders white.

### Actual results:
Slimer renders a solid white background.

### Expected results:
Given that Phantom renders transparent backgrounds I had high hopes Slimer would do the same. (I cannot use Phantom because its rendering engine is old and missing many newer features, doesn't support local files and doesn't support web fonts).

Slimer has no problem rendering the page exactly the same way Firefox displays it, but I specifically looked into automated rendering for the sole purpose of producing a transparent PNG, which PhantomJS can do. Since Slimer seems to want to provide API parity with Phantom I expect this feature should be included, too.

**Comment by laurentj** [comment]
It's a known issue: #154
