### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by Bilge** [laurentj/slimerjs#667]
### versions 

- SlimerJS: 1.0.0-beta1
- Firefox: 57.0.2
- Operating system: Win 7 x64

Even though I cannot use Slimer for what [I had originally planned](https://github.com/laurentj/slimerjs/issues/666), I am very pleased it works on the latest Firefox on Windows. It will save a lot of time that would otherwise be spent stitching together bits of large web pages.

However, I almost didn't bother with Slimer because, [according to the official website](https://slimerjs.org/download.html), it seemed to only supported old versions of Firefox. That is, until I stumbled upon [this issue](https://github.com/laurentj/slimerjs/issues/665) (which I couldn't even find with Google). I'd like to suggest making it clear that the latest version of Firefox is supported and either clearly link to the beta version or speed up the 1.0.0 release so people don't give up on it prematurely!

**Comment by laurentj** [comment]
You're right, I should mention the beta on the web site :-)

Thank you!

**Comment by laurentj** [comment]
I added informations about the betas on the web sites. I hope it will help until I find time to finish 1.0 :-)
