### ISSUE TITLE
can I block particular domains using slimerjs

### ISSUE THREAD

**Issue by developernew123** [laurentj/slimerjs#670]
can I block particular domains using slimerjs so that the browser can't load them when testing

**Comment by MarkR42** [comment]
Yes, very easily.

Just write a onResourceRequested handler function on your webpage object,
set it up before you start,

In your handler function you can check requestData.url, and if you want to
block the domain, call networkRequest.abort(), and the resource won't be
loaded.

Mark

**Comment by developernew123** [comment]
ok

**Comment by developernew123** [comment]
can you give me an example

**Comment by laurentj** [comment]
Something like that:

```
page.onResourceRequested = function(requestData, networkRequest) {
    if (requestData.url.startsWith("http://mydomain")) {
      networkRequest.abort();
      return;
    }
};
```
