### ISSUE TITLE
[website] search script blocked by CSP policy

### ISSUE THREAD

**Issue by pygy** [laurentj/slimerjs#671]
Hi! @laurentj!

### Steps to reproduce the issue

Go to https://docs.slimerjs.org/current/search.html

### Actual results:

No way to use the search functionality.

A red banner says:

> Please activate JavaScript to enable the search functionality. 

There's a wall of CSP errors in the console log (some of which are script-related).

This was tested in Chrome and Firefox

**Comment by laurentj** [comment]
Thank you for the report. It is fixed now.
