### ISSUE TITLE
discover.com web scraping fails

### ISSUE THREAD

**Issue by tsdg112** [laurentj/slimerjs#674]
### versions 

- SlimerJS: 1.0.0-beta.1
- Firefox: 57.0.4 (64-bit)
- Operating system: Windows 7  

### Steps to reproduce the issue
Run the script:
var page = require("webpage").create();
page.open("https://portal.discover.com/customersvcs/universalLogin/ac_main?Aff=Bank");

In the Firefox window, enter some random username and password and click Log In.

### Actual results:
Website shows message: Outdated browsers can expose your computer to security risks.

Console shows:
console.warn: LoginRecipes: getRecipes: falling back to a synchronous message for: https://portal.discover.com

### Expected results:

Website shows: The information you provided does not match our records. Please re-enter your login information below.

**Comment by laurentj** [comment]
Sorry, I can't do anything for web site that do stupid UA sniffing...

**Comment by laurentj** [comment]
Note that you can modify the User Agent string with [webpage.settings.userAgent](https://docs.slimerjs.org/current/api/webpage.html#settings) or with the --user-agent command line option.
