### ISSUE TITLE
is there a way to disallow the persistence of cookies between runs?

### ISSUE THREAD

**Issue by andynuss** [laurentj/slimerjs#678]
I am using firefox headless with your beta version of slimerjs to exercise normal webpages that have ads.  However, I was wondering if there is a way to setup slimerjs to not allow the adpage domains to persist cookies between invocations of slimerjs.  In other words, making all persistent cookies effectively session cookies.

**Comment by laurentj** [comment]
Cookies are not persistent since each time Slimerjs is started, it runs with a new profile. So your problem is elsewhere.
