### ISSUE TITLE
Website detects browser is Netscape

### ISSUE THREAD

**Issue by tsibiskigsn** [laurentj/slimerjs#679]
### versions 
- SlimerJS: 1.0.0-beta.1
- Firefox: 58.0.1
- Operating system: MacOs Sierra 10.12.6

### Steps to reproduce the issue
Launch CasperJS with --engine=slimerjs argument. Navigate to a webpage that checks user agent string, such as https://www.worldwinner.com/cgi/tournament/rookie-entryproc.pl?game_id=120&live (requires free account).

### Actual results:
Page detects that the browser is Netscape, and says "Sorry, this game can't be played in Netscape."

### Expected results:
I know that Netscape Navigator was a precursor to Firefox, but the browser should detect that this is the newest version of Firefox. When manually navigating to the page using Firefox, the page detects the proper user agent string.

**Comment by laurentj** [comment]
Well, user agent sniffing on this site is broken. Not my fault. You can force your own user agent string with the settings API. see documentation.
