### ISSUE TITLE
Beta 1 incompatible with FF58

### ISSUE THREAD

**Issue by Bilge** [laurentj/slimerjs#680]
### versions 

- SlimerJS: 1.0.0-beta1
- Firefox: 58.0.2
- Operating system: Win 7

```
Script Error: Component returned failure code: 0x80570018 (NS_ERROR_XPC_BAD_IID) [nsIJSCID.getService]
       Stack:
         -> resource://slimerjs/slCookiesManager.jsm: 15
         -> resource://slimerjs/slimer-sdk/phantom.jsm: 11
```

**Comment by shorewall** [comment]
I'm running Linux but got a similar problem after Quantum updated to 58.0.1
Downloading the latest master zip from git and pakaging it myself fixed the bug.
This works for me also on 58.0.2

**Comment by xaiborweb** [comment]
@shorewall please could you share the complete sequence of commands that you used so that you will work slimerjs 1.0.0-beta1 with firefo 58.02 on ubunutu 16.04 thanks.

**Comment by Bilge** [comment]
https://github.com/laurentj/slimerjs/blob/master/BUILD.md

**Comment by laurentj** [comment]
It was fixed weeks ago into the master branch. I just have to release a new version.
