### ISSUE TITLE
ERROR SLIMERJSLAUNCHER WINDOWS

### ISSUE THREAD

**Issue by xaiborweb** [laurentj/slimerjs#682]
### versions 
- SlimerJS: 1.0.0-beta.1
- Firefox: 58.0.2
- Operating system: windows 10 64 bits

### Steps to reproduce the issue
Download slimerjs version 1.0.0-beta.1 and inside the folder create 2 files with the following content.
html.js
```
var page = require('webpage').create();
page.open('http://www.imdb.com/', function (status) {
	console.log(page.content);
	slimer.exit();
});
```
html.php
```
<?php 
set_time_limit(0);
echo $html_url = shell_exec('slimerjs.bat html.js');
```
set the environment variable path with the following
`SET SLIMERJSLAUNCHER=c:\Program Files\Mozilla Firefox\firefox.exe`
As you can see in this image:
https://i.gyazo.com/0abbb9d1c366fecaf4b84fe9440c8361.png

### Actual results:
and when I run it through the next url
`http://localhost/bot/slimerjs1/html.php`
gives me the following error:
`C:\Program Files (x86) "SLIMERJSLAUNCHER is set to " SLIMERJSLAUNCHER environment variable is missing or the path is invalid. Set it with the path to Firefox. "The current value of SLIMERJSLAUNCHER is: " SET "SLIMERJSLAUNCHER=%programfiles%\Mozilla Firefox\firefox.exe" Presione una tecla para continuar . . .`
show image : https://i.gyazo.com/98122c438d2830e69fb9ddfc93c453b9.png

### Expected results:
if I install it in linux ubuntu 16.04 with the same version of firefox 58.02 and I add the --headless as indicated by the documentation as follows then it throws a blank screen and never prints the html after running javascript and jquery which is what I am needing.

**Comment by laurentj** [comment]
Well, you created a variable named `SET SLIMERJSLAUNCHER` instead of `SLIMERJSLAUNCHER`. It should appear in the window "Variables de entorno".

Bad environment configuration, sorry.

**Comment by arsen99** [comment]
Hello
Sorry for opening this, but I have exact the same problem.

### Steps to reproduce the issue
I want to run slimerJS script using browser. 
I created file skrypt.js:

`console.log("Hello Slimer!");
slimer.exit();`

I created file index.php :

`execute_script('start cmd.exe @cmd /k "C:\Users\Pierwszy\Desktop\slimerjs\slimerjs.bat C:\Users\Pierwszy\Desktop\slimerjs\skrypt.js "');

function execute_script($cmd) { 
echo $aa = substr(php_uname(), 0, 7);
    if (substr(php_uname(), 0, 7) == "Windows"){ 
        pclose(popen("start /B ". $cmd, "r"));  
    }  else { 
        exec($cmd . " > /dev/null &");   
    } 
}`

And unfortunately I get :
"SLIMERJSLAUNCHER is set to " SLIMERJSLAUNCHER environment variable is missing or the path is invalid. Set it with the path to Firefox. "The current value of SLIMERJSLAUNCHER is: " SET "SLIMERJSLAUNCHER=%programfiles%\Mozilla Firefox\firefox.exe" Press any key to continue . . . 

![screenshot_5](https://user-images.githubusercontent.com/25620919/41715976-477f253c-7555-11e8-83e1-8fc50aceed62.jpg)

![screenshot_6](https://user-images.githubusercontent.com/25620919/41715991-57d515c2-7555-11e8-9375-5d01abbe97cc.jpg)

I added environmental variable, but still doesn't work and the error is the same.
Is there a way to set it constant, as FF installation is in one place all the time.
