### ISSUE TITLE
SlimerJS beta not compatible with latest Firefox 59.0

### ISSUE THREAD

**Issue by shorewall** [laurentj/slimerjs#684]
### versions 

- SlimerJS: latest 1.0.0 Beta version downloaded from git.
- Firefox: 59.0
- Operating system: Linux Mageia 5.1 x64

### Steps to reproduce the issue
Just start SlimerJS using Firefox 59.0 as engine.
### Actual results:
SlimerJS claims that the Firefox version used is not compatible with SlimerJS

### Expected results
get SlimerJS running

**Comment by justinklemm** [comment]
PR here: https://github.com/laurentj/slimerjs/pull/685

Just waiting for it to be reviewed and merged.

**Comment by shorewall** [comment]
Downloaded fron git and repackaged, it works.
Thank you!

**Comment by justinklemm** [comment]
👍 I'd recommend closing this issue.
