### ISSUE TITLE
Accessing POST data in onResourceRequested callback

### ISSUE THREAD

**Issue by Niek** [laurentj/slimerjs#69]
PhantomJS supports accessing the postData parameter in a onResourceRequested callback, see https://github.com/ariya/phantomjs/pull/11181. Can the same feature be implemented in SlimerJS?

**Comment by amanda94** [comment]
I found the postData is avaliable when http method is PUT and POST.But for PATCH http method, the postData is still needed.Could slimerjs support this ?

**Comment by laurentj** [comment]
@amanda94 open a new issue please
