### ISSUE TITLE
Error: cannot open display: debian 9

### ISSUE THREAD

**Issue by sonickseven** [laurentj/slimerjs#691]
### versions 

- SlimerJS: Innophi SlimerJS 1.0.0, Copyright 2012-2018 Laurent Jouanneau & Innophi
- Firefox: Mozilla Firefox 59.0.2
- Operating system:No LSB modules are available.
    Distributor ID:	Debian
    Description:	Debian GNU/Linux 9.3 (stretch)
    Release:	9.3
    Codename:	stretch

### Steps to reproduce the issue

the first time that i install slimerjs in my PC desktop(ubuntu 16.04) i used this command: slimerjs -v and the result was that SLIMERJSLAUNCHER enviroment variable was bad. So i change the SLIMERJSLAUNCHER to SLIMERJSLAUNCHER=/opt/firefox/firefox and all work fine +1 but later i installed slimerjs in my server that is in digitalocean and when i run the command slimerjs -v the bash showed the same error that was when i installed it in my desktop PC, so me too change the enviroment variable SLIMERJSLAUNCHER=/usr/bin/firefox and later show it: Innophi SlimerJS 1.0.0, Copyright 2012-2018 Laurent Jouanneau & Innophi. So i thought that all was ok

But when i run this command:

slimerjs --ignore-ssl-errors=true --debug=true oo03iy5mmxly1 show the next error:
**Unable to init server: Broadway display type not supported: 
Error: cannot open display: 
Gecko error: it seems /usr/bin/firefox is not compatible with SlimerJS.
See Gecko version compatibility. If version is correct, launch slimerjs
with --debug=true to see Firefox error message**

I use the same versión of slimerjs and firefox in both machines. I think that problem is that in my desktop PC has interface graphic and the server doesn't use it :-1: 

Somebody know how install firefox without it use display or graphic interface. Because all rest of code it ok
![aesgfserges](https://user-images.githubusercontent.com/3733406/39434411-1f353b54-4c5e-11e8-883c-ddb605bfa4cb.jpg)

**Comment by laurentj** [comment]
Hi.

The response is in the documentation ;-) https://docs.slimerjs.org/current/installation.html#having-a-headless-slimerjs
