### ISSUE TITLE
SSL issue 

### ISSUE THREAD

**Issue by freezepro** [laurentj/slimerjs#693]
### versions 

- SlimerJS: 1.0.0
- Firefox: 59.0
- Operating system: MaCOS Sierra 10.12.6

### Steps to reproduce the issue

Running following script ( from your documentation) 

var page = require('webpage').create();
var startTime;
page.onLoadStarted = function () {
    startTime = new Date()
};
page.onLoadFinished = function (status) {
    if (status == "success") {
        var endTime = new Date()
        console.log('The page is loaded in '+ ((endTime - startTime)/1000)+ " seconds" );
    }
    else
        console.log("The loading has failed");
};
page.open("https://google.com");  //or any other https one

### Actual results:
Secure Connection Failed

google.com uses an invalid security certificate.

The certificate is not trusted because the issuer certificate is unknown.

### Expected results:

show success as result. 
Any other example script also doesn't work. 

I tried options from #304 and #335 , but it doesnt work still,

**Comment by laurentj** [comment]
Hi,

>google.com uses an invalid security certificate.

Well, it seems that your are behind a proxy server that hijacks your https connection. It could be a proxy of your local network (Probably you should setup some proxies parameters into SlimerJS?), or it could be your antivirus (ant this is very bad). Disable its network features

Anyway, this is not a SlimerJS or a Firefox issue.
