### ISSUE TITLE
Error webserver with webpage

### ISSUE THREAD

**Issue by kogeva** [laurentj/slimerjs#695]
### versions 

- SlimerJS: 1.0.0
- Firefox: 60.0 (64-bit)
- Operating system: ubuntu 18.04

### Steps to reproduce the issue
run example script from examples/screenshot_server.js
result output:
`Script Error: c is undefined
       Stack:
         -> resource://slimerjs/slQTKeyCodeToDOMCode.jsm: 36
         -> resource://slimerjs/slQTKeyCodeToDOMCode.jsm: 36
         -> resource://slimerjs/slimer-sdk/webpage.js: 15
`

**Comment by laurentj** [comment]
Duplicate issue of #694
