### ISSUE TITLE
Appropriate version of firefox for slimerjs on a raspberry pi?

### ISSUE THREAD

**Issue by Blakeinstein** [laurentj/slimerjs#721]
### versions 

- SlimerJS: Latest
- Firefox: Not Installed
- Operating system: Ubuntu Server Arm64 (Raspberry Pi 3b+)

I cant seem to find the appropriate version for firefox, to run on raspberry pi.
Their [ftp](https://ftp.mozilla.org/pub/firefox/releases/59.0.3/) doesn't list an Arm64 build and
`sudo apt-get install firefox=59.0.3` returns `Version '59.0.3' for 'firefox' was not found`

**Comment by laurentj** [comment]
Sorry, I don't know how to retrieve a version of Firefox for Arm64

**Comment by Blakeinstein** [comment]
Thank you.
