### ISSUE TITLE
possible issue when finishing process

### ISSUE THREAD

**Issue by javismiles** [laurentj/slimerjs#76]
When i run slimer from linux shell i often see this when process finishes

/usr/bin/xvfb-run: line 171: kill: (17131) - No such process

could this mean that something is going wrong with the Exit() of the slimer , and that resources are not being released correctly?

just wondering

**Comment by lokeshhctm** [comment]
Can you tel what was the server issue. I am facing the same issue

**Comment by Tomii9** [comment]
I too face this problem, Can you please tell me what the issue was please?
