### ISSUE TITLE
running SlimerJS from PHP script

### ISSUE THREAD

**Issue by javismiles** [laurentj/slimerjs#78]
Hi,
Anybody has ever run slimerJS from a PHP script through Apache user ?
We have been trying, me and a few colleages and nobody can manage,
we can run perfectly SlimerJS from commandline and even a colleage runs it using PHP executable but also from commandline in linux,

but nobody seems to be able to run it successfully from an apache webserver, as a normal php script,

and i really need to do that, after so many many tests by a few people we have discarded all typical reasons for this to happen, 

We can run Phantom, Cutycapt, ImageMagick and anything else you can think of successfully from PHP scripts, all except SlimerJS, using similar commands, same servers, same everything

there is obviously a problem somewhere

thank you for your help

**Comment by repetix** [comment]
@javismiles, Working on a similar problem. I know this is an old issue, but can't seem to find the answer to solve my problem. Would you contact me direct and see if you can assist me for 5 minutes? It's identical issue. I have the same server setup except centos 7. I can the command nohup and all that.

The part I'm not understanding is the php script part. Do I do something like this:

<?php
exec('DISPLAY=:1 HOME=path_to_slimer_js path_to_slimer_js/slimerjs somescript');
?>

Or do I need to specify those variables differently and run my exec differently?

**Comment by DarrenCook** [comment]
@repetix That might work. If it does not, try using `shell_exec()` instead of `exec()`. (shell_exec runs it inside a bash shell.)

Alternatively you could use `putenv()` (http://php.net/manual/en/function.putenv.php). Then it would look something like this:

```
<?php
putenv("DISPLAY=:1");
putenv("HOME=/path/to/slimerjs");
shell_exec("/path/to/slimerjs/slimerjs somescript.js");
```

(I've not tested it myself, and it assumes javismiles's 9 Sep 2013 comment is correct. If it is not working, I'd pay attention to javismiles comment about making sure the user running apache has all the permissions they need to see and run slimerjs.)

**Comment by repetix** [comment]
@DarrenCook Thanks Darren. I think I got it to work now. Below is code for anyone else trying to figure it out. It creates an image as the JS file specifies but I'm getting a white images, or blank if you prefer. I'll resolve that and post back with an answer unless you have any ideas.

This is the php code:
`putenv("DISPLAY=:1");
putenv("HOME=/web/screens/");
shell_exec("/slimerjs-bin/slimerjs /web/screens/runthis.js");`

This is the background service command:
`nohup su -c 'Xvfb :1 -auth /etc/Xvfb.auth -nolisten tcp -f /tmp' -s /bin/sh apache > /dev/null 2>&1 &`
- I added 2>&1 to remove the warning message.

**Comment by repetix** [comment]
@DarrenCook  I solved the images being blank issue. We were using phantomjs before and our JS files modeled that. I switched the JS code to a slimerjs format and everything works!

Thanks so much for helping!
