### ISSUE TITLE
Callback is not called when page redirect

### ISSUE THREAD

**Issue by kogeva** [laurentj/slimerjs#90]
Callback is not called when page redirect. You can try this on many sites. So the behaviour of slimerjs differs to phantomjs. And if this behaviour correct, how can I call callback after last redirect on response with status code 200?

**Comment by maganius** [comment]
This issue is fixed? because I have this same problem now, when my main website send a redirect the smilerjs never finish the job and never call the callback.

**Comment by Paxa** [comment]
Also have this problem when page redirects twice
